// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Sequence\Sequence.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Sequence.obj
// 1003 function symbol(s) attributed to this object.

/* type 0x674 */ std::vector<int,std::allocator<int> >::_Emplace_reallocate<int const &>(void *, void *);
void CKeyFrameStore<CAudioTrackKey *>::CKeyFrameStore<CAudioTrackKey *>(void);
void CKeyFrameStore<CBoolTrackKey *>::CKeyFrameStore<CBoolTrackKey *>(void);
void CKeyFrameStore<CColorTrackKey *>::CKeyFrameStore<CColorTrackKey *>(void);
void CKeyFrameStore<CGraphicTrackKey *>::CKeyFrameStore<CGraphicTrackKey *>(void);
void CKeyFrameStore<CInstanceTrackKey *>::CKeyFrameStore<CInstanceTrackKey *>(void);
void CKeyFrameStore<CMessageEventKey *>::CKeyFrameStore<CMessageEventKey *>(void);
void CKeyFrameStore<CMomentEventKey *>::CKeyFrameStore<CMomentEventKey *>(void);
void CKeyFrameStore<CParticleTrackKey *>::CKeyFrameStore<CParticleTrackKey *>(void);
void CKeyFrameStore<CRealTrackKey *>::CKeyFrameStore<CRealTrackKey *>(void);
void CKeyFrameStore<CSequenceTrackKey *>::CKeyFrameStore<CSequenceTrackKey *>(void);
void CKeyFrameStore<CSpriteFramesTrackKey *>::CKeyFrameStore<CSpriteFramesTrackKey *>(void);
void CKeyFrameStore<CStringTrackKey *>::CKeyFrameStore<CStringTrackKey *>(void);
void CKeyFrameStore<CTextTrackKey *>::CKeyFrameStore<CTextTrackKey *>(void);
void Keyframe<CAudioTrackKey *>::Keyframe<CAudioTrackKey *>(void);
void Keyframe<CBoolTrackKey *>::Keyframe<CBoolTrackKey *>(void);
void Keyframe<CColorTrackKey *>::Keyframe<CColorTrackKey *>(void);
void Keyframe<CGraphicTrackKey *>::Keyframe<CGraphicTrackKey *>(void);
void Keyframe<CInstanceTrackKey *>::Keyframe<CInstanceTrackKey *>(void);
void Keyframe<CMessageEventKey *>::Keyframe<CMessageEventKey *>(void);
void Keyframe<CMomentEventKey *>::Keyframe<CMomentEventKey *>(void);
void Keyframe<CParticleTrackKey *>::Keyframe<CParticleTrackKey *>(void);
void Keyframe<CRealTrackKey *>::Keyframe<CRealTrackKey *>(void);
void Keyframe<CSequenceTrackKey *>::Keyframe<CSequenceTrackKey *>(void);
void Keyframe<CSpriteFramesTrackKey *>::Keyframe<CSpriteFramesTrackKey *>(void);
void Keyframe<CStringTrackKey *>::Keyframe<CStringTrackKey *>(void);
void Keyframe<CTextTrackKey *>::Keyframe<CTextTrackKey *>(void);
void CAnimCurve::CAnimCurve(void);
void CAnimCurveChannel::CAnimCurveChannel(void);
void CAudioTrackKey::CAudioTrackKey(void);
void CBoolTrackKey::CBoolTrackKey(void);
void CColorTrackKey::CColorTrackKey(void);
void CCurvePoint::CCurvePoint(void);
void CGraphicTrackKey::CGraphicTrackKey(void);
void CInstanceTrackKey::CInstanceTrackKey(void);
void CMessageEventKey::CMessageEventKey(void);
void CMomentEventKey::CMomentEventKey(void);
void CParticleTrackKey::CParticleTrackKey(void);
void CRealTrackKey::CRealTrackKey(void);
void CSeqStackSnapshot::CSeqStackSnapshot(void *);
void CSequence::CSequence(void);
void CSequenceAudioEffectTrack::CSequenceAudioEffectTrack(void);
void CSequenceAudioTrack::CSequenceAudioTrack(void);
void CSequenceBaseClass::CSequenceBaseClass(void);
void CSequenceBaseTrack::CSequenceBaseTrack(void);
void CSequenceBoolTrack::CSequenceBoolTrack(void);
void CSequenceClipMaskTrack::CSequenceClipMaskTrack(void);
void CSequenceClipMask_MaskTrack::CSequenceClipMask_MaskTrack(void);
void CSequenceClipMask_SubjectTrack::CSequenceClipMask_SubjectTrack(void);
void CSequenceColorTrack::CSequenceColorTrack(void);
void CSequenceGraphicTrack::CSequenceGraphicTrack(void);
void CSequenceGroupTrack::CSequenceGroupTrack(void);
void CSequenceInstanceTrack::CSequenceInstanceTrack(void);
void CSequenceParticleTrack::CSequenceParticleTrack(void);
void CSequenceRealTrack::CSequenceRealTrack(void);
void CSequenceSequenceTrack::CSequenceSequenceTrack(void);
void CSequenceSpriteFramesTrack::CSequenceSpriteFramesTrack(void);
void CSequenceStringTrack::CSequenceStringTrack(void);
void CSequenceTextTrack::CSequenceTextTrack(void);
void CSequenceTrackKey::CSequenceTrackKey(void);
void CSpriteFramesTrackKey::CSpriteFramesTrackKey(void);
void CStringTrackKey::CStringTrackKey(void);
void CTextTrackKey::CTextTrackKey(void);
void TrackEval::TrackEval(void);
void CHashMap<int,int,3>::~CHashMap<int,int,3>(void);
void CHashMap<int,CSequenceBaseTrack *,3>::~CHashMap<int,CSequenceBaseTrack *,3>(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackAudioInfo,3>::~CHashMap<CSeqStackSnapshot,CSeqTrackAudioInfo,3>(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::~CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>::~CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>(void);
void std::vector<float,std::allocator<float> >::~vector<float,std::allocator<float> >(void);
void CSeqStackPush::~CSeqStackPush(void);
void CSeqStackSnapshot::~CSeqStackSnapshot(void);
void CSequence::~CSequence(void);
void CSequenceBaseClass::~CSequenceBaseClass(void);
void CSequenceBaseTrack::~CSequenceBaseTrack(void);
void CSequenceParameterTrack::~CSequenceParameterTrack(void);
void CTrackKeyBase::~CTrackKeyBase(void);
void IKeyframeStore::~IKeyframeStore(void);
void TrackEval::~TrackEval(void);
void * CSeqStackSnapshot::operator=(void *);
bool CKeyFrameStore<CRealTrackKey *>::AddKeyframe(float, float, bool, bool, void *);
bool CKeyFrameStore<CAudioEffectTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CAudioTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CBoolTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CColorTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CGraphicTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CInstanceTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CMessageEventKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CMomentEventKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CParticleTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CRealTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CSequenceTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CSpriteFramesTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CStringTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
bool CKeyFrameStore<CTextTrackKey *>::AddKeyframeCommon(float, float, bool, bool, void *);
void CSequence::AddTrack(void *, bool);
void CSequenceBaseTrack::AddTrack(void *, bool);
void * CAnimCurveChannel::AllocNewCachedPoint(void);
void * CSequenceParameterTrack::AllocNewCachedPoint(int32_t);
void * AnimCurveChannel_prop_GetIterations(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_GetName(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_GetPoints(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_GetType(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_SetIterations(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_SetName(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_SetPoints(void *, void *, void *, int32_t, void *);
void * AnimCurveChannel_prop_SetType(void *, void *, void *, int32_t, void *);
bool AnimCurve_Load(uint8_t*, uint32_t, uint8_t*);
void * AnimCurve_prop_GetChannels(void *, void *, void *, int32_t, void *);
void * AnimCurve_prop_GetName(void *, void *, void *, int32_t, void *);
void * AnimCurve_prop_SetChannels(void *, void *, void *, int32_t, void *);
void * AnimCurve_prop_SetName(void *, void *, void *, int32_t, void *);
bool CSequenceAudioEffectTrack::AreKeyframesDirty(int32_t);
bool CSequenceColorTrack::AreKeyframesDirty(int32_t);
bool CSequenceRealTrack::AreKeyframesDirty(int32_t);
void CSequenceBaseTrack::AssignBuiltinTrackName(void);
void BuildKeyframeArray(void *, void *, int32_t);
uint32_t CHashMapCalculateHash(/* struct 0x9d4d */);
bool CHashMapCompareKeys(/* struct 0x9d4d */, /* struct 0x9d4d */);
void CAnimCurveManager::Clean(void);
void CSequenceManager::Clean(void);
void CSequenceInstance::CleanUpInstances(void);
void CSequenceInstance::CleanUpParticles(void);
void CSequenceInstance::CleanupAudioEmitters(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::CommonDelete(int32_t);
void CAnimCurveChannel::ComputeBezier(void);
void CAnimCurveChannel::ComputeCatmullRom(bool, bool, bool);
void CHashMap<CSeqStackSnapshot,CSeqTrackAudioInfo,3>::ConstructElementInPlace(int32_t, uint32_t, void *, void *);
void CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::ConstructElementInPlace(int32_t, uint32_t, void *, void *);
void CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>::ConstructElementInPlace(int32_t, uint32_t, void *, void *);
void * CurvePoint_prop_GetValue(void *, void *, void *, int32_t, void *);
void * CurvePoint_prop_GetX(void *, void *, void *, int32_t, void *);
void * CurvePoint_prop_SetValue(void *, void *, void *, int32_t, void *);
void * CurvePoint_prop_SetX(void *, void *, void *, int32_t, void *);
void CHashMap<int,CSequenceBaseTrack *,3>::Delete(int32_t);
void CHashMap<int,TrackTag *,3>::Delete(int32_t);
void CAnimCurve::Evaluate(void *, int32_t, int32_t, float, float, float);
void CSequenceManager::EvaluateLayerSequenceElement(void *, bool);
void CSequenceBaseTrack::EvaluateTrack(float, float, void *, uint32_t);
void * CHashMap<int,CSequenceBaseTrack *,3>::Find(int32_t);
void * CHashMap<int,TrackTag *,3>::Find(int32_t);
void * CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>::Find(/* struct 0x9d4d */);
int32_t CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::FindPositionCheckKey(void *);
void CAnimCurve::Free(bool);
void CSequenceBaseClass::Free(bool);
void CSequenceBaseTrack::Free(bool);
float CKeyFrameStore<CGraphicTrackKey *>::GetKeyFrameLength(int32_t, float);
void * CKeyFrameStore<CSpriteFramesTrackKey *>::GetKeyframeAtFrame(float, float);
int32_t CSequenceAudioEffectTrack::GetKeyframeChangeIndex(void);
int32_t CSequenceColorTrack::GetKeyframeChangeIndex(void);
int32_t CSequenceRealTrack::GetKeyframeChangeIndex(void);
int32_t CKeyFrameStore<CGraphicTrackKey *>::GetKeyframeIndexAtFrame(float, float);
int32_t CKeyFrameStore<CInstanceTrackKey *>::GetKeyframeIndexAtFrame(float, float);
int32_t CKeyFrameStore<CParticleTrackKey *>::GetKeyframeIndexAtFrame(float, float);
int32_t CKeyFrameStore<CTextTrackKey *>::GetKeyframeIndexAtFrame(float, float);
bool CKeyFrameStore<CAudioEffectTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CAudioTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CBoolTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CColorTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CGraphicTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CInstanceTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CMessageEventKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CMomentEventKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CParticleTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CRealTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CSequenceTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CSpriteFramesTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CStringTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CTextTrackKey *>::GetKeyframeIndexRange(float, float, void *, void *, float, bool, float);
bool CKeyFrameStore<CAudioEffectTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CAudioTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CBoolTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CColorTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CGraphicTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CInstanceTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CMessageEventKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CMomentEventKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CParticleTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CRealTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CSequenceTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CSpriteFramesTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CStringTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
bool CKeyFrameStore<CTextTrackKey *>::GetKeyframeIndexRanges(int32_t, float, float, float, float, float, /* type 0x674 */, /* type 0x674 */, bool, bool);
void * CAnimCurveManager::GetNewCurve(void);
void * CSequenceManager::GetNewInstance(void);
void CSequence::GetObjectIDsFromTrack(void *, void *, void *);
void * CSequenceManager::GetSequenceFromName(void *);
/* struct 0x9d4d */ CSeqStack::GetSnapshot(void);
void CSequenceManager::HandleAudioTrackUpdate(void *, void *, void *, void *, void *, void *, float, float, float);
void CSequenceManager::HandleInstanceEvent(void *, int32_t, int32_t);
void CSequenceManager::HandleInstanceTrackUpdate(void *, void *, void *, void *, void *, void *, float, float);
void HandleMessageEvents(void *, void *, int32_t, double);
void HandleMomentEvents(void *, void *, int32_t, double);
void CSequenceManager::HandleParticleTrackUpdate(void *, void *, void *, void *, void *, void *, float, float);
void CSequenceManager::HandleSequenceTrackUpdate(void *, void *, void *, void *, void *, void *, void *, void *, void *, float, float, float, bool, bool);
void HandleSequenceWrapping(void *, void *, void *, void *, void *);
void HandleSpriteMessageEvents(void *, int32_t, double, float, float, float, float);
void HandleSpriteSequenceMessageEvents(void *, void *, void *, float, float, float, float, void *, void *, void *, void *);
void CSequenceManager::HandleTextTrackUpdate(void *, void *, float, float);
void CSequenceManager::HandleUpdateTracks(void *, void *, void *, void *, void *, void *, void *, void *, float, float, float, bool);
void CHashMap<int,int,3>::Init(void);
void CHashMap<int,CAudioEffectTrackKey *,0>::Init(void);
void CHashMap<int,CAudioTrackKey *,0>::Init(void);
void CHashMap<int,CBoolTrackKey *,0>::Init(void);
void CHashMap<int,CColorTrackKey *,0>::Init(void);
void CHashMap<int,CGraphicTrackKey *,0>::Init(void);
void CHashMap<int,CInstanceTrackKey *,0>::Init(void);
void CHashMap<int,CMessageEventKey *,0>::Init(void);
void CHashMap<int,CMomentEventKey *,0>::Init(void);
void CHashMap<int,CParticleTrackKey *,0>::Init(void);
void CHashMap<int,CRealTrackKey *,0>::Init(void);
void CHashMap<int,CSequenceBaseTrack *,3>::Init(void);
void CHashMap<int,CSequenceTrackKey *,0>::Init(void);
void CHashMap<int,CSpriteFramesTrackKey *,0>::Init(void);
void CHashMap<int,CStringTrackKey *,0>::Init(void);
void CHashMap<int,CTextTrackKey *,0>::Init(void);
void CHashMap<int,CTrackKeyBase *,0>::Init(void);
void CHashMap<int,TrackTag *,3>::Init(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackAudioInfo,3>::Init(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::Init(void);
void CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>::Init(void);
void CHashMap<int,int,3>::Insert(int32_t, int32_t);
void CHashMap<int,CAudioEffectTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CAudioTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CBoolTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CColorTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CGraphicTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CInstanceTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CMessageEventKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CMomentEventKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CParticleTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CRealTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CSequenceBaseTrack *,3>::Insert(int32_t, void *);
void CHashMap<int,CSequenceTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CSpriteFramesTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CStringTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CTextTrackKey *,0>::Insert(int32_t, void *);
void CHashMap<int,CTrackKeyBase *,0>::Insert(int32_t, void *);
void CHashMap<int,TrackTag *,3>::Insert(int32_t, void *);
void CHashMap<CSeqStackSnapshot,CSeqTrackAudioInfo,3>::Insert(/* struct 0x9d4d */, /* struct 0x9d02 */);
void CHashMap<CSeqStackSnapshot,CSeqTrackInstanceInfo,3>::Insert(/* struct 0x9d4d */, /* struct 0x9d10 */);
void CHashMap<CSeqStackSnapshot,CSeqTrackParticleInfo,3>::Insert(/* struct 0x9d4d */, /* struct 0xa907 */);
bool CSequenceBaseClass::IsDirty(int32_t);
void JS_GenericObjectConstructor(void *, void *, void *, int32_t, void *);
void JS_SequenceEvalNodeObjectConstructor(void *, void *, void *, int32_t, void *);
void JS_SequenceKeyframeObjectConstructor(void *, void *, void *, int32_t, void *);
void JS_SequenceObjectConstructor(void *, void *, void *, int32_t, void *);
void LoadSequence(void *, void *, uint8_t*);
bool CKeyFrameStore<CAudioEffectTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CAudioTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CBoolTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CColorTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CGraphicTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CInstanceTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CMessageEventKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CMomentEventKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CParticleTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CRealTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CSequenceTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CSpriteFramesTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CStringTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CKeyFrameStore<CTextTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CAudioEffectTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CAudioTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CBoolTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CColorTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CGraphicTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CInstanceTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CMessageEventKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CMomentEventKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CParticleTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CRealTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CSequenceTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CSpriteFramesTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CStringTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool Keyframe<CTextTrackKey *>::Mark4GC(/* type 0x675 */, int32_t);
bool CAnimCurve::Mark4GC(/* type 0x675 */, int32_t);
bool CAnimCurveChannel::Mark4GC(/* type 0x675 */, int32_t);
bool CAudioEffectTrackKey::Mark4GC(/* type 0x675 */, int32_t);
bool CColorTrackKey::Mark4GC(/* type 0x675 */, int32_t);
bool CRealTrackKey::Mark4GC(/* type 0x675 */, int32_t);
bool CSequence::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceAudioEffectTrack::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceAudioTrack::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceBaseTrack::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceInstance::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceParameterTrack::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceRealTrack::Mark4GC(/* type 0x675 */, int32_t);
bool CSequenceTrackKey::Mark4GC(/* type 0x675 */, int32_t);
bool TrackEvalNode::Mark4GC(/* type 0x675 */, int32_t);
void MultiplyTrackMatrix(void *, float, float, float, float, float, float, float);
bool CAnimCurveChannel::NeedsRegen(void);
void CSequenceInstance::Pause(void);
void CSequenceManager::PerformInstanceEvents(void *, int32_t, int32_t);
void CSequenceInstance::Play(void);
void CAnimCurve::PreFree(void);
void CSequenceBaseTrack::PreFree(void);
void CSequenceInstance::PreFree(void);
void ProcessMessageEvents(void);
void ProcessMomentEvents(void);
void ProcessSpriteMessageEvents(void);
void CSeqStack::Push(void *);
double REAL_RValue(void *);
void CSequence::RemoveTrack(void *);
void CSequenceBaseTrack::RemoveTrack(void *);
void * SequenceAudioEffectTrackKey_prop_GetCurve(void *, void *, void *, int32_t, void *);
void * SequenceAudioEffectTrackKey_prop_GetValue(void *, void *, void *, int32_t, void *);
void * SequenceAudioEffectTrackKey_prop_SetCurve(void *, void *, void *, int32_t, void *);
void * SequenceAudioEffectTrackKey_prop_SetValue(void *, void *, void *, int32_t, void *);
void SequenceAudioEffectTrack_Load(void *, void *, uint8_t*);
void * SequenceAudioEffectTrack_prop_GetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceAudioEffectTrack_prop_SetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_GetEmitterIndex(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_GetMode(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_GetSoundIndex(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_SetEmitterIndex(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_SetMode(void *, void *, void *, int32_t, void *);
void * SequenceAudioTrackKey_prop_SetSoundIndex(void *, void *, void *, int32_t, void *);
void SequenceAudioTrack_Load(void *, void *, uint8_t*);
void * SequenceBaseTrack_Load(void *, uint8_t*);
void * SequenceBaseTrack_prop_GetBuiltInName(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetEnabled(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetKeyframes(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetLinkedTrack(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetName(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetTracks(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetTraits(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetType(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_GetVisible(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_IsLinked(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetEnabled(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetKeyframes(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetName(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetTracks(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetTraits(void *, void *, void *, int32_t, void *);
void * SequenceBaseTrack_prop_SetVisible(void *, void *, void *, int32_t, void *);
void * SequenceBoolTrackKey_prop_GetValue(void *, void *, void *, int32_t, void *);
void * SequenceBoolTrackKey_prop_SetValue(void *, void *, void *, int32_t, void *);
void SequenceBoolTrack_Load(void *, void *, uint8_t*);
void * SequenceClipMaskTrack_prop_GetMaskTrack(void *, void *, void *, int32_t, void *);
void * SequenceClipMaskTrack_prop_GetSubjectTrack(void *, void *, void *, int32_t, void *);
void * SequenceClipMaskTrack_prop_SetMaskTrack(void *, void *, void *, int32_t, void *);
void * SequenceClipMaskTrack_prop_SetSubjectTrack(void *, void *, void *, int32_t, void *);
void * SequenceColorTrackKey_prop_GetColor(void *, void *, void *, int32_t, void *);
void * SequenceColorTrackKey_prop_GetCurve(void *, void *, void *, int32_t, void *);
void * SequenceColorTrackKey_prop_SetColor(void *, void *, void *, int32_t, void *);
void * SequenceColorTrackKey_prop_SetCurve(void *, void *, void *, int32_t, void *);
void SequenceColorTrack_Load(void *, void *, uint8_t*);
void * SequenceColorTrack_prop_GetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceColorTrack_prop_SetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetActiveTracks(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetCharacterSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetColourAdd(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetColourMultiply(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetCoreColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetDropShadowEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetEffectsEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetEmitterIndex(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetFalloffFactor(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetFalloffMax(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetFalloffRef(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetFrameSizeX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetFrameSizeY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetGain(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetGlowColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetGlowEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetGlowEnd(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetGlowStart(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetImageIndex(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetImageSpeed(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetInstanceID(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetLineSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetMatrix(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetOutlineColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetOutlineDist(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetOutlineEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetParagraphSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetParent(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetParticleSystemID(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetPitch(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetRotation(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetScaleX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetScaleY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetSequence(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetSequenceID(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetShadowColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetShadowOffsetX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetShadowOffsetY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetShadowSoftness(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetSoundIndex(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetSpriteIndex(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetThickness(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetTrack(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetXOrigin(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_GetYOrigin(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetCharacterSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetColourAdd(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetColourMultiply(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetCoreColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetDropShadowEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetEffectsEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetFalloffFactor(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetFalloffMax(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetFalloffRef(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetFrameSizeX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetFrameSizeY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetGain(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetGlowColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetGlowEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetGlowEnd(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetGlowStart(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetImageIndex(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetImageSpeed(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetLineSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetMatrix(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetOutlineColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetOutlineDist(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetOutlineEnabled(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetParagraphSpacing(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetPitch(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetRotation(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetScaleX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetScaleY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetShadowColour(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetShadowOffsetX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetShadowOffsetY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetShadowSoftness(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetThickness(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetX(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetXOrigin(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetY(void *, void *, void *, int32_t, void *);
void * SequenceEvalNode_prop_SetYOrigin(void *, void *, void *, int32_t, void *);
void * SequenceEventKey_prop_GetEvents(void *, void *, void *, int32_t, void *);
void * SequenceEventKey_prop_SetEvents(void *, void *, void *, int32_t, void *);
void * SequenceGraphicTrackKey_prop_GetSpriteIndex(void *, void *, void *, int32_t, void *);
void * SequenceGraphicTrackKey_prop_SetSpriteIndex(void *, void *, void *, int32_t, void *);
void SequenceGraphicTrack_Load(void *, void *, uint8_t*);
void * SequenceInstanceTrackKey_prop_GetObjectIndex(void *, void *, void *, int32_t, void *);
void * SequenceInstanceTrackKey_prop_SetObjectIndex(void *, void *, void *, int32_t, void *);
void SequenceInstanceTrack_Load(void *, void *, uint8_t*);
void * SequenceInstance_prop_GetActiveTracks(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetAsync_Load(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetElementID(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetEvent_Data(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetFinished(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetHeadDirection(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetHeadPosition(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetPaused(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetSequence(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetSpeedScale(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_GetVolume(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_SetHeadDirection(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_SetHeadPosition(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_SetSequence(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_SetSpeedScale(void *, void *, void *, int32_t, void *);
void * SequenceInstance_prop_SetVolume(void *, void *, void *, int32_t, void *);
void * SequenceKeyframeData_prop_GetChannel(void *, void *, void *, int32_t, void *);
void * SequenceKeyframeData_prop_SetChannel(void *, void *, void *, int32_t, void *);
void * SequenceKeyframeStore_prop_GetKeyframes(void *, void *, void *, int32_t, void *);
void * SequenceKeyframeStore_prop_SetKeyframes(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_GetChannels(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_GetDisabled(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_GetKey(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_GetLength(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_GetStretch(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_SetChannels(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_SetDisabled(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_SetKey(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_SetLength(void *, void *, void *, int32_t, void *);
void * SequenceKeyframe_prop_SetStretch(void *, void *, void *, int32_t, void *);
void * SequenceParticleTrackKey_prop_GetParticleSystemIndex(void *, void *, void *, int32_t, void *);
void * SequenceParticleTrackKey_prop_SetParticleSystemIndex(void *, void *, void *, int32_t, void *);
void SequenceParticleTrack_Load(void *, void *, uint8_t*);
void * SequenceRealCurve_Load(void *, uint8_t*, bool);
void * SequenceRealTrackKey_prop_GetCurve(void *, void *, void *, int32_t, void *);
void * SequenceRealTrackKey_prop_GetValue(void *, void *, void *, int32_t, void *);
void * SequenceRealTrackKey_prop_SetCurve(void *, void *, void *, int32_t, void *);
void * SequenceRealTrackKey_prop_SetValue(void *, void *, void *, int32_t, void *);
void SequenceRealTrack_Load(void *, void *, uint8_t*, /* type 0x674 */);
void * SequenceRealTrack_prop_GetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceRealTrack_prop_SetInterpolation(void *, void *, void *, int32_t, void *);
void * SequenceSequenceTrackKey_prop_GetSequence(void *, void *, void *, int32_t, void *);
void * SequenceSequenceTrackKey_prop_SetSequence(void *, void *, void *, int32_t, void *);
void SequenceSequenceTrack_Load(void *, void *, uint8_t*);
void * SequenceSpriteFramesTrackKey_prop_GetImageIndex(void *, void *, void *, int32_t, void *);
void * SequenceSpriteFramesTrackKey_prop_SetImageIndex(void *, void *, void *, int32_t, void *);
void SequenceSpriteFramesTrack_Load(void *, void *, uint8_t*);
void * SequenceStringTrackKey_prop_GetValue(void *, void *, void *, int32_t, void *);
void * SequenceStringTrackKey_prop_SetValue(void *, void *, void *, int32_t, void *);
void SequenceStringTrack_Load(void *, void *, uint8_t*);
void * SequenceTextTrackKey_prop_GetAlignmentH(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetAlignmentV(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetFontIndex(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetOrigin(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetText(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetWrap(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_GetWrapMode(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetAlignmentH(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetAlignmentV(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetFontIndex(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetOrigin(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetText(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetWrap(void *, void *, void *, int32_t, void *);
void * SequenceTextTrackKey_prop_SetWrapMode(void *, void *, void *, int32_t, void *);
void SequenceTextTrack_Load(void *, void *, uint8_t*);
bool Sequence_Prepare(void);
void * Sequence_prop_GetLength(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetLoopmode(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetMessageEventKeyframes(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetMomentKeyframes(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetName(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetPlaybackSpeed(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetPlaybackSpeedType(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetTracks(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetVolume(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetXOrigin(void *, void *, void *, int32_t, void *);
void * Sequence_prop_GetYOrigin(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetLength(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetLoopmode(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetMessageEventKeyframes(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetMomentKeyframes(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetName(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetPlaybackSpeed(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetPlaybackSpeedType(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetTracks(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetVolume(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetXOrigin(void *, void *, void *, int32_t, void *);
void * Sequence_prop_SetYOrigin(void *, void *, void *, int32_t, void *);
void CSequenceInstance::SetInstanceInSequenceStatus(bool);
void CInstance::SetSimpleFlag(void);
void CSequenceInstance::SetupAudioEmitters(void *);
void CSequenceInstance::SetupInstances(void *, int32_t, int32_t, int32_t);
void CAudioEffectTrackKey::SetupObject(void);
void CAudioTrackKey::SetupObject(void);
void CBoolTrackKey::SetupObject(void);
void CColorTrackKey::SetupObject(void);
void CGraphicTrackKey::SetupObject(void);
void CInstanceTrackKey::SetupObject(void);
void CMessageEventKey::SetupObject(void);
void CParticleTrackKey::SetupObject(void);
void CRealTrackKey::SetupObject(void);
void CSequenceAudioEffectTrack::SetupObject(void);
void CSequenceBaseTrack::SetupObject(void);
void CSequenceClipMaskTrack::SetupObject(void);
void CSequenceColorTrack::SetupObject(void);
void CSequenceRealTrack::SetupObject(void);
void CSequenceTrackKey::SetupObject(void);
void CSpriteFramesTrackKey::SetupObject(void);
void CStringTrackKey::SetupObject(void);
void CTextTrackKey::SetupObject(void);
void CTrackKeyBase::SetupObject(void);
void CSequenceBaseClass::SignalChange(void);
void CSequenceInstance::StopAllSounds(void);
void CSequenceInstance::StopAllSoundsAndKeepEmitters(void);
void CSequenceBaseClass::ThreadFree(bool, void *);
void CSequenceBaseTrack::ThreadFree(bool, void *);
void CAnimCurveChannel::UpdateCachedPoints(bool, bool, bool);
void CSequenceAudioEffectTrack::UpdateCachedPoints(int32_t, float);
void CSequenceColorTrack::UpdateCachedPoints(int32_t, float);
void CSequenceRealTrack::UpdateCachedPoints(int32_t, float);
void CKeyFrameStore<CAudioEffectTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CAudioTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CBoolTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CColorTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CGraphicTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CInstanceTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CMessageEventKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CMomentEventKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CParticleTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CRealTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CSequenceTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CSpriteFramesTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CStringTrackKey *>::UpdateDirtiness(void);
void CKeyFrameStore<CTextTrackKey *>::UpdateDirtiness(void);
void Keyframe<CAudioEffectTrackKey *>::UpdateDirtiness(void);
void Keyframe<CAudioTrackKey *>::UpdateDirtiness(void);
void Keyframe<CBoolTrackKey *>::UpdateDirtiness(void);
void Keyframe<CColorTrackKey *>::UpdateDirtiness(void);
void Keyframe<CGraphicTrackKey *>::UpdateDirtiness(void);
void Keyframe<CInstanceTrackKey *>::UpdateDirtiness(void);
void Keyframe<CMessageEventKey *>::UpdateDirtiness(void);
void Keyframe<CMomentEventKey *>::UpdateDirtiness(void);
void Keyframe<CParticleTrackKey *>::UpdateDirtiness(void);
void Keyframe<CRealTrackKey *>::UpdateDirtiness(void);
void Keyframe<CSequenceTrackKey *>::UpdateDirtiness(void);
void Keyframe<CSpriteFramesTrackKey *>::UpdateDirtiness(void);
void Keyframe<CStringTrackKey *>::UpdateDirtiness(void);
void Keyframe<CTextTrackKey *>::UpdateDirtiness(void);
void CAnimCurve::UpdateDirtiness(void);
void CAnimCurveChannel::UpdateDirtiness(void);
void CSequenceBaseClass::UpdateDirtiness(void);
void std::vector<int,std::allocator<int> >::_Change_array(void *, void, void);
void std::vector<float,std::allocator<float> >::_Tidy(void);
void std::vector<int,std::allocator<int> >::_Xlength(void);
void std::vector<float,std::allocator<float> >::_Xlength(void);
/* type 0x674 */ std::allocator<int>::allocate(void);
/* type 0x640 */ std::allocator<float>::allocate(void);
bool CSequenceRealTrack::calculateAnimDistance(int32_t, float, float, float, /* type 0x640 */);
bool CSequenceParameterTrack::evaluate(int32_t, float, float, /* type 0x603 */);
void * Keyframe<CGraphicTrackKey *>::first(void);
void * Keyframe<CParticleTrackKey *>::first(void);
void * Keyframe<CSpriteFramesTrackKey *>::first(void);
void * Keyframe<CTextTrackKey *>::first(void);
bool CSequenceAudioEffectTrack::getCachedChannelVal(int32_t, float, float, /* type 0x640 */);
bool CSequenceParameterTrack::getCachedChannelVal(int32_t, float, float, /* type 0x640 */);
int32_t CKeyFrameStore<CAudioEffectTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CAudioTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CBoolTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CColorTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CGraphicTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CInstanceTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CMessageEventKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CMomentEventKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CParticleTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CRealTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CSequenceTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CSpriteFramesTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CStringTrackKey *>::getKeyframeCount(void);
int32_t CKeyFrameStore<CTextTrackKey *>::getKeyframeCount(void);
int32_t CSequenceBaseTrack::getKeyframeCount(void);
void * CSequenceAudioEffectTrack::getKeyframeStore(void);
void * CSequenceAudioTrack::getKeyframeStore(void);
void * CSequenceBaseTrack::getKeyframeStore(void);
void * CSequenceBoolTrack::getKeyframeStore(void);
void * CSequenceColorTrack::getKeyframeStore(void);
void * CSequenceGraphicTrack::getKeyframeStore(void);
void * CSequenceInstanceTrack::getKeyframeStore(void);
void * CSequenceParticleTrack::getKeyframeStore(void);
void * CSequenceRealTrack::getKeyframeStore(void);
void * CSequenceSequenceTrack::getKeyframeStore(void);
void * CSequenceSpriteFramesTrack::getKeyframeStore(void);
void * CSequenceStringTrack::getKeyframeStore(void);
void * CSequenceTextTrack::getKeyframeStore(void);
void * CSequenceAudioEffectTrack::getKeyframeStoreRef(void);
void * CSequenceAudioTrack::getKeyframeStoreRef(void);
void * CSequenceBaseTrack::getKeyframeStoreRef(void);
void * CSequenceBoolTrack::getKeyframeStoreRef(void);
void * CSequenceColorTrack::getKeyframeStoreRef(void);
void * CSequenceGraphicTrack::getKeyframeStoreRef(void);
void * CSequenceInstanceTrack::getKeyframeStoreRef(void);
void * CSequenceParticleTrack::getKeyframeStoreRef(void);
void * CSequenceRealTrack::getKeyframeStoreRef(void);
void * CSequenceSequenceTrack::getKeyframeStoreRef(void);
void * CSequenceSpriteFramesTrack::getKeyframeStoreRef(void);
void * CSequenceStringTrack::getKeyframeStoreRef(void);
void * CSequenceTextTrack::getKeyframeStoreRef(void);
void * CSequenceBaseTrack::getKeyframes(void);
void * CSequenceBaseTrack::getLinkedTrack(void);
bool CSequenceAudioEffectTrack::getValue(int32_t, float, float, /* type 0x603 */);
bool CSequenceColorTrack::getValue(int32_t, float, float, /* type 0x603 */);
bool CSequenceRealTrack::getValue(int32_t, float, float, /* type 0x603 */);
float CSequenceSpriteFramesTrack::getValue(float);
