// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Support\Support_Data_Structures.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Support_Data_Structures.obj
// 150 function symbol(s) attributed to this object.

void Hash<MapStore>::Hash<MapStore>(int32_t);
void CDS_Map::CDS_Map(void);
void DS_GCProxy::DS_GCProxy(int32_t, /* type 0x603 */);
void CDS_Map::~CDS_Map(void);
void Hash<MapStore>::Add(uint32_t, void *);
void CDS_List::Add(void *);
bool CDS_Map::Add(void *, void *);
bool CDS_Map::Add(void *, double, void *);
void CDS_Priority::Add(void *, void *);
bool AddToDsMap(int32_t, void *, double);
void CDS_Grid::Assign(void *);
void CDS_List::Assign(void *);
void CDS_Map::Assign(void *);
void CDS_Priority::Assign(void *);
void CDS_Queue::Assign(void *);
void CDS_Stack::Assign(void *);
void CDS_Grid::Cell_Operation(int32_t, int32_t, int32_t, int32_t, void *);
void CDS_Priority::Change(void *, void *);
void Hash<MapStore>::Clear(/* type 0x6f9f (LF_ENUM) */);
void CDS_Grid::Clear(void *);
void CDS_List::Clear(void);
void CDS_Map::Clear(void);
void CDS_Priority::Clear(void);
void CDS_Queue::Clear(void);
void CDS_Stack::Clear(void);
int32_t CreateDsMap(int32_t, /* type 0x0 */);
void CDS_Priority::Delete(void *);
void CDS_Priority::DeleteMax(void *);
void CDS_Priority::DeleteMin(void *);
void * CDS_Queue::Dequeue(void);
void CDS_Grid::Disk_Operation(int32_t, double, double, double, void *);
void DoOperation(int32_t, void *, void *);
void CDS_Queue::Enqueue(void *);
int32_t FUNC_GridSort(void *, void *);
int32_t FUNC_ListSort(void *, void *);
void * CDS_Map::Find(void *);
void * CDS_Map::FindNext(void *);
void DS_GCProxy::Free(bool);
void FreeAllDataStructures(void);
uint32_t GenHash(void *);
void * GetDsMap(int32_t);
void * RValue::GetString(void);
void CDS_Grid::Get_Disk_Max(void *, double, double, double);
void CDS_Grid::Get_Disk_Mean(void *, double, double, double);
void CDS_Grid::Get_Disk_Min(void *, double, double, double);
void CDS_Grid::Get_Disk_Sum(void *, double, double, double);
void CDS_Grid::Get_Max(void *, int32_t, int32_t, int32_t, int32_t);
void CDS_Grid::Get_Min(void *, int32_t, int32_t, int32_t, int32_t);
void CDS_Grid::Grid_Operation(int32_t, void *, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
void CDS_List::Insert(int32_t, void *);
void CDS_Map::Mark4GC(/* type 0x675 */, int32_t);
void CDS_Priority::Mark4GC(/* type 0x675 */, int32_t);
bool DS_GCProxy::Mark4GC(/* type 0x675 */, int32_t);
void CDS_Stack::Push(void *);
bool CDS_Grid::ReadFromString(void *, bool);
bool CDS_List::ReadFromString(void *, bool);
bool CDS_Map::ReadFromString(void *, bool);
bool CDS_Priority::ReadFromString(void *, bool);
bool CDS_Queue::ReadFromString(void *, bool);
bool CDS_Stack::ReadFromString(void *, bool);
char* ReadHexString(void *);
void ReadValue(void *, void *, int32_t);
void CDS_Grid::Region_Operation(int32_t, int32_t, int32_t, int32_t, int32_t, void *);
void CDS_List::Replace(int32_t, void *);
bool CDS_Map::Replace(void *, void *);
void CDS_Grid::Resize(int32_t, int32_t);
void * CDS_List::Set(int32_t, void *, void *);
void CDS_Map::Set(void *, void *, void *);
void MapStore::SetKey(void *);
void CDS_Grid::SetSize(int32_t, int32_t);
void MapStore::SetValue(void *);
void CDS_Grid::Shuffle(void);
void CDS_List::Shuffle(void);
void CDS_Grid::Sort(int32_t, int32_t);
void DS_GCProxy::ThreadFree(bool, void *);
void CDS_Grid::WriteToString(void *);
void CDS_List::WriteToString(void *);
void CDS_Map::WriteToString(void *);
void CDS_Priority::WriteToString(void *);
void CDS_Queue::WriteToString(void *);
void CDS_Stack::WriteToString(void *);
void WriteValue(void *, void *);
int32_t YYCompareVal(void *, void *, double, bool);
