// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Room\Room_Layers.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Room_Layers.obj
// 450 function symbol(s) attributed to this object.

/* struct 0xa25a */ std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::emplace<CInstance * const &>(void *);
/* struct 0xa077 */ std::_Hash<std::_Uset_traits<CLayerElementBase *,std::_Uhash_compare<CLayerElementBase *,std::hash<CLayerElementBase *>,std::equal_to<CLayerElementBase *> >,std::allocator<CLayerElementBase *>,0> >::emplace<CLayerElementBase * const &>(void *);
void std::fill<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CInstance *> >,std::_Iterator_base0> *,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CInstance *> >,std::_Iterator_base0> >(void *, void *, void *);
void std::fill<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CLayerElementBase *> >,std::_Iterator_base0> *,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CLayerElementBase *> >,std::_Iterator_base0> >(void *, void *, void *);
void std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >(/* struct 0x98ef */, void *);
void CLayer::CLayer(void);
void CLayerEffectInfo::CLayerEffectInfo(void *);
void CLayerEffectParam::CLayerEffectParam(void);
void CLayerParticleElement::CLayerParticleElement(void);
void CLayerSequenceElement::CLayerSequenceElement(void);
void CLayerTextElement::CLayerTextElement(void);
void CLayerTileElement::CLayerTileElement(void);
void Layer_GCProxy::Layer_GCProxy(void *);
void gm::uilayer::EnumConstant<enum gm::uilayer::Origin>::~EnumConstant<enum gm::uilayer::Origin>(void);
void LinkedList<CLayer>::~LinkedList<CLayer>(void);
void LinkedList<CLayerBackgroundElement>::~LinkedList<CLayerBackgroundElement>(void);
void LinkedList<CLayerInstanceElement>::~LinkedList<CLayerInstanceElement>(void);
void LinkedList<CLayerOldTilemapElement>::~LinkedList<CLayerOldTilemapElement>(void);
void LinkedList<CLayerParticleElement>::~LinkedList<CLayerParticleElement>(void);
void LinkedList<CLayerSequenceElement>::~LinkedList<CLayerSequenceElement>(void);
void LinkedList<CLayerSpriteElement>::~LinkedList<CLayerSpriteElement>(void);
void LinkedList<CLayerTextElement>::~LinkedList<CLayerTextElement>(void);
void LinkedList<CLayerTileElement>::~LinkedList<CLayerTileElement>(void);
void LinkedList<CLayerTilemapElement>::~LinkedList<CLayerTilemapElement>(void);
void LinkedList<CTileSlab>::~LinkedList<CTileSlab>(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<CInstance *,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<CInstance *,void *> > >(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<CLayerElementBase *,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<CLayerElementBase *,void *> > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<CInstance *,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<CInstance *,void *> > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<CLayerElementBase *,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<CLayerElementBase *,void *> > >(void);
void std::_Tidy_guard<std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > > >::~_Tidy_guard<std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > > >(void);
void std::_Uninitialized_backout_al<std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >::~_Uninitialized_backout_al<std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >(void);
void CLayerEffectParam::~CLayerEffectParam(void);
int32_t List<CInstance *>::AddDupCheck(void *);
void * CLayerManager::AddDynamicLayer(void *, int32_t);
void CLayerManager::AddElementToLayer(void *, void *, void *, bool);
void LinkedList<CLayer>::AddFirst(void *);
void LinkedList<CLayerParticleElement>::AddFirst(void *);
void LinkedList<CLayerSequenceElement>::AddFirst(void *);
void LinkedList<CLayerTextElement>::AddFirst(void *);
void LinkedList<CLayerTileElement>::AddFirst(void *);
void LinkedList<CLayerTilemapElement>::AddFirst(void *);
void CLayerManager::AddInstanceToLayer(void *, void *, void *, int32_t);
void LinkedList<CLayer>::AddLast(void *);
void * CLayerManager::AddLayer(void *, int32_t, void *, int32_t);
int32_t CLayerManager::AddNewElement(void *, void *, void *, bool);
int32_t CLayerManager::AddNewElementAtDepth(void *, int32_t, void *, bool, bool);
void CLayerManager::BuildElementRuntimeData(void *, void *, void *);
void CLayerManager::BuildInstanceElementRuntimeData(void *, void *, void *);
void CLayerManager::BuildOldTilemapElementRuntimeData(void *, void *, void *);
void CLayerManager::BuildRoomLayerRuntimeData(void *);
void CLayerManager::BuildRoomLayers(void *, void *);
void CLayerManager::ChangeLayerDepth(void *, void *, int32_t, bool);
void CLayerManager::CleanElementRuntimeData(void *, void *);
void CLayerManager::CleanRoomLayerRuntimeData(void *);
void CLayerManager::CleanRoomLayers(void *);
void CHashMap<int,CLayer *,3>::Clear(bool, bool);
void CHashMap<int,CLayerElementBase *,3>::Clear(bool, bool);
void CHashMap<int,CLayerInstanceElement *,3>::Clear(bool, bool);
void LinkedList<CLayerElementBase>::Clear(/* type 0x6f9f (LF_ENUM) */);
void LinkedList<CTileSlab>::Clear(/* type 0x6f9f (LF_ENUM) */);
void CBackGM2::DeSerialise(void *);
void CLayerManager::DeSerializeLayer(void *, void *);
void DecodeTileMap(/* type 0x675 */, /* type 0x675 */, /* type 0x13 */);
void CHashMap<int,CLayer *,3>::Delete(int32_t);
void CHashMap<int,CLayerElementBase *,3>::Delete(int32_t);
void CHashMap<int,CLayerInstanceElement *,3>::Delete(int32_t);
void CLayerManager::DuplicateRoomLayers(void *, void *);
void F_DrawTile(void *, void *, void *, int32_t, void *);
void F_DrawTilemap(void *, void *, void *, int32_t, void *);
void F_LayerActivate(void *, void *, void *, int32_t, void *);
void F_LayerAddInstance(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundAlpha(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundBlend(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundCreate(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundDestroy(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundExists(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetAlpha(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetBlend(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetHtiled(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetID(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetIndex(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetSpeed(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetSprite(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetStretch(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetVisible(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetVtiled(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetXscale(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundGetYscale(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundHtiled(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundIndex(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundSpeed(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundSprite(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundStretch(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundVisible(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundVtiled(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundXscale(void *, void *, void *, int32_t, void *);
void F_LayerBackgroundYscale(void *, void *, void *, int32_t, void *);
void F_LayerCreate(void *, void *, void *, int32_t, void *);
void F_LayerDeactivate(void *, void *, void *, int32_t, void *);
void F_LayerDepth(void *, void *, void *, int32_t, void *);
void F_LayerDestroy(void *, void *, void *, int32_t, void *);
void F_LayerDestroyInstances(void *, void *, void *, int32_t, void *);
void F_LayerElementMove(void *, void *, void *, int32_t, void *);
void F_LayerExists(void *, void *, void *, int32_t, void *);
void F_LayerForceDrawDepth(void *, void *, void *, int32_t, void *);
void F_LayerGetAll(void *, void *, void *, int32_t, void *);
void F_LayerGetAllElements(void *, void *, void *, int32_t, void *);
void F_LayerGetDepth(void *, void *, void *, int32_t, void *);
void F_LayerGetElementLayer(void *, void *, void *, int32_t, void *);
void F_LayerGetElementType(void *, void *, void *, int32_t, void *);
void F_LayerGetFlexpanelNode(void *, void *, void *, int32_t, void *);
void F_LayerGetForcedDepth(void *, void *, void *, int32_t, void *);
void F_LayerGetHspeed(void *, void *, void *, int32_t, void *);
void F_LayerGetId(void *, void *, void *, int32_t, void *);
void F_LayerGetIdAtDepth(void *, void *, void *, int32_t, void *);
void F_LayerGetName(void *, void *, void *, int32_t, void *);
void F_LayerGetScriptBegin(void *, void *, void *, int32_t, void *);
void F_LayerGetScriptEnd(void *, void *, void *, int32_t, void *);
void F_LayerGetShader(void *, void *, void *, int32_t, void *);
void F_LayerGetTargetRoom(void *, void *, void *, int32_t, void *);
void F_LayerGetType(void *, void *, void *, int32_t, void *);
void F_LayerGetVisible(void *, void *, void *, int32_t, void *);
void F_LayerGetVspeed(void *, void *, void *, int32_t, void *);
void F_LayerGetX(void *, void *, void *, int32_t, void *);
void F_LayerGetY(void *, void *, void *, int32_t, void *);
void F_LayerHasInstance(void *, void *, void *, int32_t, void *);
void F_LayerHspeed(void *, void *, void *, int32_t, void *);
void F_LayerInstanceGetInstance(void *, void *, void *, int32_t, void *);
void F_LayerIsDrawDepthForced(void *, void *, void *, int32_t, void *);
void F_LayerParticleAlpha(void *, void *, void *, int32_t, void *);
void F_LayerParticleAngle(void *, void *, void *, int32_t, void *);
void F_LayerParticleBlend(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetAlpha(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetAngle(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetBlend(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetID(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetInstance(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetSystem(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetX(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetXScale(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetY(void *, void *, void *, int32_t, void *);
void F_LayerParticleGetYScale(void *, void *, void *, int32_t, void *);
void F_LayerParticleX(void *, void *, void *, int32_t, void *);
void F_LayerParticleXScale(void *, void *, void *, int32_t, void *);
void F_LayerParticleY(void *, void *, void *, int32_t, void *);
void F_LayerParticleYScale(void *, void *, void *, int32_t, void *);
void F_LayerResetTargetRoom(void *, void *, void *, int32_t, void *);
void F_LayerScriptBegin(void *, void *, void *, int32_t, void *);
void F_LayerScriptEnd(void *, void *, void *, int32_t, void *);
void F_LayerSequenceAngle(void *, void *, void *, int32_t, void *);
void F_LayerSequenceCreate(void *, void *, void *, int32_t, void *);
void F_LayerSequenceDestroy(void *, void *, void *, int32_t, void *);
void F_LayerSequenceExists(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetAngle(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetHeaddir(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetHeadpos(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetInstance(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetLength(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetSequence(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetSpeedScale(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetX(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetXscale(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetY(void *, void *, void *, int32_t, void *);
void F_LayerSequenceGetYscale(void *, void *, void *, int32_t, void *);
void F_LayerSequenceHeaddir(void *, void *, void *, int32_t, void *);
void F_LayerSequenceHeadpos(void *, void *, void *, int32_t, void *);
void F_LayerSequenceIsFinished(void *, void *, void *, int32_t, void *);
void F_LayerSequenceIsPaused(void *, void *, void *, int32_t, void *);
void F_LayerSequencePause(void *, void *, void *, int32_t, void *);
void F_LayerSequencePlay(void *, void *, void *, int32_t, void *);
void F_LayerSequenceSpeedScale(void *, void *, void *, int32_t, void *);
void F_LayerSequenceX(void *, void *, void *, int32_t, void *);
void F_LayerSequenceXscale(void *, void *, void *, int32_t, void *);
void F_LayerSequenceY(void *, void *, void *, int32_t, void *);
void F_LayerSequenceYscale(void *, void *, void *, int32_t, void *);
void F_LayerSetTargetRoom(void *, void *, void *, int32_t, void *);
void F_LayerSetVisible(void *, void *, void *, int32_t, void *);
void F_LayerShader(void *, void *, void *, int32_t, void *);
void F_LayerSpriteAlpha(void *, void *, void *, int32_t, void *);
void F_LayerSpriteAngle(void *, void *, void *, int32_t, void *);
void F_LayerSpriteBlend(void *, void *, void *, int32_t, void *);
void F_LayerSpriteChange(void *, void *, void *, int32_t, void *);
void F_LayerSpriteCreate(void *, void *, void *, int32_t, void *);
void F_LayerSpriteDestroy(void *, void *, void *, int32_t, void *);
void F_LayerSpriteExists(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetAlpha(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetAngle(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetBlend(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetID(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetIndex(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetSpeed(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetSprite(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetX(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetXScale(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetY(void *, void *, void *, int32_t, void *);
void F_LayerSpriteGetYScale(void *, void *, void *, int32_t, void *);
void F_LayerSpriteIndex(void *, void *, void *, int32_t, void *);
void F_LayerSpriteSpeed(void *, void *, void *, int32_t, void *);
void F_LayerSpriteX(void *, void *, void *, int32_t, void *);
void F_LayerSpriteXScale(void *, void *, void *, int32_t, void *);
void F_LayerSpriteY(void *, void *, void *, int32_t, void *);
void F_LayerSpriteYScale(void *, void *, void *, int32_t, void *);
void F_LayerTextAlpha(void *, void *, void *, int32_t, void *);
void F_LayerTextAngle(void *, void *, void *, int32_t, void *);
void F_LayerTextBlend(void *, void *, void *, int32_t, void *);
void F_LayerTextCharspacing(void *, void *, void *, int32_t, void *);
void F_LayerTextCreate(void *, void *, void *, int32_t, void *);
void F_LayerTextDestroy(void *, void *, void *, int32_t, void *);
void F_LayerTextExists(void *, void *, void *, int32_t, void *);
void F_LayerTextFont(void *, void *, void *, int32_t, void *);
void F_LayerTextFrameh(void *, void *, void *, int32_t, void *);
void F_LayerTextFramew(void *, void *, void *, int32_t, void *);
void F_LayerTextGetAlpha(void *, void *, void *, int32_t, void *);
void F_LayerTextGetAngle(void *, void *, void *, int32_t, void *);
void F_LayerTextGetBlend(void *, void *, void *, int32_t, void *);
void F_LayerTextGetCharspacing(void *, void *, void *, int32_t, void *);
void F_LayerTextGetFont(void *, void *, void *, int32_t, void *);
void F_LayerTextGetFrameh(void *, void *, void *, int32_t, void *);
void F_LayerTextGetFramew(void *, void *, void *, int32_t, void *);
void F_LayerTextGetHalign(void *, void *, void *, int32_t, void *);
void F_LayerTextGetID(void *, void *, void *, int32_t, void *);
void F_LayerTextGetLinespacing(void *, void *, void *, int32_t, void *);
void F_LayerTextGetParagraphspacing(void *, void *, void *, int32_t, void *);
void F_LayerTextGetText(void *, void *, void *, int32_t, void *);
void F_LayerTextGetValign(void *, void *, void *, int32_t, void *);
void F_LayerTextGetWrap(void *, void *, void *, int32_t, void *);
void F_LayerTextGetWrapMode(void *, void *, void *, int32_t, void *);
void F_LayerTextGetX(void *, void *, void *, int32_t, void *);
void F_LayerTextGetXorigin(void *, void *, void *, int32_t, void *);
void F_LayerTextGetXscale(void *, void *, void *, int32_t, void *);
void F_LayerTextGetY(void *, void *, void *, int32_t, void *);
void F_LayerTextGetYorigin(void *, void *, void *, int32_t, void *);
void F_LayerTextGetYscale(void *, void *, void *, int32_t, void *);
void F_LayerTextGetorigin(void *, void *, void *, int32_t, void *);
void F_LayerTextHalign(void *, void *, void *, int32_t, void *);
void F_LayerTextLinespacing(void *, void *, void *, int32_t, void *);
void F_LayerTextOrigin(void *, void *, void *, int32_t, void *);
void F_LayerTextParagraphspacing(void *, void *, void *, int32_t, void *);
void F_LayerTextText(void *, void *, void *, int32_t, void *);
void F_LayerTextValign(void *, void *, void *, int32_t, void *);
void F_LayerTextWrap(void *, void *, void *, int32_t, void *);
void F_LayerTextWrapMode(void *, void *, void *, int32_t, void *);
void F_LayerTextX(void *, void *, void *, int32_t, void *);
void F_LayerTextXorigin(void *, void *, void *, int32_t, void *);
void F_LayerTextXscale(void *, void *, void *, int32_t, void *);
void F_LayerTextY(void *, void *, void *, int32_t, void *);
void F_LayerTextYorigin(void *, void *, void *, int32_t, void *);
void F_LayerTextYscale(void *, void *, void *, int32_t, void *);
void F_LayerTileAlpha(void *, void *, void *, int32_t, void *);
void F_LayerTileBlend(void *, void *, void *, int32_t, void *);
void F_LayerTileChange(void *, void *, void *, int32_t, void *);
void F_LayerTileCreate(void *, void *, void *, int32_t, void *);
void F_LayerTileDestroy(void *, void *, void *, int32_t, void *);
void F_LayerTileExists(void *, void *, void *, int32_t, void *);
void F_LayerTileGetAlpha(void *, void *, void *, int32_t, void *);
void F_LayerTileGetBlend(void *, void *, void *, int32_t, void *);
void F_LayerTileGetRegion(void *, void *, void *, int32_t, void *);
void F_LayerTileGetSprite(void *, void *, void *, int32_t, void *);
void F_LayerTileGetVisible(void *, void *, void *, int32_t, void *);
void F_LayerTileGetX(void *, void *, void *, int32_t, void *);
void F_LayerTileGetXScale(void *, void *, void *, int32_t, void *);
void F_LayerTileGetY(void *, void *, void *, int32_t, void *);
void F_LayerTileGetYScale(void *, void *, void *, int32_t, void *);
void F_LayerTileRegion(void *, void *, void *, int32_t, void *);
void F_LayerTileVisible(void *, void *, void *, int32_t, void *);
void F_LayerTileX(void *, void *, void *, int32_t, void *);
void F_LayerTileXScale(void *, void *, void *, int32_t, void *);
void F_LayerTileY(void *, void *, void *, int32_t, void *);
void F_LayerTileYScale(void *, void *, void *, int32_t, void *);
void F_LayerTilemapCreate(void *, void *, void *, int32_t, void *);
void F_LayerTilemapDestroy(void *, void *, void *, int32_t, void *);
void F_LayerTilemapExists(void *, void *, void *, int32_t, void *);
void F_LayerTilemapGetColmask(void *, void *, void *, int32_t, void *);
void F_LayerTilemapGetID(void *, void *, void *, int32_t, void *);
void F_LayerTilemapSetColmask(void *, void *, void *, int32_t, void *);
void F_LayerVspeed(void *, void *, void *, int32_t, void *);
void F_LayerX(void *, void *, void *, int32_t, void *);
void F_LayerY(void *, void *, void *, int32_t, void *);
void F_SequenceInstanceExists(void *, void *, void *, int32_t, void *);
void F_TileSetEmpty(void *, void *, void *, int32_t, void *);
void F_TileSetFlip(void *, void *, void *, int32_t, void *);
void F_TileSetIndex(void *, void *, void *, int32_t, void *);
void F_TileSetMirror(void *, void *, void *, int32_t, void *);
void F_TileSetRotate(void *, void *, void *, int32_t, void *);
void F_TilemapClear(void *, void *, void *, int32_t, void *);
void F_TilemapGet(void *, void *, void *, int32_t, void *);
void F_TilemapGetAtPixel(void *, void *, void *, int32_t, void *);
void F_TilemapGetCellXAtPixel(void *, void *, void *, int32_t, void *);
void F_TilemapGetCellYAtPixel(void *, void *, void *, int32_t, void *);
void F_TilemapGetFrame(void *, void *, void *, int32_t, void *);
void F_TilemapGetGlobalMask(void *, void *, void *, int32_t, void *);
void F_TilemapGetHeight(void *, void *, void *, int32_t, void *);
void F_TilemapGetMask(void *, void *, void *, int32_t, void *);
void F_TilemapGetTileHeight(void *, void *, void *, int32_t, void *);
void F_TilemapGetTileWidth(void *, void *, void *, int32_t, void *);
void F_TilemapGetTileset(void *, void *, void *, int32_t, void *);
void F_TilemapGetWidth(void *, void *, void *, int32_t, void *);
void F_TilemapGetX(void *, void *, void *, int32_t, void *);
void F_TilemapGetY(void *, void *, void *, int32_t, void *);
void F_TilemapSet(void *, void *, void *, int32_t, void *);
void F_TilemapSetAtPixel(void *, void *, void *, int32_t, void *);
void F_TilemapSetGlobalMask(void *, void *, void *, int32_t, void *);
void F_TilemapSetHeight(void *, void *, void *, int32_t, void *);
void F_TilemapSetMask(void *, void *, void *, int32_t, void *);
void F_TilemapSetWidth(void *, void *, void *, int32_t, void *);
void F_TilemapTileGetEmpty(void *, void *, void *, int32_t, void *);
void F_TilemapTileGetFlip(void *, void *, void *, int32_t, void *);
void F_TilemapTileGetIndex(void *, void *, void *, int32_t, void *);
void F_TilemapTileGetMirror(void *, void *, void *, int32_t, void *);
void F_TilemapTileGetRotate(void *, void *, void *, int32_t, void *);
void F_TilemapTileset(void *, void *, void *, int32_t, void *);
void F_TilemapX(void *, void *, void *, int32_t, void *);
void F_TilemapY(void *, void *, void *, int32_t, void *);
void * CHashMap<int,CLayerInstanceElement *,3>::Find(int32_t);
void * CInstance::Find(int32_t);
void Layer_GCProxy::Free(bool);
void * CParticleSystem::Get(int32_t);
void * CLayerManager::GetElementFromID(void *, int32_t, void *);
void * ObjectPool<CLayer>::GetFromPool(void);
void * ObjectPool<CLayerBackgroundElement>::GetFromPool(void);
void * ObjectPool<CLayerInstanceElement>::GetFromPool(void);
void * ObjectPool<CLayerOldTilemapElement>::GetFromPool(void);
void * ObjectPool<CLayerParticleElement>::GetFromPool(void);
void * ObjectPool<CLayerSequenceElement>::GetFromPool(void);
void * ObjectPool<CLayerSpriteElement>::GetFromPool(void);
void * ObjectPool<CLayerTextElement>::GetFromPool(void);
void * ObjectPool<CLayerTileElement>::GetFromPool(void);
void * ObjectPool<CLayerTilemapElement>::GetFromPool(void);
void * CLayerManager::GetLayerFromID(void *, int32_t);
void * CLayerManager::GetLayerWithDepth(void *, int32_t, bool);
void * CLayerManager::GetTargetRoomObj(void);
/* struct 0x7e9c */ CLayerManager::GetTilesFromPool(int32_t);
bool CLayer::HasBeginScript(void);
bool CLayer::HasEndScript(void);
void CHashMap<int,CLayer *,3>::Init(void);
void CHashMap<int,CLayerElementBase *,3>::Init(void);
void CHashMap<int,CLayerInstanceElement *,3>::Init(void);
void CLayerManager::Init(void);
void CLayerManager::InitLayerFunctions(void);
void CHashMap<int,CLayer *,3>::Insert(int32_t, void *);
void CHashMap<int,CLayerElementBase *,3>::Insert(int32_t, void *);
void CHashMap<int,CLayerInstanceElement *,3>::Insert(int32_t, void *);
void LinkedList<CLayer>::InsertAfter(void *, void *);
bool Layer_GCProxy::Mark4GC(/* type 0x675 */, int32_t);
void * Object_Data(int32_t);
int32_t IBuffer::ReadS32(void);
bool LinkedList<CLayer>::Remove(void *);
bool LinkedList<CLayerElementBase>::Remove(void *);
void CLayerManager::RemoveElement(void *, void *, void *, bool, bool);
void CLayerManager::RemoveElement(void *, int32_t, bool, bool, bool);
void CLayerManager::RemoveInstance(void *, void *);
void CLayerManager::RemoveInstanceFromLayer(void *, void *, void *);
void CLayerManager::RemoveLayer(void *, int32_t, bool);
void CLayerTilemapElement::Resize(int32_t, int32_t);
void CLayerManager::RestoreUILayers(void *);
void CLayer::RestoreView(void);
void ObjectPool<CLayer>::ReturnToPool(void *);
void ObjectPool<CLayerInstanceElement>::ReturnToPool(void *);
void CLayer::SetBeginScript(void *);
void CLayer::SetEffect(void *);
void CLayer::SetEndScript(void *);
void CLayer::SetView(void);
void Layer_GCProxy::ThreadFree(bool, void *);
void CLayerManager::TransitionUILayers(void *);
void CLayerManager::UpdateInstanceActivation(void *, void *);
void std::_Iterator_base0::_Adopt(void *);
void std::_Hash_vec<std::allocator<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CInstance *> >,std::_Iterator_base0> > >::_Assign_grow(void, void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<CLayerElementBase *> >,std::_Iterator_base0> > >::_Assign_grow(void, void);
void std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >::_Buy_raw(void);
/* type 0x22 */ std::_Ceiling_of_log_2(void);
/* type 0x22 */ std::_Floor_of_log_2(/* type 0x23 */);
/* type 0x23 */ std::_Fnv1a_append_bytes(/* type 0x23 */, void *, void);
void std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::_Forced_rehash(/* type 0x23 */);
void std::_Hash<std::_Uset_traits<CLayerElementBase *,std::_Uhash_compare<CLayerElementBase *,std::hash<CLayerElementBase *>,std::equal_to<CLayerElementBase *> >,std::allocator<CLayerElementBase *>,0> >::_Forced_rehash(/* type 0x23 */);
void * std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::_Insert_new_node_before(void, void *, void *);
void std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::_Rehash_for_1(void);
void std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >::_Tidy(void);
void * std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::_Unchecked_erase(void *, void *);
void * std::_Hash<std::_Uset_traits<CLayerElementBase *,std::_Uhash_compare<CLayerElementBase *,std::hash<CLayerElementBase *>,std::equal_to<CLayerElementBase *> >,std::allocator<CLayerElementBase *>,0> >::_Unchecked_erase(void *, void *);
void std::vector<gm::uilayer::EnumConstant<enum gm::uilayer::Origin>,std::allocator<gm::uilayer::EnumConstant<enum gm::uilayer::Origin> > >::_Xlength(void);
int32_t YYSlot<YYObjectBase>::allocSlot(void *);
void std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::clear(void);
void std::_Hash<std::_Uset_traits<CLayerElementBase *,std::_Uhash_compare<CLayerElementBase *,std::hash<CLayerElementBase *>,std::equal_to<CLayerElementBase *> >,std::allocator<CLayerElementBase *>,0> >::clear(void);
int32_t snprintf(void *, void, void *, char *);
