// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Yoga\GMYoga.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\GMYoga.obj
// 109 function symbol(s) attributed to this object.

void FLEXPANEL_CreateValueResult(void *, void *);
void * FLEXPANEL_Create_Node(void *);
void FLEXPANEL_Delete_Node(void *, bool);
void * FLEXPANEL_Find_Child(void *, void *, int32_t);
void FLEXPANEL_GetStruct(void *, void *);
void FLEXPANEL_InitHashes(void);
bool FLEXPANEL_Init_From_Struct(void *, void *);
/* struct 0xaad6 */ FLEXPANEL_NodeMeasureFunc(void *, float, /* type 0xaadb (LF_ENUM) */, float, /* type 0xaadb (LF_ENUM) */);
void FLEXPANEL_YGValue_ToStruct(void *, void *, /* struct 0x18260 */);
void F_FlexboxCalculateLayout(void *, void *, void *, int32_t, void *);
void F_FlexboxCreateNode(void *, void *, void *, int32_t, void *);
void F_FlexboxDeleteNode(void *, void *, void *, int32_t, void *);
void F_FlexboxGetRoundingScale(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetChild(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetChildHash(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetData(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetLayoutPosition(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetMeasureFunction(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetName(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetNumChildren(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetParent(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStruct(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleAlignContent(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleAlignItems(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleAlignSelf(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleAspectRatio(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleBorder(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleDirection(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleDisplay(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlex(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlexBasis(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlexDirection(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlexGrow(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlexShrink(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleFlexWrap(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleGap(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleJustifyContent(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleMargin(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleMaxHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleMaxWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleMinHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleMinWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStylePadding(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStylePosition(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStylePositionType(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeGetStyleWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeInsertChild(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeRemoveAllChildren(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeRemoveChild(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetAlignContent(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetAlignItems(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetData(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetFlexDirection(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetFlexWrap(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetGap(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetMeasureFunction(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetName(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleAlignSelf(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleAspectRatio(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleBorder(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleDirection(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleDisplay(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleFlex(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleFlexBasis(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleFlexGrow(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleFlexShrink(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleJustifyContent(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleMargin(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleMaxHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleMaxWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleMinHeight(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleMinWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStylePadding(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStylePosition(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStylePositionType(void *, void *, void *, int32_t, void *);
void F_FlexboxNodeSetStyleWidth(void *, void *, void *, int32_t, void *);
void F_FlexboxSetRoundingScale(void *, void *, void *, int32_t, void *);
void InitYogaFunctions(void);
void SetCSSValue(void *, void *, void *, void *, void *);
void SetCSSValueEdge(void *, void *, /* type 0xc435 (LF_ENUM) */, void *, void *);
void YYContext::SetData(void *);
void YYContext::SetName(void *);
void YGNodeGetDepthRecursive(void *, void *);
void * YYGetNodeRef(void *, int32_t);
void ensure_ui_tree(void *);
