// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Graphics_API\Graphics_Perf.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Graphics_Perf.obj
// 246 function symbol(s) attributed to this object.

void DBGDropDown::DBGDropDown(void *, void *, int32_t, void *, void *);
void DBGSection::DBGSection(void *, bool);
void DBGSlider::DBGSlider(void *, void *, double, double, double);
void DBGSprite::DBGSprite(void *, void *, void *, int32_t, int32_t);
void DBGView::DBGView(void *, bool, int32_t, int32_t, int32_t, int32_t);
void GMMemoryView::GMMemoryView(void);
void ImVector<char>::~ImVector<char>(void);
void ImVector<int>::~ImVector<int>(void);
void ImVector<ImVec2>::~ImVector<ImVec2>(void);
void AutoMutex::~AutoMutex(void);
void DBGControl::~DBGControl(void);
void DBGDropDown::~DBGDropDown(void);
void GMDebugWindowBase::~GMDebugWindowBase(void);
void ScrollingBuffer::~ScrollingBuffer(void);
void operator delete(/* type 0x603 */, /* struct 0x1a205 */, /* type 0x603 */);
void ActionFontInfo(void);
void DBGView::Add(void *);
void GMDebugViewControl::Add(void *);
void GMDebugViewControl::Add(void *);
void ScrollingBuffer::AddPoint(float, float);
void GraphicsPerf::BeginDebugDraw(void);
void GraphicsPerf::BeginFrame(void);
void GMDebugWindowBase::BeginRender(void);
int32_t GMLogWindow::CandidateCompareFunc(void *, void *);
void GMLogWindow::CheckAndPopulateCandidates(void *, void *);
void DBGButton::CopyFromClipboard(void *, void *);
void DBGCheckBox::CopyFromClipboard(void *, void *);
void DBGColour::CopyFromClipboard(void *, void *);
void DBGDropDown::CopyFromClipboard(void *, void *);
void DBGSameLine::CopyFromClipboard(void *, void *);
void DBGSection::CopyFromClipboard(void *, void *);
void DBGSlider::CopyFromClipboard(void *, void *);
void DBGSprite::CopyFromClipboard(void *, void *);
void DBGText::CopyFromClipboard(void *, void *);
void DBGTextInput::CopyFromClipboard(void *, void *);
void DBGTextSeparator::CopyFromClipboard(void *, void *);
void DBGView::CopyFromClipboard(void *, void *);
void DBGWatch::CopyFromClipboard(void *, void *);
void LogText::CopyFromClipboard(void *, void *);
void DBGButton::CopyToClipboard(void *);
void DBGCheckBox::CopyToClipboard(void *);
void DBGColour::CopyToClipboard(void *);
void DBGDropDown::CopyToClipboard(void *);
void DBGSameLine::CopyToClipboard(void *);
void DBGSection::CopyToClipboard(void *);
void DBGSlider::CopyToClipboard(void *);
void DBGSprite::CopyToClipboard(void *);
void DBGText::CopyToClipboard(void *);
void DBGTextInput::CopyToClipboard(void *);
void DBGTextSeparator::CopyToClipboard(void *);
void DBGView::CopyToClipboard(void *);
void DBGWatch::CopyToClipboard(void *);
void LogText::CopyToClipboard(void *);
void GMLogWindow::CreateArgumentArray(/* type 0x670 */, int32_t, /* type 0x674 */, void *);
/* type 0x603 */ Debug_AddCheckBox(void *, int32_t);
/* type 0x603 */ Debug_AddColour(void *, int32_t);
/* type 0x603 */ Debug_AddDropDown(void *, int32_t, void *);
/* type 0x603 */ Debug_AddDropDown(void *, int32_t, int32_t, void *, void *);
/* type 0x603 */ Debug_AddSlider(void *, int32_t, double, double, double);
/* type 0x603 */ Debug_AddSliderInt(void *, int32_t, int32_t, int32_t, int32_t);
/* type 0x603 */ Debug_AddSprite(void *, int32_t, int32_t, int32_t, int32_t);
/* type 0x603 */ Debug_AddText(void *, int32_t);
/* type 0x603 */ Debug_AddTextInput(void *, int32_t, void *);
/* type 0x603 */ Debug_AddTextSeparator(void *, int32_t, int32_t);
/* type 0x603 */ Debug_AddWatch(void *, int32_t);
int32_t Debug_CreateRef2(int32_t, int32_t);
int32_t Debug_CreateRef(int32_t, int32_t);
int32_t Debug_CreateRef(int32_t, int32_t, int32_t);
int32_t Debug_CreateRef(void *, void *, int32_t, int32_t);
int32_t Debug_CreateRefDBIndex(void *, void *, int32_t, int32_t);
void GMLogWindow::DrawAutoComplete(void *, void *, void *);
void GMFlexPanelView::DrawFlexPanel(void *, /* struct 0xcf46 */, void *, float, /* type 0x674 */);
void GraphicsPerf::EndDebugDraw(void);
void GraphicsPerf::EndFrame(void);
void GMDebugWindowBase::EndRender(void);
void GMLogWindow::Execute(int32_t, void *, bool);
bool DBGRef::Get(void *);
void GMFlexPanelView::GetFlexPanelChildMaxContentXY(void *, /* struct 0xcf46 */, /* type 0x674 */, /* type 0x674 */, bool);
bool ImGui_ImplGMGFX_CreateDeviceObjects(void);
void ImGui_ImplGMGFX_RenderDrawData(void *);
void ImGui_ImplGMGFX_SetupRenderState(void *, int32_t, int32_t);
void ImGui_ImplGM_NewFrame(void);
/* type 0xced0 (LF_ENUM) */ ImGui_ImplGM_VirtualKeyToImGuiKey(int32_t);
void ImGui_OutputFunc(void *);
void DBGControl::InsertTail(void *, void *, void *);
int32_t GMLogWindow::MyCallback(void *);
void DBGDropDown::ParseElements(void *);
void GraphicsPerf::Pop(void);
void GMLogWindow::PopulateCandidates(void *, void *);
void GMDebugWindowBase::PostRender(void);
void GMDebugWindowBase::PreRender(void);
void GraphicsPerf::Push(uint32_t, void *);
void DBGButton::Render(void);
void DBGCheckBox::Render(void);
void DBGColour::Render(void);
void DBGDropDown::Render(void);
void DBGSameLine::Render(void);
void DBGSection::Render(void);
void DBGSlider::Render(void);
void DBGSliderInt::Render(void);
void DBGSprite::Render(void);
void DBGSpriteButton::Render(void);
void DBGText::Render(void);
void DBGTextInput::Render(void);
void DBGTextSeparator::Render(void);
void DBGView::Render(void);
void DBGWatch::Render(void);
void GMAudioWindow::Render(void);
void GMDebugViewControl::Render(void);
void GMFPSWindow::Render(void);
void GMFlexPanelView::Render(void);
void GMLogWindow::Render(void);
void GMMemoryView::Render(void);
void GMTextureGroupView::Render(void);
void GMTextureView::Render(void);
void LogText::Render(void);
/* struct 0xf13e */ GMAudioWindow::SampleGetter(int32_t, /* type 0x603 */);
bool DBGRef::Set(void *);
int32_t SetDbgRefSlot(void *);
void GMDebugWindowBase::UpdateWindowState(void);
void ImVector<char>::clear(void);
void ImVector<int>::push_back(void *);
void ImVector<ImVec2>::push_back(void *);
void ImVector<char>::reserve(int32_t);
void ImVector<int>::reserve(int32_t);
void ImVector<double>::reserve(int32_t);
void ImVector<ImVec2>::reserve(int32_t);
void ImVector<char>::resize(int32_t);
void GMTextureView::restoreDrawAlphaBlend(void *, void *);
void GMTextureView::restoreTexFilter(void *, void *);
void GMTextureView::setDrawAlphaBlend(void *, void *);
void GMTextureView::setNoTexFilter(void *, void *);
void GMTextureView::storeDrawAlphaBlend(void *, void *);
