// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Sprite\Sprite_Class.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Sprite_Class.obj
// 150 function symbol(s) attributed to this object.

void CNineSliceData::CNineSliceData(void);
void CSprite::CSprite(void);
void CNineSliceCacheData::~CNineSliceCacheData(void);
void CSprite::AddFromBitmap(void *, bool, bool, bool);
void CSprite::AddFromSprite(void *);
void CNineSliceCacheData::AddVert(float, float, float, float);
void CSprite::Assign(void *);
bool CSprite::BuildSWFData(char*, int32_t, int32_t);
bool CSprite::BuildVectorData(char*, int32_t, int32_t, int32_t);
bool CSprite::CalculateVectorShapeNumVerts(void *);
void CSprite::Clear(void);
void CSprite::ClearSWFData(void);
void CSprite::ClearVectorData(void);
bool CSprite::ColMaskSet(float, float, uint8_t*, float, float, bool);
bool CSprite::CollisionTilemapLine(void *, float, float, float, float);
void CSprite::ComputeBoundingBox(void);
void CSprite::ComputeCullRadius(void);
void CSprite::ComputeMask(bool, int32_t, void *, int32_t, uint32_t);
bool CSprite::ConstructVectorShapeVB(void *, int32_t, void *, float, bool, bool, void *, /* type 0x674 */, /* type 0x674 */, void *, float, float);
void CSprite::CreateFromBitmap(void *, bool, bool, bool, bool, int32_t, int32_t, bool);
void CSprite::CreateMask(void);
void CNineSliceData::Draw(float, float, float, float, float, uint32_t, float, int32_t, void *, bool);
void CSprite::Draw(float, float, float, float, float, float, uint32_t, float);
void CSprite::Draw(void *);
void CNineSliceData::DrawFromCache(float, float, float, uint32_t, float, void *, bool);
void CSprite::DrawGeneral(float, float, float, float, float, float, float, float, float, float, uint32_t, uint32_t, uint32_t, uint32_t, float);
void CSprite::DrawPart(float, float, float, float, float, float, float, float, float, uint32_t, float);
void CSprite::DrawPos(float, float, float, float, float, float, float, float, float, uint32_t, float);
void CSprite::DrawSWF(int32_t, float, float, float, float, float, float, float, uint32_t, float);
int32_t CSprite::DrawSWFObject(void *, void *, void *, uint32_t, bool);
void CSprite::DrawSWFTiled(int32_t, float, float, float, float, bool, bool, float, float, float, float, uint32_t, float);
void CSprite::DrawSimple(float, float, float);
void CSprite::DrawSimple(void *);
void CSprite::DrawStretched(float, float, float, float, float, uint32_t, float);
void CSprite::DrawTiled(float, float, float, float, float, bool, bool, float, float, float, float, uint32_t, float);
void CSprite::DrawVector(int32_t, float, float, float, float, float, float, float, uint32_t, float);
int32_t CSprite::DrawVectorShape(void *, void *, void *, uint32_t, bool);
int32_t CSprite::DrawVectorShape(void *, /* struct 0x73f7 */, float, bool, bool, void *, uint32_t, /* type 0x674 */, /* type 0x674 */, void *, float, float);
void CSprite::DrawVectorTiled(int32_t, float, float, float, float, bool, bool, float, float, float, float, uint32_t, float);
void F_SphereIsVisible(void *, void *, void *, int32_t, void *);
int32_t CHashMap<VectorShapeCacheGroupKey *,VectorShapeCacheGroup *,3>::FindPositionCheckKey(void *);
void CNineSliceData::Free(bool);
void Sprite_GCProxy::Free(bool);
void CSprite::FreeBitmapData(void);
void Vector_Shape::FreeCache(void);
void CSprite::FreeMask(void);
bool FreeSpaceFromVectorShapeLRU(int32_t, void *, bool, /* type 0x13 */, int32_t);
void CSprite::FreeTexture(void);
bool CSprite::GenerateBitmapData(void);
void * CSprite::GenerateBitmapDataForFrame(int32_t);
void CNineSliceData::GenerateCacheData(float, float, int32_t, void *);
uint8_t* CSprite::GetMaskData(int32_t);
void CSprite::GetScaledBoundingBox(float, float);
bool CSprite::GetSkeletonBounds(void *, void *);
bool CSprite::GetSkeletonSpriteSize(void *, void *, void *);
/* type 0x13 */ CSprite::GetTexture(int32_t);
void CHashMap<VectorShapeCacheGroupKey *,VectorShapeCacheGroup *,3>::Init(void);
void CSprite::InitLocalTPE(void);
void CSprite::InitTexture(bool, bool);
void CHashMap<VectorShapeCacheGroupKey *,VectorShapeCacheGroup *,3>::Insert(void *, void *);
bool CSprite::LoadFromASTCData(/* type 0x603 */, int32_t, int32_t, bool, bool, bool, int32_t, int32_t, bool);
void CSprite::LoadFromAnimation(void *, bool, bool);
bool CSprite::LoadFromBuffer(/* type 0x603 */, int32_t, int32_t, bool, bool, bool, int32_t, int32_t, bool);
bool CSprite::LoadFromChunk(void *, uint8_t*);
bool CSprite::LoadFromDDSData(/* type 0x603 */, int32_t, int32_t, bool, bool, bool, int32_t, int32_t, bool);
bool CSprite::LoadFromData(/* type 0x603 */, int32_t, int32_t, int32_t, bool, bool, bool, int32_t, int32_t, bool);
bool CSprite::LoadFromFile(void *, int32_t, bool, bool, bool, bool, int32_t, int32_t, bool);
bool CSprite::LoadFromFileAsync(void *, int32_t, int32_t, int32_t, bool, bool);
bool CSprite::LoadFromYYSFile(void *, int32_t, int32_t);
void CSprite::LoadStrip(void *, bool, bool, int32_t, bool);
bool Sprite_GCProxy::Mark4GC(/* type 0x675 */, int32_t);
void * NineSlice_prop_GetBottom(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_GetEnabled(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_GetLeft(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_GetRight(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_GetTilemode(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_GetTop(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetBottom(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetEnabled(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetLeft(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetRight(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetTilemode(void *, void *, void *, int32_t, void *);
void * NineSlice_prop_SetTop(void *, void *, void *, int32_t, void *);
bool CSprite::OrigPreciseCollisionLine(int32_t, void *, int32_t, int32_t, float, float, float, int32_t, int32_t, int32_t, int32_t);
bool CSprite::OrigPreciseCollisionRectangle(int32_t, void *, int32_t, int32_t, float, float, float, void *);
bool CSprite::PreciseCollisionEllipse(int32_t, void *, int32_t, int32_t, float, float, float, void *);
bool CSprite::PreciseCollisionLine(int32_t, void *, float, float, float, float, float, float, float, float, float);
bool CSprite::PreciseCollisionPoint(int32_t, void *, int32_t, int32_t, float, float, float, float, float);
bool CSprite::PreciseCollisionRectangle(int32_t, void *, float, float, float, float, float, void *);
bool CSprite::PreciseCollisionTilemap(int32_t, void *, float, float, float, float, float, void *, void *, uint8_t*, void *);
bool CSprite::PreciseCollisionTilemapEllipse(uint8_t*, void *, void *, float, float, float, float);
bool CSprite::PreciseCollisionTilemapLine(uint8_t*, void *, void *, float, float, float, float);
bool CSprite::PreciseCollisionTilemapRect(uint8_t*, void *, void *, float, float, float, float);
bool Vector_Shape::RemoveCacheEntry(void *, bool);
uint32_t CSprite::SampleGradient(void *, int32_t);
void CSprite::SetAlphaFromSprite(void *);
void CSprite::SetBoundingBox(void *);
void CSprite::Set_NineSliceData(void *);
void CSprite::SetupBitmapTexture(void *, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint8_t*, uint8_t*, uint8_t*, uint8_t*, uint32_t);
bool CSprite::SetupFromRequest(void *);
void CSprite::SetupGradientTexture(void *);
void CSprite::SetupSWFCollisionMasks(void *, /* type 0x674 */, int32_t);
bool SphereIsVisible(void *, float, bool);
void CSprite::TMaskCreate(void *, void *, void *, int32_t, int32_t, uint32_t);
void CNineSliceData::ThreadFree(bool, void *);
void Sprite_GCProxy::ThreadFree(bool, void *);
float fwrap(float, float);
