// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\multiplayer\lib\backends\synctest.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\synctest.obj
// 157 function symbol(s) attributed to this object.

void * std::operator<<<std::char_traits<char> >(void *, void *);
void * std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Reallocate_grow_by<<lambda_b986da8d428e4af07c64af60eec09b61>,unsigned __int64,unsigned __int64,char>(void, /* struct 0x1adbf */, /* type 0x23 */, /* type 0x23 */, char);
void * std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Reallocate_grow_by<<lambda_e1befb086ad3257e3f042a63030725f7>,unsigned __int64,char>(void, /* struct 0x1addd */, /* type 0x23 */, char);
void * std::use_facet<std::ctype<char> >(void *);
void * std::use_facet<std::numpunct<char> >(void *);
void SyncTestBackend::SyncTestBackend(void *, void *, int32_t, int32_t, bool, bool);
void std::_Locinfo::_Locinfo(void *);
void std::bad_cast::bad_cast(void *);
void std::bad_cast::bad_cast(void);
void std::ios_base::failure::failure(void *);
void std::ios_base::failure::failure(void *, void *);
void std::basic_ostream<char,std::char_traits<char> >::sentry::sentry(void *);
void std::_Tidy_guard<std::numpunct<char> >::~_Tidy_guard<std::numpunct<char> >(void);
void std::_Yarn<char>::~_Yarn<char>(void);
void std::_Yarn<wchar_t>::~_Yarn<wchar_t>(void);
void std::unique_ptr<std::_Facet_base,std::default_delete<std::_Facet_base> >::~unique_ptr<std::_Facet_base,std::default_delete<std::_Facet_base> >(void);
void SyncTestBackend::SavedInfo::~SavedInfo(void);
void std::_Locinfo::~_Locinfo(void);
void std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base(void);
void std::bad_cast::~bad_cast(void);
void std::locale::facet::~facet(void);
void std::ios_base::failure::~failure(void);
void std::locale::~locale(void);
void std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry(void);
void * std::vector<GameInput,std::allocator<GameInput> >::operator=(void *);
void * std::basic_ostream<char,std::char_traits<char> >::operator<<(int32_t);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::AddLocalInput(int32_t, /* type 0x603 */, int32_t);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::AddPlayer(void *, void *);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::DoPoll(void);
int32_t SyncTestBackend::GetLastConfirmedFrame(void);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::IncrementFrame(void);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::SendChatMsg(void *, int32_t);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::SetPlayerPrefs(char*, uint32_t);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::SetPlayerPrefs(char*, uint32_t, uint32_t);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::StartGame(void);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::SyncInput(/* type 0x603 */, int32_t, void *);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::SyncOnFrame(bool);
/* type 0x13663 (LF_ENUM) */ SyncTestBackend::UseRandomInput(bool);
void std::vector<GameInput,std::allocator<GameInput> >::_Clear_and_reserve_geometric(void);
void * std::locale::facet::_Decref(void);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::_Fput(/* struct 0x2876 */, void *, char, void *, /* type 0x23 */);
/* type 0x23 */ std::ctype<char>::_Getcat(void *, void *);
/* type 0x23 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::_Getcat(void *, void *);
/* type 0x23 */ std::numpunct<char>::_Getcat(void *, void *);
void std::locale::facet::_Incref(void);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::_Iput(/* struct 0x2876 */, void *, char, char*, /* type 0x23 */);
void std::basic_ostream<char,std::char_traits<char> >::_Osfx(void);
/* type 0x13 */ std::basic_streambuf<char,std::char_traits<char> >::_Pnavail(void);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::_Rep(/* struct 0x2876 */, char, /* type 0x23 */);
void std::_Throw_bad_cast(void);
void std::vector<GameInput,std::allocator<GameInput> >::_Xlength(void);
void * std::allocator<GameInput>::allocate(void);
void * std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign(void, void);
char std::numpunct<char>::do_decimal_point(void);
/* struct 0x1413 */ std::numpunct<char>::do_falsename(void);
/* struct 0x1413 */ std::numpunct<char>::do_grouping(void);
char std::ctype<char>::do_narrow(char, char);
void * std::ctype<char>::do_narrow(void *, void *, char, char*);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, /* type 0x12 */);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, /* type 0x22 */);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, double);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, void *);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, /* type 0x13 */);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, /* type 0x23 */);
/* struct 0x2876 */ std::num_put<char,std::ostreambuf_iterator<char,std::char_traits<char> > >::do_put(/* struct 0x2876 */, void *, char, bool);
char std::numpunct<char>::do_thousands_sep(void);
char std::ctype<char>::do_tolower(char);
void * std::ctype<char>::do_tolower(char*, void *);
char std::ctype<char>::do_toupper(char);
void * std::ctype<char>::do_toupper(char*, void *);
/* struct 0x1413 */ std::numpunct<char>::do_truename(void);
char std::ctype<char>::do_widen(char);
void * std::ctype<char>::do_widen(void *, void *, char*);
void * std::basic_ostream<char,std::char_traits<char> >::flush(void);
/* struct 0x1841 */ std::make_error_code(/* type 0x1d9e (LF_ENUM) */);
/* struct 0x1413 */ std::_Iostream_error_category2::message(int32_t);
void * std::_Iostream_error_category2::name(void);
void * std::basic_ostream<char,std::char_traits<char> >::put(char);
char std::basic_ios<char,std::char_traits<char> >::widen(char);
