// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Instance\Instance_Class.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Instance_Class.obj
// 158 function symbol(s) attributed to this object.

/* struct 0xa25a */ std::_Hash<std::_Uset_traits<CInstance *,std::_Uhash_compare<CInstance *,std::hash<CInstance *>,std::equal_to<CInstance *> >,std::allocator<CInstance *>,0> >::emplace<CInstance *>(void *);
void CGCGeneration::CGCGeneration(void);
void CInstance::CInstance(float, float, int32_t, int32_t, bool);
void CScriptRef::CScriptRef(int32_t, int32_t);
void CWeakRef::CWeakRef(void);
void AutoLock::~AutoLock(void);
void CGCGeneration::~CGCGeneration(void);
void CInstance::~CInstance(void);
void YYObjectBase::~YYObjectBase(void);
void CInstance::Activate(void);
bool CInstance::Adapt_Path(void);
void CInstance::Add(void *);
void * YYObjectBase::Add(int32_t, void *, int32_t);
void * YYObjectBase::Add(int32_t, int32_t, int32_t);
void * YYObjectBase::Add(int32_t, double, int32_t);
void * YYObjectBase::Add(int32_t, void *, int32_t);
void * YYObjectBase::Add(int32_t, void *, int32_t);
void * YYObjectBase::Add(int32_t, bool, int32_t);
void * YYObjectBase::Add(void *, void *, int32_t);
void * YYObjectBase::Add(void *, void *, int32_t);
void * YYObjectBase::Add(void *, int32_t, int32_t);
void * YYObjectBase::Add(void *, double, int32_t);
void * YYObjectBase::Add(void *, void *, int32_t);
void * YYObjectBase::Add(void *, /* type 0x13 */, int32_t);
void * YYObjectBase::Add(void *, bool, int32_t);
void AddGlobalObject(void *);
void GCContext::AddRValToDecRef(void *, bool);
void * YYObjectBase::AddRef(int32_t, /* type 0x13 */, int32_t);
void * YYObjectBase::AddRef(void *, /* type 0x13 */, int32_t);
void CInstance::AddTo_Speed(float, float);
void * YYObjectBase::Alloc(uint32_t, int32_t, int32_t, bool);
void YYObjectBase::AllocVars(void);
void CInstance::Assign(void *, bool);
void YYObjectBase::AssignVars(void *, bool);
void CInstance::Assign_Path(int32_t, float, float, float, bool, int32_t);
void CREATE_RVALUE_MUTEX(void);
void CInstance::ChangeObjectIndex(int32_t);
void CBucket<16,1048576,0>::Check(void);
bool CInstance::CheckSkeletonAnimation(void);
void Hash<CInstance>::Clear(/* type 0x6f9f (LF_ENUM) */);
bool CInstance::Collision_Ellipse(float, float, float, float, bool);
bool CInstance::Collision_Instance(void *, bool);
bool CInstance::Collision_Line(float, float, float, float, bool);
bool CInstance::Collision_Point(float, float, bool);
bool CInstance::Collision_Rectangle(float, float, float, float, bool);
bool CInstance::Collision_Skeleton(void *, bool);
void CInstance::Compute_BoundingBox(bool);
void CInstance::Compute_Speed1(void);
void CInstance::Compute_Speed2(void);
void CInstance::CreatePhysicsBody(void *);
void CInstance::DeSerialise(void *, bool);
void CInstance::Deactivate(void);
void CHashMap<YYObjectBase *,YYObjectBase *,4>::DeleteCheckKey(void *);
void DeterminePotentialRoot(void *, void *);
void FINALIZE_Instance_Class(void);
int32_t CHashMap<YYObjectBase *,YYObjectBase *,3>::FindPositionCheckKey(void *);
void * YYObjectBase::FindValue(void *);
bool CBucket<16,1048576,0>::Free(void *);
void CInstance::Free(bool);
void CScriptRef::Free(bool);
void CWeakRef::Free(bool);
void GCArrayThing::Free(bool);
void GCObjectContainer::Free(bool);
void YYObjectBase::Free(void *, bool);
void YYObjectBase::Free(bool);
void YYObjectBase::FreeVars(void *, bool, void *);
void * CInstance::GetCollisionSkeleton(void);
void * YYObjectBase::GetDispose(void);
float CInstance::GetImageIndex(void);
float CInstance::GetImageNumber(void);
void * GetRValue(void);
int32_t CBucket<16,1048576,0>::GetSize(void);
bool YYObjectBase::HasValue(void *);
void CHashMap<YYObjectBase *,YYObjectBase *,3>::Init(void);
void CHashMap<YYObjectBase *,YYObjectBase *,4>::Init(void);
void StructVarsMap::Init(void);
void CHashMap<YYObjectBase *,YYObjectBase *,3>::Insert(void *, void *);
void CHashMap<YYObjectBase *,YYObjectBase *,4>::Insert(void *, void *);
void StructVarsMap::Insert(int32_t, void *);
void * YYObjectBase::InternalGetYYVar(int32_t);
void * YYObjectBase::InternalGetYYVarRef(int32_t);
void * YYObjectBase::InternalGetYYVarRefL(int32_t);
void JS_SharedPrototypeObjectConstructor(void *, void *, void *, void *, void *, int32_t);
bool CInstance::Mark4GC(/* type 0x675 */, int32_t);
bool GCArrayThing::Mark4GC(/* type 0x675 */, int32_t);
bool GCObjectContainer::Mark4GC(/* type 0x675 */, int32_t);
bool YYObjectBase::Mark4GC(/* type 0x675 */, int32_t);
bool YYObjectBase::MarkOnlyChildren4GC(/* type 0x675 */, int32_t);
bool YYObjectBase::MarkThisOnly4GC(/* type 0x675 */, int32_t);
void * CInstance::MaskCollisionSkeleton(void);
void CInstance::Maybe_Compute_BoundingBox(bool);
void CInstance::PreFree(void);
void CWeakRef::PreFree(void);
void YYObjectBase::PreFree(void);
void CInstance::RebuildPhysicsBody(void *);
void CInstance::Remove(void *);
void RemoveGlobalObject(void *);
void GCObjectContainer::RemoveObject(void *);
void CInstance::Serialise(void *);
void CInstance::SetDirection(float);
void CInstance::SetImageAngle(float);
void CInstance::SetImageScaleX(float);
void CInstance::SetImageScaleY(float);
void CInstance::SetObjectIndex(int32_t, bool);
void CInstance::SetPathIndex(int32_t);
void CInstance::SetPathPosition(float);
void CInstance::SetPathPositionPrevious(float);
void CInstance::SetPathXStart(float);
void CInstance::SetPathYStart(float);
void CInstance::SetPosition(float, float);
void CWeakRef::SetReference(void *);
void CInstance::SetSpriteIndex(int32_t);
void CInstance::SetTimelinePrevPosition(float);
void * CInstance::SkeletonAnimation(void);
void CInstance::ThreadFree(bool, void *);
void CScriptRef::ThreadFree(bool, void *);
void CWeakRef::ThreadFree(bool, void *);
void GCArrayThing::ThreadFree(bool, void *);
void GCObjectContainer::ThreadFree(bool, void *);
void YYObjectBase::ThreadFree(bool, void *);
bool CInstance::UseSkeletonCollision(void);
void * WeakRef_prop_GetRef(void *, void *, void *, int32_t, void *);
void getPoints(void *, void *);
bool sa_checkCollision(void *, void *);
bool sa_checkCollisionEllipse(void *, void *, float, float);
bool sa_checkCollisionLine(void *, void *);
bool sa_checkCollisionPoint(void *, void *);
