// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Code\VM_Exec.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\VM_Exec.obj
// 154 function symbol(s) attributed to this object.

void Buffer_Standard::Buffer_Standard(/* type 0x603 */, int32_t, /* type 0x8229 (LF_ENUM) */, int32_t, bool);
void TErrStreamConsole::TErrStreamConsole(void);
void YYGMLException::YYGMLException(void *);
void YYGMLException::YYGMLException(void *, void *, void *, void *, void *, int32_t, void *, int32_t);
void AddGCRefObj(void *, bool, void *, bool);
/* type 0x603 */ CBucket<32768,1048576,0>::Alloc(bool);
void CBucket<32768,1048576,0>::Check(void);
/* type 0x620 */ CheckForStackResize(/* type 0x620 */, void *, int32_t);
void VM::ClearBreakpointsFromMemory(void);
bool ConvertStringToBool(void *, bool, /* type 0x630 */);
/* type 0x620 */ DoAdd(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoAnd(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoBranch(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoBranchFalse(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoBranchTrue(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoBreak(uint32_t, unsigned char, /* type 0x620 */, void *, void *, bool);
/* type 0x620 */ DoCall(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoCallGML(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoCallLibrary(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoCallScript(void *, int32_t, /* type 0x620 */, void *, void *, void *);
/* type 0x620 */ DoConv(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoConvIntToVariable(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoDiv(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoDup(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoExit(uint32_t, /* type 0x620 */, void *, void *);
void DoFullGC(void);
void DoGenerationalGC(int32_t);
/* type 0x620 */ DoMod(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoMul(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoNeg(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoNot(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoOr(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPop(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPopEnv(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPopLocalVariable(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPopNull(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPush(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPushBuiltin(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPushEnv(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPushGlobal(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPushImmediate(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoPushLocal(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoRem(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoRet(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoSet(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoShl(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoShr(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoSub(uint32_t, /* type 0x620 */, void *, void *);
/* type 0x620 */ DoXor(uint32_t, /* type 0x620 */, void *, void *);
void VM::Exec(void *, void *, void *, void *, void *, int32_t, void *, int32_t, void *);
void VM::ExecDebug(void *, void *, bool);
void VM::ExecRelease(void *, void *);
void F_VMGetCallStack(void *, void *, void *, int32_t, void *);
bool CBucket<32768,1048576,0>::Free(void *);
void FreeAllObjects(void);
/* type 0x603 */ GCThreadFunc(void *);
void VM::GetAllInstanceIDs(void *, bool);
void VM::GetDSMap(void *, int32_t, int32_t);
void * YYGMLException::GetExceptionObject(void);
void VM::GetGlobalVariables(void *, bool);
void VM::GetInstanceVariables(void *, void *, bool);
void VM::GetLocalVariables(void *, void *, bool, int32_t);
void VM::GetObjectBaseVariables(void *, void *, bool);
void VM::GetRuntimeState(void *, int32_t);
int32_t CBucket<32768,1048576,0>::GetSize(void);
void VM::GetStructureCounts(void *);
void HandleInstance(void *);
bool HasGMLExceptionHandler(void);
void CHashMap<int,CInstance *,3>::Init(void);
void CHashMap<int,CInstance *,3>::Insert(int32_t, void *);
bool InstanceHandled(void *);
void MarkAndSweepGen(int32_t, int32_t, bool);
void TErrStreamConsole::Output(void *, /* type 0x0 */);
/* type 0x620 */ PerformReturn(/* type 0x620 */, void *);
bool VM::PokeDSList(int32_t, int32_t, void *);
bool VM::PokeDSMap(int32_t, int32_t, void *);
bool VM::PokeDSPriority(int32_t, int32_t, void *);
bool VM::PokeDSQueue(int32_t, int32_t, void *);
bool VM::PokeDSStack(int32_t, int32_t, void *);
void ProcessObjectDisposeList(void);
void PushContextStack(void *);
bool RValue_IsCallable(void *);
void ResetGC(void);
void ResetObjectGCList(void);
void VMError(void *, void *, /* type 0x0 */);
void VM::WriteBreakpointsToMemory(void);
void VM::WriteCallStack(void *, void *, bool);
int32_t VM::WriteDSSizeCount(void *, int32_t, void *);
void VM::WriteInstanceBuiltInVariables(void *, void *);
void VM::WriteRValueToBuffer(void *, void *);
void * YYAllocLocalStackNew(int32_t);
void YYCatchGMLException(void *);
void YYCreateString(void *, void *);
void YYCreateString(void *, void *);
void YYError(void *, /* type 0x0 */);
void * YYGML_CallMethod(void *, void *, void *, int32_t, void *, void *);
void * YYGML_GetStaticObject(int32_t);
void YYSetScriptRef(void *);
void YYSetString(void *, void *);
void * YYStrDup(void *);
void YYWarning(void *, /* type 0x0 */);
void YYprintf(void *, /* type 0x0 */);
bool tryParseBool(void *, void *);
bool tryParseDouble(void *, void *);
bool tryParseInt32(void *, void *);
bool tryParseInt64(void *, void *);
void * vmGetCallStack(void);
