// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Graphics\Graphics_Support.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Graphics_Support.obj
// 94 function symbol(s) attributed to this object.

void CCamera::CCamera(void);
void Camera_GCProxy::Camera_GCProxy(void *);
void CCamera::~CCamera(void);
void CCameraManager::AddCameraToList(void *, int32_t);
void CCamera::ApplyMatrices(void);
void CCamera::Build2DView(float, float);
void CCamera::Build3DView(float, float);
void CCameraManager::BuildRoomCameraList(void);
void CCamera::BuildView(void);
void CCamera::CameraUpdate(void);
void CCameraManager::Clean(void);
void CCamera::CopyFrom(void *);
void * CCameraManager::CreateCamera(void);
void CCamera::DeSerialize(void *);
void DeSerializeMatrix(void *, void *);
void CCameraManager::DestroyCamera(int32_t);
bool CCamera::ExecuteScript(void *);
void F_CameraApply(void *, void *, void *, int32_t, void *);
void F_CameraCopyTransforms(void *, void *, void *, int32_t, void *);
void F_CameraCreate(void *, void *, void *, int32_t, void *);
void F_CameraCreateView(void *, void *, void *, int32_t, void *);
void F_CameraDestroy(void *, void *, void *, int32_t, void *);
void F_CameraGetActive(void *, void *, void *, int32_t, void *);
void F_CameraGetBeginScript(void *, void *, void *, int32_t, void *);
void F_CameraGetDefault(void *, void *, void *, int32_t, void *);
void F_CameraGetEndScript(void *, void *, void *, int32_t, void *);
void F_CameraGetProjMat(void *, void *, void *, int32_t, void *);
void F_CameraGetUpdateScript(void *, void *, void *, int32_t, void *);
void F_CameraGetViewAngle(void *, void *, void *, int32_t, void *);
void F_CameraGetViewBorderX(void *, void *, void *, int32_t, void *);
void F_CameraGetViewBorderY(void *, void *, void *, int32_t, void *);
void F_CameraGetViewHeight(void *, void *, void *, int32_t, void *);
void F_CameraGetViewMat(void *, void *, void *, int32_t, void *);
void F_CameraGetViewSpeedX(void *, void *, void *, int32_t, void *);
void F_CameraGetViewSpeedY(void *, void *, void *, int32_t, void *);
void F_CameraGetViewTarget(void *, void *, void *, int32_t, void *);
void F_CameraGetViewWidth(void *, void *, void *, int32_t, void *);
void F_CameraGetViewX(void *, void *, void *, int32_t, void *);
void F_CameraGetViewY(void *, void *, void *, int32_t, void *);
void F_CameraSetBeginScript(void *, void *, void *, int32_t, void *);
void F_CameraSetDefault(void *, void *, void *, int32_t, void *);
void F_CameraSetEndScript(void *, void *, void *, int32_t, void *);
void F_CameraSetProjMat(void *, void *, void *, int32_t, void *);
void F_CameraSetUpdateScript(void *, void *, void *, int32_t, void *);
void F_CameraSetViewAngle(void *, void *, void *, int32_t, void *);
void F_CameraSetViewBorder(void *, void *, void *, int32_t, void *);
void F_CameraSetViewMat(void *, void *, void *, int32_t, void *);
void F_CameraSetViewPos(void *, void *, void *, int32_t, void *);
void F_CameraSetViewSize(void *, void *, void *, int32_t, void *);
void F_CameraSetViewSpeed(void *, void *, void *, int32_t, void *);
void F_CameraSetViewTarget(void *, void *, void *, int32_t, void *);
void F_ViewGetCamera(void *, void *, void *, int32_t, void *);
void F_ViewGetHport(void *, void *, void *, int32_t, void *);
void F_ViewGetSurfaceId(void *, void *, void *, int32_t, void *);
void F_ViewGetVisible(void *, void *, void *, int32_t, void *);
void F_ViewGetWport(void *, void *, void *, int32_t, void *);
void F_ViewGetXport(void *, void *, void *, int32_t, void *);
void F_ViewGetYport(void *, void *, void *, int32_t, void *);
void F_ViewSetCamera(void *, void *, void *, int32_t, void *);
void F_ViewSetHport(void *, void *, void *, int32_t, void *);
void F_ViewSetSurfaceId(void *, void *, void *, int32_t, void *);
void F_ViewSetVisible(void *, void *, void *, int32_t, void *);
void F_ViewSetWport(void *, void *, void *, int32_t, void *);
void F_ViewSetXport(void *, void *, void *, int32_t, void *);
void F_ViewSetYport(void *, void *, void *, int32_t, void *);
int32_t CCameraManager::FindCameraInList(int32_t);
void Camera_GCProxy::Free(bool);
uint32_t GR_Color_Merge(uint32_t, uint32_t, float);
void * CCameraManager::GetCamera(int32_t);
bool Camera_GCProxy::Mark4GC(/* type 0x675 */, int32_t);
/* struct 0x6ec7 */ RotateRectAroundOrigin(/* struct 0x6ec7 */, float, float, float);
void CCamera::Serialize(void *);
void SerializeMatrix(void *, void *);
void CCamera::SetBeginScript(void *);
void CCamera::SetEndScript(void *);
void CCamera::SetProjMat(void *);
void CCamera::SetUpdateScript(void *);
void CCamera::SetViewMat(void *);
void CCameraManager::SetupGMLFunctions(void);
void Camera_GCProxy::ThreadFree(bool, void *);
void CCamera::Update2D(void);
void ValidateValidScriptValue(void *, void *);
bool WritePNG32(/* type 0x670 */, /* type 0x603 */, int32_t, int32_t, int32_t);
void pngFlushFn(void *);
void pngWriteBufferFn(void *, /* type 0x620 */, /* type 0x23 */);
void pngWriteFn(void *, /* type 0x620 */, /* type 0x23 */);
