// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\multiplayer\rollback_input.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\rollback_input.obj
// 123 function symbol(s) attributed to this object.

void std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::_Assign_range<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *>(void *, void *, /* struct 0x19d2 */);
void * std::_Copy_unchecked<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *>(void *, void *, void *);
void * std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::_Emplace_reallocate<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> >(void *, void *);
/* struct 0x1b34b */ std::_Hash<std::_Umap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,float,std::_Uhash_compare<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> >,0> >::_Find_last<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >(void *, void);
void std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *>::_Free_non_head<std::allocator<std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *> > >(void *, void *);
void * std::_Insertion_sort_unchecked<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,bool (__cdecl*)(std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>)>(void *, void *, void *);
void std::_Med3_unchecked<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,bool (__cdecl*)(std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>)>(void *, void *, void *, void *);
/* struct 0x16961 */ std::_Partition_by_median_guess_unchecked<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,bool (__cdecl*)(std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>)>(void *, void *, void *);
void std::_Pop_heap_hole_by_index<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,bool (__cdecl*)(std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>)>(void *, /* type 0x13 */, /* type 0x13 */, void *, void *);
void std::vector<Rollback::InputBuffer,std::allocator<Rollback::InputBuffer> >::_Resize_reallocate<std::_Value_init_tag>(void, void *);
void std::_Sort_unchecked<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> *,bool (__cdecl*)(std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>)>(void *, void *, /* type 0x13 */, void *);
/* struct 0x16cbd */ std::_Hash<std::_Umap_traits<int,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >,std::_Uhash_compare<int,std::hash<int>,std::equal_to<int> >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > >,0> >::_Try_emplace<int const &>(void *);
/* struct 0x16c28 */ std::_Hash<std::_Umap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,float,std::_Uhash_compare<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> >,0> >::_Try_emplace<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &>(void *);
void std::fill<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > > > *,std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > > > >(void *, void *, void *);
void std::fill<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > > > *,std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > > > >(void *, void *, void *);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,void *> > >(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *> > >(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > > > > >::~_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > > > > >(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > > > > >::~_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > > > > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,void *> > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,void *> > >(void);
void std::_Uninitialized_backout_al<std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::~_Uninitialized_backout_al<std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >(void);
void std::list<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > >::~list<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > >(void);
void std::list<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > >::~list<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > >(void);
void std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>::~pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>(void);
void std::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,float,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > >::~unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,float,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > >(void);
void std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::~vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >(void);
void std::vector<Rollback::InputBuffer,std::allocator<Rollback::InputBuffer> >::~vector<Rollback::InputBuffer,std::allocator<Rollback::InputBuffer> >(void);
void Rollback::InputBuffer::~InputBuffer(void);
void * Rollback::CreateInputStruct(int32_t, bool);
int32_t Rollback::GetInputBits(int32_t);
void Rollback::InitInputBuffers(int32_t);
void Rollback::MakeDefaultInputDefinition(void);
void * Rollback::PollInput(void);
void Rollback::SetIfZeroOrUnset(void *, void *, /* struct 0x1413 */, float);
void Rollback::SetInputDefinition(void *);
void Rollback::SetMockInputDefinition(int32_t, void *);
void Rollback::SortInputDefinitions(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > > > > > >::_Assign_grow(void, void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> > > > > >::_Assign_grow(void, void);
void std::_Hash<std::_Umap_traits<int,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >,std::_Uhash_compare<int,std::hash<int>,std::equal_to<int> >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > >,0> >::_Forced_rehash(/* type 0x23 */);
void std::_Hash<std::_Umap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,float,std::_Uhash_compare<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,float> >,0> >::_Forced_rehash(/* type 0x23 */);
void * std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::_Umove(void *, void *, void *);
void * std::_Hash<std::_Umap_traits<int,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >,std::_Uhash_compare<int,std::hash<int>,std::equal_to<int> >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > >,0> >::_Unchecked_erase(void *, void *);
void std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::_Xlength(void);
void std::vector<Rollback::InputBuffer,std::allocator<Rollback::InputBuffer> >::_Xlength(void);
void * std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> >::allocate(void);
void std::_Hash<std::_Umap_traits<int,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >,std::_Uhash_compare<int,std::hash<int>,std::equal_to<int> >,std::allocator<std::pair<int const ,std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > > > >,0> >::clear(void);
bool Rollback::compareInput(/* struct 0xe971 */, /* struct 0xe971 */);
void std::vector<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int> > >::push_back(void *);
void std::vector<Rollback::InputBuffer,std::allocator<Rollback::InputBuffer> >::resize(void);
