set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-cl")
set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-cl")

set(CMAKE_LINKER "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-link")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-lib")
set(CMAKE_RC_COMPILER "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-rc")
set(CMAKE_MT "${CMAKE_CURRENT_LIST_DIR}/wine-bin/wine-mt")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)