// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Sound\Audio_Effect_Struct.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Audio_Effect_Struct.obj
// 157 function symbol(s) attributed to this object.

void * std::vector<AudioEffectStruct *,std::allocator<AudioEffectStruct *> >::_Emplace_reallocate<AudioEffectStruct *>(void *, void *);
void std::vector<double,std::allocator<double> >::_Resize_reallocate<std::_Value_init_tag>(void, void *);
void std::vector<int,std::allocator<int> >::vector<int,std::allocator<int> >(void);
void AudioEffectStruct::AudioEffectStruct(/* type 0xb2b1 (LF_ENUM) */);
void EQEffectStruct::EQEffectStruct(void *);
void std::vector<int,std::allocator<int> >::~vector<int,std::allocator<int> >(void);
void AudioEffectStruct::~AudioEffectStruct(void);
void * AudioEffect_prop_GetBypass(void *, void *, void *, int32_t, void *);
void * AudioEffect_prop_GetType(void *, void *, void *, int32_t, void *);
void * AudioEffect_prop_SetBypass(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_GetFactor(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_GetGain(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_GetMix(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_GetResolution(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_SetFactor(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_SetGain(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_SetMix(void *, void *, void *, int32_t, void *);
void * Bitcrusher_prop_SetResolution(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetAttack(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetInputGain(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetOutputGain(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetRatio(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetRelease(void *, void *, void *, int32_t, void *);
void * Compressor_prop_GetThreshold(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetAttack(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetInputGain(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetOutputGain(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetRatio(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetRelease(void *, void *, void *, int32_t, void *);
void * Compressor_prop_SetThreshold(void *, void *, void *, int32_t, void *);
void * AudioEffectStruct::Create(/* type 0xb2b1 (LF_ENUM) */, void *);
int32_t AudioEffectStruct::CreateInstance(void);
int32_t EQEffectStruct::CreateInstance(void);
void * Delay_prop_GetFeedback(void *, void *, void *, int32_t, void *);
void * Delay_prop_GetMix(void *, void *, void *, int32_t, void *);
void * Delay_prop_GetTime(void *, void *, void *, int32_t, void *);
void * Delay_prop_SetFeedback(void *, void *, void *, int32_t, void *);
void * Delay_prop_SetMix(void *, void *, void *, int32_t, void *);
void * Delay_prop_SetTime(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetEQ1(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetEQ2(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetEQ3(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetEQ4(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetHicut(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetHishelf(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetLocut(void *, void *, void *, int32_t, void *);
void * EQ_prop_GetLoshelf(void *, void *, void *, int32_t, void *);
void AudioEffectStruct::Free(bool);
void * Gain_prop_GetGain(void *, void *, void *, int32_t, void *);
void * Gain_prop_SetGain(void *, void *, void *, int32_t, void *);
void * BitcrusherEffectStruct::GetParamDescriptors(void);
void * CompressorEffectStruct::GetParamDescriptors(void);
void * DelayEffectStruct::GetParamDescriptors(void);
void * EQEffectStruct::GetParamDescriptors(void);
void * GainEffectStruct::GetParamDescriptors(void);
void * HPF2EffectStruct::GetParamDescriptors(void);
void * HiShelfEffectStruct::GetParamDescriptors(void);
void * LPF2EffectStruct::GetParamDescriptors(void);
void * LoShelfEffectStruct::GetParamDescriptors(void);
void * PeakEQEffectStruct::GetParamDescriptors(void);
void * Reverb1EffectStruct::GetParamDescriptors(void);
void * TremoloEffectStruct::GetParamDescriptors(void);
float AudioEffectStruct::GetParamOrDefault(void *, void *, void);
void * HPF2_prop_GetCutoff(void *, void *, void *, int32_t, void *);
void * HPF2_prop_GetQ(void *, void *, void *, int32_t, void *);
void * HPF2_prop_SetCutoff(void *, void *, void *, int32_t, void *);
void * HPF2_prop_SetQ(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_GetFreq(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_GetGain(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_GetQ(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_SetFreq(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_SetGain(void *, void *, void *, int32_t, void *);
void * HiShelf_prop_SetQ(void *, void *, void *, int32_t, void *);
void * LPF2_prop_GetCutoff(void *, void *, void *, int32_t, void *);
void * LPF2_prop_GetQ(void *, void *, void *, int32_t, void *);
void * LPF2_prop_SetCutoff(void *, void *, void *, int32_t, void *);
void * LPF2_prop_SetQ(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_GetFreq(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_GetGain(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_GetQ(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_SetFreq(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_SetGain(void *, void *, void *, int32_t, void *);
void * LoShelf_prop_SetQ(void *, void *, void *, int32_t, void *);
bool AudioEffectStruct::Mark4GC(/* type 0x675 */, int32_t);
bool EQEffectStruct::Mark4GC(/* type 0x675 */, int32_t);
void * PeakEQ_prop_GetFreq(void *, void *, void *, int32_t, void *);
void * PeakEQ_prop_GetGain(void *, void *, void *, int32_t, void *);
void * PeakEQ_prop_GetQ(void *, void *, void *, int32_t, void *);
void * PeakEQ_prop_SetFreq(void *, void *, void *, int32_t, void *);
void * PeakEQ_prop_SetGain(void *, void *, void *, int32_t, void *);
void * PeakEQ_prop_SetQ(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_GetDamp(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_GetMix(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_GetSize(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_SetDamp(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_SetMix(void *, void *, void *, int32_t, void *);
void * Reverb1_prop_SetSize(void *, void *, void *, int32_t, void *);
void AudioEffectStruct::SetParam(void, void);
void HPF2EffectStruct::SetParam(void, void);
void HiShelfEffectStruct::SetParam(void, void);
void LPF2EffectStruct::SetParam(void, void);
void LoShelfEffectStruct::SetParam(void, void);
void PeakEQEffectStruct::SetParam(void, void);
void AudioEffectStruct::ThreadFree(bool, void *);
void * Tremolo_prop_GetIntensity(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_GetOffset(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_GetRate(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_GetShape(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_SetIntensity(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_SetOffset(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_SetRate(void *, void *, void *, int32_t, void *);
void * Tremolo_prop_SetShape(void *, void *, void *, int32_t, void *);
void std::vector<int,std::allocator<int> >::_Tidy(void);
void std::vector<AudioEffectStruct *,std::allocator<AudioEffectStruct *> >::_Xlength(void);
void std::vector<double,std::allocator<double> >::resize(void);
