// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Math.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Math.obj
// 317 function symbol(s) attributed to this object.

void * std::vector<RValue,std::allocator<RValue> >::_Emplace_reallocate<RValue const &>(void *, void *);
/* type 0x623 */ std::vector<unsigned __int64,std::allocator<unsigned __int64> >::_Emplace_reallocate<unsigned __int64>(void *, void *);
void * std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Reallocate_grow_by<<lambda_319d5e083f45f90dcdce5dce53cbb275>,char>(void, /* struct 0x1a560 */, char);
void * std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Reallocate_grow_by<<lambda_9013ee9e23efe4882b67eff5b0ecf103> >(void, /* struct 0x1a57e */);
void std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >::_Resize_reallocate<std::_Value_init_tag>(void, void *);
/* struct 0xfc72 */ std::_Hash<std::_Umap_traits<__int64,int,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<std::pair<__int64 const ,int> >,0> >::_Try_emplace<__int64 const &>(void *);
/* struct 0xff2a */ std::_Hash<std::_Uset_traits<__int64,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<__int64>,0> >::emplace<__int64 const &>(void *);
void std::fill<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<__int64> >,std::_Iterator_base0> *,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<__int64> >,std::_Iterator_base0> >(void *, void *, void *);
void std::fill<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<__int64 const ,int> > > > *,std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<__int64 const ,int> > > > >(void *, void *, void *);
void _RefThing<char const *>::_RefThing<char const *>(int32_t);
void std::unordered_set<__int64,std::hash<__int64>,std::equal_to<__int64>,std::allocator<__int64> >::unordered_set<__int64,std::hash<__int64>,std::equal_to<__int64>,std::allocator<__int64> >(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<__int64 const ,int>,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<__int64 const ,int>,void *> > >(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<__int64,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<__int64,void *> > >(void);
void std::_Hash<std::_Umap_traits<__int64,int,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<std::pair<__int64 const ,int> >,0> >::~_Hash<std::_Umap_traits<__int64,int,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<std::pair<__int64 const ,int> >,0> >(void);
void std::_Hash<std::_Uset_traits<__int64,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<__int64>,0> >::~_Hash<std::_Uset_traits<__int64,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<__int64>,0> >(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<__int64> >,std::_Iterator_base0> > >::~_Hash_vec<std::allocator<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<__int64> >,std::_Iterator_base0> > >(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<__int64 const ,int> > > > > >::~_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<__int64 const ,int> > > > > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<__int64 const ,int>,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<__int64 const ,int>,void *> > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<__int64,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<__int64,void *> > >(void);
void std::deque<ArraySortData,std::allocator<ArraySortData> >::~deque<ArraySortData,std::allocator<ArraySortData> >(void);
void std::list<std::pair<__int64 const ,int>,std::allocator<std::pair<__int64 const ,int> > >::~list<std::pair<__int64 const ,int>,std::allocator<std::pair<__int64 const ,int> > >(void);
void std::list<__int64,std::allocator<__int64> >::~list<__int64,std::allocator<__int64> >(void);
void std::unordered_map<__int64,int,std::hash<__int64>,std::equal_to<__int64>,std::allocator<std::pair<__int64 const ,int> > >::~unordered_map<__int64,int,std::hash<__int64>,std::equal_to<__int64>,std::allocator<std::pair<__int64 const ,int> > >(void);
void std::unordered_set<__int64,std::hash<__int64>,std::equal_to<__int64>,std::allocator<__int64> >::~unordered_set<__int64,std::hash<__int64>,std::equal_to<__int64>,std::allocator<__int64> >(void);
void std::vector<RValue,std::allocator<RValue> >::~vector<RValue,std::allocator<RValue> >(void);
void std::vector<unsigned __int64,std::allocator<unsigned __int64> >::~vector<unsigned __int64,std::allocator<unsigned __int64> >(void);
int32_t ArrayEquals(void *, void *);
void DoString(void *, int32_t, void *, bool);
int32_t FUNC_double_sort(void *, void *);
void F_Abs(void *, void *, void *, int32_t, void *);
void F_AnsiChar(void *, void *, void *, int32_t, void *);
void F_ArcCos(void *, void *, void *, int32_t, void *);
void F_ArcSin(void *, void *, void *, int32_t, void *);
void F_ArcTan2(void *, void *, void *, int32_t, void *);
void F_ArcTan(void *, void *, void *, int32_t, void *);
void F_ArrayAll(void *, void *, void *, int32_t, void *);
void F_ArrayAny(void *, void *, void *, int32_t, void *);
void F_ArrayConcat(void *, void *, void *, int32_t, void *);
void F_ArrayContains(void *, void *, void *, int32_t, void *);
void F_ArrayContainsExt(void *, void *, void *, int32_t, void *);
void F_ArrayCopy(void *, void *, void *, int32_t, void *);
void F_ArrayCopyWhile(void *, void *, void *, int32_t, void *);
void F_ArrayCreate(void *, void *, void *, int32_t, void *);
void F_ArrayCreateExt(void *, void *, void *, int32_t, void *);
void F_ArrayDelete(void *, void *, void *, int32_t, void *);
void F_ArrayEquals(void *, void *, void *, int32_t, void *);
void F_ArrayFilter(void *, void *, void *, int32_t, void *);
void F_ArrayFilterExt(void *, void *, void *, int32_t, void *);
void F_ArrayFindIndex(void *, void *, void *, int32_t, void *);
void F_ArrayFirst(void *, void *, void *, int32_t, void *);
void F_ArrayForEach(void *, void *, void *, int32_t, void *);
void F_ArrayGet2D(void *, void *, void *, int32_t, void *);
void F_ArrayGet(void *, void *, void *, int32_t, void *);
void F_ArrayGetIndex(void *, void *, void *, int32_t, void *);
void F_ArrayGetSanitised(void *, void *, void *, int32_t, void *);
void F_ArrayHeight2D(void *, void *, void *, int32_t, void *);
void F_ArrayInsert(void *, void *, void *, int32_t, void *);
void F_ArrayIntersection(void *, void *, void *, int32_t, void *);
void F_ArrayLast(void *, void *, void *, int32_t, void *);
void F_ArrayLength1D(void *, void *, void *, int32_t, void *);
void F_ArrayLength2D(void *, void *, void *, int32_t, void *);
void F_ArrayMap(void *, void *, void *, int32_t, void *);
void F_ArrayMapExt(void *, void *, void *, int32_t, void *);
void F_ArrayPop(void *, void *, void *, int32_t, void *);
void F_ArrayPush(void *, void *, void *, int32_t, void *);
void F_ArrayReduce(void *, void *, void *, int32_t, void *);
void F_ArrayResize(void *, void *, void *, int32_t, void *);
void F_ArrayReverse(void *, void *, void *, int32_t, void *);
void F_ArrayReverseExt(void *, void *, void *, int32_t, void *);
void F_ArraySet2D(void *, void *, void *, int32_t, void *);
void F_ArraySet2DPost(void *, void *, void *, int32_t, void *);
void F_ArraySet2DPre(void *, void *, void *, int32_t, void *);
void F_ArraySet(void *, void *, void *, int32_t, void *);
void F_ArraySetOwner(void *, void *, void *, int32_t, void *);
void F_ArraySetPost(void *, void *, void *, int32_t, void *);
void F_ArraySetPre(void *, void *, void *, int32_t, void *);
void F_ArrayShift(void *, void *, void *, int32_t, void *);
void F_ArrayShuffle(void *, void *, void *, int32_t, void *);
void F_ArrayShuffleExt(void *, void *, void *, int32_t, void *);
void F_ArraySort(void *, void *, void *, int32_t, void *);
void F_ArrayUnion(void *, void *, void *, int32_t, void *);
void F_ArrayUnique(void *, void *, void *, int32_t, void *);
void F_ArrayUniqueExt(void *, void *, void *, int32_t, void *);
void F_Bool(void *, void *, void *, int32_t, void *);
void F_Ceil(void *, void *, void *, int32_t, void *);
void F_Choose(void *, void *, void *, int32_t, void *);
void F_Chr(void *, void *, void *, int32_t, void *);
void F_Clamp(void *, void *, void *, int32_t, void *);
void F_Cos(void *, void *, void *, int32_t, void *);
void F_DArcCos(void *, void *, void *, int32_t, void *);
void F_DArcSin(void *, void *, void *, int32_t, void *);
void F_DArcTan2(void *, void *, void *, int32_t, void *);
void F_DArcTan(void *, void *, void *, int32_t, void *);
void F_DCos(void *, void *, void *, int32_t, void *);
void F_DSin(void *, void *, void *, int32_t, void *);
void F_DTan(void *, void *, void *, int32_t, void *);
void F_DegToRad(void *, void *, void *, int32_t, void *);
void F_DotProduct(void *, void *, void *, int32_t, void *);
void F_DotProduct_3D(void *, void *, void *, int32_t, void *);
void F_DotProduct_3D_Normalised(void *, void *, void *, int32_t, void *);
void F_DotProduct_Normalised(void *, void *, void *, int32_t, void *);
void F_Exp(void *, void *, void *, int32_t, void *);
void F_Floor(void *, void *, void *, int32_t, void *);
void F_Frac(void *, void *, void *, int32_t, void *);
void F_Handle(void *, void *, void *, int32_t, void *);
void F_IRandom(void *, void *, void *, int32_t, void *);
void F_IRandomRange(void *, void *, void *, int32_t, void *);
void F_Instanceof(void *, void *, void *, int32_t, void *);
void F_Int64(void *, void *, void *, int32_t, void *);
void F_IsArray(void *, void *, void *, int32_t, void *);
void F_IsBool(void *, void *, void *, int32_t, void *);
void F_IsCallable(void *, void *, void *, int32_t, void *);
void F_IsHandle(void *, void *, void *, int32_t, void *);
void F_IsInf(void *, void *, void *, int32_t, void *);
void F_IsInstanceof(void *, void *, void *, int32_t, void *);
void F_IsInt32(void *, void *, void *, int32_t, void *);
void F_IsInt64(void *, void *, void *, int32_t, void *);
void F_IsMethod(void *, void *, void *, int32_t, void *);
void F_IsNaN(void *, void *, void *, int32_t, void *);
void F_IsNumeric(void *, void *, void *, int32_t, void *);
void F_IsPtr(void *, void *, void *, int32_t, void *);
void F_IsReal(void *, void *, void *, int32_t, void *);
void F_IsString(void *, void *, void *, int32_t, void *);
void F_IsStruct(void *, void *, void *, int32_t, void *);
void F_IsUndefined(void *, void *, void *, int32_t, void *);
void F_LengthDirX(void *, void *, void *, int32_t, void *);
void F_LengthDirY(void *, void *, void *, int32_t, void *);
void F_Lerp(void *, void *, void *, int32_t, void *);
void F_Ln(void *, void *, void *, int32_t, void *);
void F_Log10(void *, void *, void *, int32_t, void *);
void F_Log2(void *, void *, void *, int32_t, void *);
void F_Logn(void *, void *, void *, int32_t, void *);
void F_MathAngleDifference(void *, void *, void *, int32_t, void *);
void F_MathGetEpsilon(void *, void *, void *, int32_t, void *);
void F_MathSetEpsilon(void *, void *, void *, int32_t, void *);
void F_Max(void *, void *, void *, int32_t, void *);
void F_Mean(void *, void *, void *, int32_t, void *);
void F_Median(void *, void *, void *, int32_t, void *);
void F_Method(void *, void *, void *, int32_t, void *);
void F_MethodCall(void *, void *, void *, int32_t, void *);
void F_MethodGetIndex(void *, void *, void *, int32_t, void *);
void F_MethodGetObject(void *, void *, void *, int32_t, void *);
void F_Min(void *, void *, void *, int32_t, void *);
void F_Ord(void *, void *, void *, int32_t, void *);
void F_PointDirection(void *, void *, void *, int32_t, void *);
void F_PointDistance(void *, void *, void *, int32_t, void *);
void F_PointDistance_3D(void *, void *, void *, int32_t, void *);
void F_Power(void *, void *, void *, int32_t, void *);
void F_Ptr(void *, void *, void *, int32_t, void *);
void F_RadToDeg(void *, void *, void *, int32_t, void *);
void F_Random(void *, void *, void *, int32_t, void *);
void F_RandomGetSeed(void *, void *, void *, int32_t, void *);
void F_RandomRange(void *, void *, void *, int32_t, void *);
void F_RandomSetSeed(void *, void *, void *, int32_t, void *);
void F_Randomize(void *, void *, void *, int32_t, void *);
void F_Real(void *, void *, void *, int32_t, void *);
void F_Round(void *, void *, void *, int32_t, void *);
void F_Sign(void *, void *, void *, int32_t, void *);
void F_Sin(void *, void *, void *, int32_t, void *);
void F_Sqr(void *, void *, void *, int32_t, void *);
void F_Sqrt(void *, void *, void *, int32_t, void *);
void F_String(void *, void *, void *, int32_t, void *);
void F_StringByteAt(void *, void *, void *, int32_t, void *);
void F_StringByteLength(void *, void *, void *, int32_t, void *);
void F_StringCharAt(void *, void *, void *, int32_t, void *);
void F_StringConcat(void *, void *, void *, int32_t, void *);
void F_StringConcatExt(void *, void *, void *, int32_t, void *);
void F_StringCopy(void *, void *, void *, int32_t, void *);
void F_StringCount(void *, void *, void *, int32_t, void *);
void F_StringDelete(void *, void *, void *, int32_t, void *);
void F_StringDigits(void *, void *, void *, int32_t, void *);
void F_StringEndsWith(void *, void *, void *, int32_t, void *);
void F_StringExt(void *, void *, void *, int32_t, void *);
void F_StringForEach(void *, void *, void *, int32_t, void *);
void F_StringFormat(void *, void *, void *, int32_t, void *);
void F_StringHashToNewline(void *, void *, void *, int32_t, void *);
void F_StringInsert(void *, void *, void *, int32_t, void *);
void F_StringInternal(void *, void *, void *, int32_t, void *);
void F_StringJoin(void *, void *, void *, int32_t, void *);
void F_StringJoinExt(void *, void *, void *, int32_t, void *);
void F_StringLastPos(void *, void *, void *, int32_t, void *);
void F_StringLastPosExt(void *, void *, void *, int32_t, void *);
void F_StringLength(void *, void *, void *, int32_t, void *);
void F_StringLetters(void *, void *, void *, int32_t, void *);
void F_StringLettersDigits(void *, void *, void *, int32_t, void *);
void F_StringLower(void *, void *, void *, int32_t, void *);
void F_StringOrdAt(void *, void *, void *, int32_t, void *);
void F_StringPos(void *, void *, void *, int32_t, void *);
void F_StringPosExt(void *, void *, void *, int32_t, void *);
void F_StringRepeat(void *, void *, void *, int32_t, void *);
void F_StringReplace(void *, void *, void *, int32_t, void *);
void F_StringReplaceAll(void *, void *, void *, int32_t, void *);
void F_StringSetByteAt(void *, void *, void *, int32_t, void *);
void F_StringSplit(void *, void *, void *, int32_t, void *);
void F_StringSplitExt(void *, void *, void *, int32_t, void *);
void F_StringStartsWith(void *, void *, void *, int32_t, void *);
void F_StringTrim(void *, void *, void *, int32_t, void *);
void F_StringTrimEnd(void *, void *, void *, int32_t, void *);
void F_StringTrimStart(void *, void *, void *, int32_t, void *);
void F_StringUpper(void *, void *, void *, int32_t, void *);
void F_Tan(void *, void *, void *, int32_t, void *);
void F_Typeof(void *, void *, void *, int32_t, void *);
void F_WeakRefAlive(void *, void *, void *, int32_t, void *);
void F_WeakRefAnyAlive(void *, void *, void *, int32_t, void *);
void F_WeakRefCreate(void *, void *, void *, int32_t, void *);
void * GetMethodPrototype(void);
void CHashMap<int,YYObjectBase *,3>::Init(void);
void InitMathFunctions(void);
void CHashMap<int,YYObjectBase *,3>::Insert(int32_t, void *);
int32_t MethodGetIndex(void *);
bool ResizeArray(void *, int32_t);
/* struct 0x1413 */ StringExpandPlaceholders(void *, void *, bool);
void StringReplace(void *, void *, void *, void *, bool);
void String_Trim_End(void *, void *, void *);
void String_Trim_Start(void *, void *, void *);
bool ValidateHandle(int32_t, int32_t);
void std::_Hash_vec<std::allocator<std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<__int64> >,std::_Iterator_base0> > >::_Assign_grow(void, void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<__int64 const ,int> > > > > >::_Assign_grow(void, void);
void std::_Hash<std::_Umap_traits<__int64,int,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<std::pair<__int64 const ,int> >,0> >::_Forced_rehash(/* type 0x23 */);
void std::_Hash<std::_Uset_traits<__int64,std::_Uhash_compare<__int64,std::hash<__int64>,std::equal_to<__int64> >,std::allocator<__int64>,0> >::_Forced_rehash(/* type 0x23 */);
void std::deque<ArraySortData,std::allocator<ArraySortData> >::_Growmap(/* type 0x23 */);
void std::vector<char const *,std::allocator<char const *> >::_Reallocate_exactly(void);
void std::vector<unsigned __int64,std::allocator<unsigned __int64> >::_Tidy(void);
void std::deque<ArraySortData,std::allocator<ArraySortData> >::_Xlen(void);
void std::vector<RValue,std::allocator<RValue> >::_Xlength(void);
void std::vector<unsigned __int64,std::allocator<unsigned __int64> >::_Xlength(void);
/* type 0x623 */ std::allocator<unsigned __int64>::allocate(void);
int32_t cmp_ascending(void *, void *);
int32_t cmp_descending(void *, void *);
int32_t cmp_userfunc(void *, void *);
/* type 0x13 */ iScript_Random(/* type 0x13 */);
void std::basic_string<char,std::char_traits<char>,std::allocator<char> >::reserve(void);
bool utf8_is_space(void *);
unsigned char utf8_set_char(char*, uint32_t);
void utf8_add_char(void *, uint32_t);
uint32_t utf8_extract_char(void *);
uint32_t utf8_get_char(void *);
int32_t utf8_stricmp(void *, void *);
int32_t utf8_strlen(void *);
int32_t utf8_strncmp(void *, void *, int32_t);
void * utf8_strrchr(void *, char, char);
