// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Game.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Game.obj
// 124 function symbol(s) attributed to this object.

void CallEllipseCollision(void *, float, float, float, float, void *, bool, bool, void *);
void CallEllipseCollisionList(void *, float, float, float, float, void *, bool, bool, void *, void *, bool);
void DoInstanceDestroy(void *, void *, int32_t, bool, bool);
void F_CollisionCircle(void *, void *, void *, int32_t, void *);
void F_CollisionCircleList(void *, void *, void *, int32_t, void *);
void F_CollisionEllipse(void *, void *, void *, int32_t, void *);
void F_CollisionEllipseList(void *, void *, void *, int32_t, void *);
void F_CollisionLine(void *, void *, void *, int32_t, void *);
void F_CollisionLineList(void *, void *, void *, int32_t, void *);
void F_CollisionPoint(void *, void *, void *, int32_t, void *);
void F_CollisionPointList(void *, void *, void *, int32_t, void *);
void F_CollisionRectangle(void *, void *, void *, int32_t, void *);
void F_CollisionRectangleList(void *, void *, void *, int32_t, void *);
void F_DistanceToObject(void *, void *, void *, int32_t, void *);
void F_DistanceToPoint(void *, void *, void *, int32_t, void *);
void F_GameChange(void *, void *, void *, int32_t, void *);
void F_GameEnd(void *, void *, void *, int32_t, void *);
void F_GameLoad(void *, void *, void *, int32_t, void *);
void F_GameLoadBuffer(void *, void *, void *, int32_t, void *);
void F_GameRestart(void *, void *, void *, int32_t, void *);
void F_GameSave(void *, void *, void *, int32_t, void *);
void F_GameSaveBuffer(void *, void *, void *, int32_t, void *);
void F_InstanceActivateAll(void *, void *, void *, int32_t, void *);
void F_InstanceActivateObject(void *, void *, void *, int32_t, void *);
void F_InstanceActivateRegion(void *, void *, void *, int32_t, void *);
void F_InstanceChange(void *, void *, void *, int32_t, void *);
void F_InstanceCopy(void *, void *, void *, int32_t, void *);
void F_InstanceCreateDepth(void *, void *, void *, int32_t, void *);
void F_InstanceCreateLayer(void *, void *, void *, int32_t, void *);
void F_InstanceDeactivateAll(void *, void *, void *, int32_t, void *);
void F_InstanceDeactivateObject(void *, void *, void *, int32_t, void *);
void F_InstanceDeactivateRegion(void *, void *, void *, int32_t, void *);
void F_InstanceDestroy(void *, void *, void *, int32_t, void *);
void F_InstanceExists(void *, void *, void *, int32_t, void *);
void F_InstanceFind(void *, void *, void *, int32_t, void *);
void F_InstanceFurthest(void *, void *, void *, int32_t, void *);
void F_InstanceIdGet(void *, void *, void *, int32_t, void *);
void F_InstanceNearest(void *, void *, void *, int32_t, void *);
void F_InstanceNumber(void *, void *, void *, int32_t, void *);
void F_InstancePlace(void *, void *, void *, int32_t, void *);
void F_InstancePlaceList(void *, void *, void *, int32_t, void *);
void F_InstancePosition(void *, void *, void *, int32_t, void *);
void F_InstancePositionList(void *, void *, void *, int32_t, void *);
void F_MotionAdd(void *, void *, void *, int32_t, void *);
void F_MotionSet(void *, void *, void *, int32_t, void *);
void F_MoveAndCollide(void *, void *, void *, int32_t, void *);
void F_MoveBounceAll(void *, void *, void *, int32_t, void *);
void F_MoveBounceSolid(void *, void *, void *, int32_t, void *);
void F_MoveContactAll(void *, void *, void *, int32_t, void *);
void F_MoveContactSolid(void *, void *, void *, int32_t, void *);
void F_MoveOutsideAll(void *, void *, void *, int32_t, void *);
void F_MoveOutsideSolid(void *, void *, void *, int32_t, void *);
void F_MoveRandom(void *, void *, void *, int32_t, void *);
void F_MoveSnap(void *, void *, void *, int32_t, void *);
void F_MoveTowardsPoint(void *, void *, void *, int32_t, void *);
void F_MoveWrap(void *, void *, void *, int32_t, void *);
void F_MpGridAddCell(void *, void *, void *, int32_t, void *);
void F_MpGridAddInstances(void *, void *, void *, int32_t, void *);
void F_MpGridAddRectangle(void *, void *, void *, int32_t, void *);
void F_MpGridClearAll(void *, void *, void *, int32_t, void *);
void F_MpGridClearCell(void *, void *, void *, int32_t, void *);
void F_MpGridClearRectangle(void *, void *, void *, int32_t, void *);
void F_MpGridCreate(void *, void *, void *, int32_t, void *);
void F_MpGridDestroy(void *, void *, void *, int32_t, void *);
void F_MpGridDraw(void *, void *, void *, int32_t, void *);
void F_MpGridGetCell(void *, void *, void *, int32_t, void *);
void F_MpGridPath(void *, void *, void *, int32_t, void *);
void F_MpGrid_to_DSGrid(void *, void *, void *, int32_t, void *);
void F_MpLinearPath(void *, void *, void *, int32_t, void *);
void F_MpLinearPathObject(void *, void *, void *, int32_t, void *);
void F_MpLinearStep(void *, void *, void *, int32_t, void *);
void F_MpLinearStepObject(void *, void *, void *, int32_t, void *);
void F_MpPotentialPath(void *, void *, void *, int32_t, void *);
void F_MpPotentialPathObject(void *, void *, void *, int32_t, void *);
void F_MpPotentialSettings(void *, void *, void *, int32_t, void *);
void F_MpPotentialStep(void *, void *, void *, int32_t, void *);
void F_MpPotentialStepObject(void *, void *, void *, int32_t, void *);
void F_PathEnd(void *, void *, void *, int32_t, void *);
void F_PathStart(void *, void *, void *, int32_t, void *);
void F_PlaceEmpty(void *, void *, void *, int32_t, void *);
void F_PlaceFree(void *, void *, void *, int32_t, void *);
void F_PlaceMeeting(void *, void *, void *, int32_t, void *);
void F_PlaceSnapped(void *, void *, void *, int32_t, void *);
void F_Point_In_Circle(void *, void *, void *, int32_t, void *);
void F_Point_In_Rectangle(void *, void *, void *, int32_t, void *);
void F_Point_In_Triangle(void *, void *, void *, int32_t, void *);
void F_PositionChange(void *, void *, void *, int32_t, void *);
void F_PositionDestroy(void *, void *, void *, int32_t, void *);
void F_PositionEmpty(void *, void *, void *, int32_t, void *);
void F_PositionMeeting(void *, void *, void *, int32_t, void *);
void F_Rectangle_In_Circle(void *, void *, void *, int32_t, void *);
void F_Rectangle_In_Rectangle(void *, void *, void *, int32_t, void *);
void F_Rectangle_In_Triangle(void *, void *, void *, int32_t, void *);
void F_RoomGoto(void *, void *, void *, int32_t, void *);
void F_RoomGotoNext(void *, void *, void *, int32_t, void *);
void F_RoomGotoPrevious(void *, void *, void *, int32_t, void *);
void F_RoomNext(void *, void *, void *, int32_t, void *);
void F_RoomPrevious(void *, void *, void *, int32_t, void *);
void F_RoomRestart(void *, void *, void *, int32_t, void *);
void F_SchedulerResolutionGet(void *, void *, void *, int32_t, void *);
void F_SchedulerResolutionSet(void *, void *, void *, int32_t, void *);
void F_Sleep(void *, void *, void *, int32_t, void *);
float FindDist(void *, void *);
void GenerateTileMapUVs(void *, int32_t, int32_t, int32_t, int32_t, uint32_t, void *);
void * GetActiveList(/* type 0x689c (LF_ENUM) */, void *);
void * GetDeactiveList(/* type 0x689c (LF_ENUM) */, void *);
void InitGameFunctions(void);
void InstanceRegionActivate(void *);
void InstanceRegionDeactivate(void *);
/* type 0x13 */ PerformColTest(void *, float, float, void *);
bool Point_In_Triangle(double, double, double, double, double, double, double, double);
int32_t SortFunc(void *, void *);
bool Tilemap_CollisionEllipse(float, float, float, float, /* type 0x13 */, void *, bool);
bool Tilemap_CollisionLine(float, float, float, float, /* type 0x13 */, void *, bool);
bool Tilemap_CollisionRect(float, float, float, float, /* type 0x13 */, void *, bool);
bool Tilemap_InstancePlace(void *, float, float, /* type 0x13 */, void *, bool);
bool Tilemap_PointPlace(float, float, /* type 0x13 */, void *, bool);
void YYGML_instance_activate_object(void *, void *, int32_t, /* type 0x689c (LF_ENUM) */);
bool YYGML_instance_exists(void *, void *, int32_t);
void project_pts(void *, int32_t, /* struct 0xf3f0 */, void *, void *);
