// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_File.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_File.obj
// 128 function symbol(s) attributed to this object.

void * std::max<int>(void *, void *);
void YYZipFile::~YYZipFile(void);
void yyFindData::AddFile(void *);
/* type 0x670 */ BuildHTTPRequestHeaders(int32_t, /* type 0x674 */, /* type 0x630 */);
void DecodeHandleJSON(void *, void *);
void * EncodeDSMap(void *);
void * EncodeValue(void *, void *);
void FINALIZE_Function_File(void);
void F_DirectoryCreate(void *, void *, void *, int32_t, void *);
void F_DirectoryDelete(void *, void *, void *, int32_t, void *);
void F_DirectoryExists(void *, void *, void *, int32_t, void *);
void F_EnvironmentGetVariable(void *, void *, void *, int32_t, void *);
void F_FileAttributes(void *, void *, void *, int32_t, void *);
void F_FileBinClose(void *, void *, void *, int32_t, void *);
void F_FileBinOpen(void *, void *, void *, int32_t, void *);
void F_FileBinPosition(void *, void *, void *, int32_t, void *);
void F_FileBinReadByte(void *, void *, void *, int32_t, void *);
void F_FileBinRewrite(void *, void *, void *, int32_t, void *);
void F_FileBinSeek(void *, void *, void *, int32_t, void *);
void F_FileBinSize(void *, void *, void *, int32_t, void *);
void F_FileBinWriteByte(void *, void *, void *, int32_t, void *);
void F_FileCopy(void *, void *, void *, int32_t, void *);
void F_FileDelete(void *, void *, void *, int32_t, void *);
void F_FileExists(void *, void *, void *, int32_t, void *);
void F_FileFindClose(void *, void *, void *, int32_t, void *);
void F_FileFindFirst(void *, void *, void *, int32_t, void *);
void F_FileFindNext(void *, void *, void *, int32_t, void *);
void F_FileRename(void *, void *, void *, int32_t, void *);
void F_FileTextClose(void *, void *, void *, int32_t, void *);
void F_FileTextEof(void *, void *, void *, int32_t, void *);
void F_FileTextEoln(void *, void *, void *, int32_t, void *);
void F_FileTextOpenAppend(void *, void *, void *, int32_t, void *);
void F_FileTextOpenRead(void *, void *, void *, int32_t, void *);
void F_FileTextOpenWrite(void *, void *, void *, int32_t, void *);
void F_FileTextReadLn(void *, void *, void *, int32_t, void *);
void F_FileTextReadReal(void *, void *, void *, int32_t, void *);
void F_FileTextReadString(void *, void *, void *, int32_t, void *);
void F_FileTextSet(void *, void *, void *, int32_t, void *);
void F_FileTextWriteLn(void *, void *, void *, int32_t, void *);
void F_FileTextWriteReal(void *, void *, void *, int32_t, void *);
void F_FileTextWriteString(void *, void *, void *, int32_t, void *);
void F_FilenameChangeExt(void *, void *, void *, int32_t, void *);
void F_FilenameDir(void *, void *, void *, int32_t, void *);
void F_FilenameDrive(void *, void *, void *, int32_t, void *);
void F_FilenameExt(void *, void *, void *, int32_t, void *);
void F_FilenameName(void *, void *, void *, int32_t, void *);
void F_FilenamePath(void *, void *, void *, int32_t, void *);
void F_HttpGet(void *, void *, void *, int32_t, void *);
void F_HttpGetConnectTimeout(void *, void *, void *, int32_t, void *);
void F_HttpGetFile(void *, void *, void *, int32_t, void *);
void F_HttpGetRequestCrossOrigin(void *, void *, void *, int32_t, void *);
void F_HttpPostString(void *, void *, void *, int32_t, void *);
void F_HttpRequest(void *, void *, void *, int32_t, void *);
void F_HttpSetConnectTimeout(void *, void *, void *, int32_t, void *);
void F_HttpSetRequestCrossOrigin(void *, void *, void *, int32_t, void *);
void F_IniClose(void *, void *, void *, int32_t, void *);
void F_IniKeyDelete(void *, void *, void *, int32_t, void *);
void F_IniKeyExists(void *, void *, void *, int32_t, void *);
void F_IniOpen(void *, void *, void *, int32_t, void *);
void F_IniOpenFromString(void *, void *, void *, int32_t, void *);
void F_IniReadReal(void *, void *, void *, int32_t, void *);
void F_IniReadString(void *, void *, void *, int32_t, void *);
void F_IniSectionDelete(void *, void *, void *, int32_t, void *);
void F_IniSectionExists(void *, void *, void *, int32_t, void *);
void F_IniWriteReal(void *, void *, void *, int32_t, void *);
void F_IniWriteString(void *, void *, void *, int32_t, void *);
void F_JsonDecode(void *, void *, void *, int32_t, void *);
void F_JsonDecodeExt(void *, void *, void *, int32_t, void *);
void F_JsonEncode(void *, void *, void *, int32_t, void *);
void F_JsonEncodeExt(void *, void *, void *, int32_t, void *);
void F_LoadCSV(void *, void *, void *, int32_t, void *);
void F_ParameterCount(void *, void *, void *, int32_t, void *);
void F_ParameterString(void *, void *, void *, int32_t, void *);
void F_ZipAddFile(void *, void *, void *, int32_t, void *);
void F_ZipCreate(void *, void *, void *, int32_t, void *);
void F_ZipSave(void *, void *, void *, int32_t, void *);
void F_ZipUnzip(void *, void *, void *, int32_t, void *);
void F_ZipUnzipAsync(void *, void *, void *, int32_t, void *);
void YYZipFile::Free(bool);
int32_t HttpBufferRequestCallback(void *, /* type 0x603 */, /* type 0x674 */);
int32_t HttpGetFileCallback(void *, /* type 0x603 */, /* type 0x674 */);
int32_t HttpRequestCallback(void *, /* type 0x603 */, /* type 0x674 */);
void InitFileFunctions(void);
int32_t JSONToDSMap(/* type 0x670 */, int32_t);
bool JsonParse(void *, void *);
void YYZipFile::ThreadFree(bool, void *);
void YYGML_ini_open_from_string(void *);
int32_t ZipCompressBuffSaveCallback(void *, /* type 0x603 */, /* type 0x674 */);
void ZipCompressJob(/* type 0x13 */);
void ZipCompressSaveFileJob(/* type 0x13 */);
int32_t ZipSaveLoadCallback(void *, /* type 0x603 */, /* type 0x674 */);
int32_t json_parse(void *);
int32_t json_parse_array(void *, /* type 0x670 */);
void json_parse_array_to_list(void *, /* type 0x670 */, void *);
void json_parse_ext(void *, void *, void *);
void json_parse_to_map(void *, void *);
void json_value(void *, void *);
/* type 0x623 */ __local_stdio_scanf_options(void);
int32_t sscanf(void *, void *, /* type 0x0 */);
