// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Graphics.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Graphics.obj
// 428 function symbol(s) attributed to this object.

void * std::vector<RValue *,std::allocator<RValue *> >::_Emplace_reallocate<RValue * const &>(void *, void *);
void * std::vector<RefDynamicArrayOfRValue *,std::allocator<RefDynamicArrayOfRValue *> >::_Emplace_reallocate<RefDynamicArrayOfRValue * const &>(void *, void *);
void * std::vector<HullPt,std::allocator<HullPt> >::_Emplace_reallocate<HullPt const &>(void *, void *);
void * std::vector<SFrameInfo,std::allocator<SFrameInfo> >::_Emplace_reallocate<SFrameInfo const &>(void *, void *);
void * std::vector<SMessage,std::allocator<SMessage> >::_Emplace_reallocate<SMessage const &>(void *, void *);
void * std::vector<YYTPageEntry,std::allocator<YYTPageEntry> >::_Emplace_reallocate<YYTPageEntry const &>(void *, void *);
/* type 0x640 */ std::vector<float,std::allocator<float> >::_Emplace_reallocate<float>(void *, void *);
void * std::vector<char const *,std::allocator<char const *> >::_Emplace_reallocate<char const *>(void *, void *);
void std::_Med3_unchecked<HullPt *,<unnamed-type-customSort> >(void *, void *, void *, /* struct 0xf414 */);
/* struct 0xf4cd */ std::_Partition_by_median_guess_unchecked<HullPt *,<unnamed-type-customSort> >(void *, void *, /* struct 0xf414 */);
void std::_Pop_heap_hole_by_index<HullPt *,HullPt,<unnamed-type-customSort> >(void *, /* type 0x13 */, /* type 0x13 */, void *, /* struct 0xf414 */);
void std::_Sort_unchecked<HullPt *,<unnamed-type-customSort> >(void *, void *, /* type 0x13 */, /* struct 0xf414 */);
void std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > >::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > >(void *, void *);
void std::vector<RValue *,std::allocator<RValue *> >::~vector<RValue *,std::allocator<RValue *> >(void);
void std::vector<RefDynamicArrayOfRValue *,std::allocator<RefDynamicArrayOfRValue *> >::~vector<RefDynamicArrayOfRValue *,std::allocator<RefDynamicArrayOfRValue *> >(void);
void std::vector<char const *,std::allocator<char const *> >::~vector<char const *,std::allocator<char const *> >(void);
void std::vector<HullPt,std::allocator<HullPt> >::~vector<HullPt,std::allocator<HullPt> >(void);
void std::vector<SFrameInfo,std::allocator<SFrameInfo> >::~vector<SFrameInfo,std::allocator<SFrameInfo> >(void);
void std::vector<SMessage,std::allocator<SMessage> >::~vector<SMessage,std::allocator<SMessage> >(void);
void std::vector<YYTPageEntry,std::allocator<YYTPageEntry> >::~vector<YYTPageEntry,std::allocator<YYTPageEntry> >(void);
void AddRValueToArray(void *, void *);
int32_t ConvertSurfColToRValue(void *, /* type 0x603 */, /* type 0x72fd (LF_ENUM) */);
void CreateArray(void *, int32_t, /* type 0x0 */);
void CreateArrayValOrString(void *, int32_t, /* type 0x0 */);
void F_ColorGetBlue(void *, void *, void *, int32_t, void *);
void F_ColorGetGreen(void *, void *, void *, int32_t, void *);
void F_ColorGetHue(void *, void *, void *, int32_t, void *);
void F_ColorGetRed(void *, void *, void *, int32_t, void *);
void F_ColorGetSaturation(void *, void *, void *, int32_t, void *);
void F_ColorGetValue(void *, void *, void *, int32_t, void *);
void F_DebugAddButton(void *, void *, void *, int32_t, void *);
void F_DebugAddFont(void *, void *, void *, int32_t, void *);
void F_DebugAddSpriteButton(void *, void *, void *, int32_t, void *);
void F_DebugCheckBox(void *, void *, void *, int32_t, void *);
void F_DebugColour(void *, void *, void *, int32_t, void *);
void F_DebugControlDelete(void *, void *, void *, int32_t, void *);
void F_DebugControlExists(void *, void *, void *, int32_t, void *);
void F_DebugDropDown(void *, void *, void *, int32_t, void *);
void F_DebugGetGamepadInput(void *, void *, void *, int32_t, void *);
void F_DebugRef(void *, void *, void *, int32_t, void *);
void F_DebugSameLine(void *, void *, void *, int32_t, void *);
void F_DebugSection(void *, void *, void *, int32_t, void *);
void F_DebugSectionDelete(void *, void *, void *, int32_t, void *);
void F_DebugSectionExists(void *, void *, void *, int32_t, void *);
void F_DebugSetSection(void *, void *, void *, int32_t, void *);
void F_DebugSetView(void *, void *, void *, int32_t, void *);
void F_DebugSlider(void *, void *, void *, int32_t, void *);
void F_DebugSliderInt(void *, void *, void *, int32_t, void *);
void F_DebugSprite(void *, void *, void *, int32_t, void *);
void F_DebugText(void *, void *, void *, int32_t, void *);
void F_DebugTextInput(void *, void *, void *, int32_t, void *);
void F_DebugTextSeparator(void *, void *, void *, int32_t, void *);
void F_DebugView(void *, void *, void *, int32_t, void *);
void F_DebugViewDelete(void *, void *, void *, int32_t, void *);
void F_DebugViewExists(void *, void *, void *, int32_t, void *);
void F_DebugWatch(void *, void *, void *, int32_t, void *);
void F_DisplayGetFrequency(void *, void *, void *, int32_t, void *);
void F_DisplayGetHeight(void *, void *, void *, int32_t, void *);
void F_DisplayGetOrientation(void *, void *, void *, int32_t, void *);
void F_DisplayGetSleepMargin(void *, void *, void *, int32_t, void *);
void F_DisplayGetTimingMethod(void *, void *, void *, int32_t, void *);
void F_DisplayGetVisibleRects(void *, void *, void *, int32_t, void *);
void F_DisplayGetWidth(void *, void *, void *, int32_t, void *);
void F_DisplayMouseGetX(void *, void *, void *, int32_t, void *);
void F_DisplayMouseGetY(void *, void *, void *, int32_t, void *);
void F_DisplayMouseSet(void *, void *, void *, int32_t, void *);
void F_DisplayReset(void *, void *, void *, int32_t, void *);
void F_DisplaySetSleepMargin(void *, void *, void *, int32_t, void *);
void F_DisplaySetTimingMethod(void *, void *, void *, int32_t, void *);
void F_DisplaySetUIVisibility(void *, void *, void *, int32_t, void *);
void F_DrawArrow(void *, void *, void *, int32_t, void *);
void F_DrawButton(void *, void *, void *, int32_t, void *);
void F_DrawCircle(void *, void *, void *, int32_t, void *);
void F_DrawCircleExt(void *, void *, void *, int32_t, void *);
void F_DrawClear(void *, void *, void *, int32_t, void *);
void F_DrawClearAlpha(void *, void *, void *, int32_t, void *);
void F_DrawClearDepth(void *, void *, void *, int32_t, void *);
void F_DrawClearExt(void *, void *, void *, int32_t, void *);
void F_DrawClearStencil(void *, void *, void *, int32_t, void *);
void F_DrawEllipse(void *, void *, void *, int32_t, void *);
void F_DrawEllipseExt(void *, void *, void *, int32_t, void *);
void F_DrawEnableCornerID(void *, void *, void *, int32_t, void *);
void F_DrawEnableDrawEvent(void *, void *, void *, int32_t, void *);
void F_DrawEnableSVGAA(void *, void *, void *, int32_t, void *);
void F_DrawEnableSWFAA(void *, void *, void *, int32_t, void *);
void F_DrawEnableSkeletonBlendOverride(void *, void *, void *, int32_t, void *);
void F_DrawEnableSkeletonBlendmodes(void *, void *, void *, int32_t, void *);
void F_DrawGetAlpha(void *, void *, void *, int32_t, void *);
void F_DrawGetCirclePrecision(void *, void *, void *, int32_t, void *);
void F_DrawGetColor(void *, void *, void *, int32_t, void *);
void F_DrawGetEnableSkeletonBlendOverride(void *, void *, void *, int32_t, void *);
void F_DrawGetEnableSkeletonBlendmodes(void *, void *, void *, int32_t, void *);
void F_DrawGetFont(void *, void *, void *, int32_t, void *);
void F_DrawGetHAlign(void *, void *, void *, int32_t, void *);
void F_DrawGetPixel(void *, void *, void *, int32_t, void *);
void F_DrawGetPixelExt(void *, void *, void *, int32_t, void *);
void F_DrawGetSVGAAlevel(void *, void *, void *, int32_t, void *);
void F_DrawGetSWFAAlevel(void *, void *, void *, int32_t, void *);
void F_DrawGetVAlign(void *, void *, void *, int32_t, void *);
void F_DrawHealthbar(void *, void *, void *, int32_t, void *);
void F_DrawLine(void *, void *, void *, int32_t, void *);
void F_DrawLineExt(void *, void *, void *, int32_t, void *);
void F_DrawLineWidth(void *, void *, void *, int32_t, void *);
void F_DrawLineWidthExt(void *, void *, void *, int32_t, void *);
void F_DrawPath(void *, void *, void *, int32_t, void *);
void F_DrawPoint(void *, void *, void *, int32_t, void *);
void F_DrawPointExt(void *, void *, void *, int32_t, void *);
void F_DrawPrimitiveBegin(void *, void *, void *, int32_t, void *);
void F_DrawPrimitiveBeginTexture(void *, void *, void *, int32_t, void *);
void F_DrawPrimitiveEnd(void *, void *, void *, int32_t, void *);
void F_DrawRectangle(void *, void *, void *, int32_t, void *);
void F_DrawRectangleExt(void *, void *, void *, int32_t, void *);
void F_DrawRoundRect(void *, void *, void *, int32_t, void *);
void F_DrawRoundRectColour(void *, void *, void *, int32_t, void *);
void F_DrawRoundRectColour_EXT(void *, void *, void *, int32_t, void *);
void F_DrawRoundRect_EXT(void *, void *, void *, int32_t, void *);
void F_DrawSelf(void *, void *, void *, int32_t, void *);
void F_DrawSetAlpha(void *, void *, void *, int32_t, void *);
void F_DrawSetCirclePrecision(void *, void *, void *, int32_t, void *);
void F_DrawSetColor(void *, void *, void *, int32_t, void *);
void F_DrawSetFont(void *, void *, void *, int32_t, void *);
void F_DrawSetHAlign(void *, void *, void *, int32_t, void *);
void F_DrawSetSVGAAlevel(void *, void *, void *, int32_t, void *);
void F_DrawSetSWFAAlevel(void *, void *, void *, int32_t, void *);
void F_DrawSetVAlign(void *, void *, void *, int32_t, void *);
void F_DrawSetWindowsAlternateSync(void *, void *, void *, int32_t, void *);
void F_DrawSprite(void *, void *, void *, int32_t, void *);
void F_DrawSpriteExt(void *, void *, void *, int32_t, void *);
void F_DrawSpriteGeneral(void *, void *, void *, int32_t, void *);
void F_DrawSpritePart(void *, void *, void *, int32_t, void *);
void F_DrawSpritePartExt(void *, void *, void *, int32_t, void *);
void F_DrawSpritePos(void *, void *, void *, int32_t, void *);
void F_DrawSpriteStretched(void *, void *, void *, int32_t, void *);
void F_DrawSpriteStretchedExt(void *, void *, void *, int32_t, void *);
void F_DrawSpriteTiled(void *, void *, void *, int32_t, void *);
void F_DrawSpriteTiledExt(void *, void *, void *, int32_t, void *);
void F_DrawSurface(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceExt(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceGeneral(void *, void *, void *, int32_t, void *);
void F_DrawSurfacePart(void *, void *, void *, int32_t, void *);
void F_DrawSurfacePartExt(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceStretched(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceStretchedExt(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceTiled(void *, void *, void *, int32_t, void *);
void F_DrawSurfaceTiledExt(void *, void *, void *, int32_t, void *);
void F_DrawText(void *, void *, void *, int32_t, void *);
void F_DrawTextColor(void *, void *, void *, int32_t, void *);
void F_DrawTextExt(void *, void *, void *, int32_t, void *);
void F_DrawTextExtColor(void *, void *, void *, int32_t, void *);
void F_DrawTextExtTransformed(void *, void *, void *, int32_t, void *);
void F_DrawTextExtTransformedColor(void *, void *, void *, int32_t, void *);
void F_DrawTextTransformed(void *, void *, void *, int32_t, void *);
void F_DrawTextTransformedColor(void *, void *, void *, int32_t, void *);
void F_DrawTriangle(void *, void *, void *, int32_t, void *);
void F_DrawTriangleExt(void *, void *, void *, int32_t, void *);
void F_DrawVertex(void *, void *, void *, int32_t, void *);
void F_DrawVertexColor(void *, void *, void *, int32_t, void *);
void F_DrawVertexTexture(void *, void *, void *, int32_t, void *);
void F_DrawVertexTextureColor(void *, void *, void *, int32_t, void *);
void F_FontCacheGlyph(void *, void *, void *, int32_t, void *);
void F_FontEnableEffects(void *, void *, void *, int32_t, void *);
void F_FontEnableSdf(void *, void *, void *, int32_t, void *);
void F_FontGetBaseUV(void *, void *, void *, int32_t, void *);
void F_FontGetInfo(void *, void *, void *, int32_t, void *);
void F_FontGetSdfEnabled(void *, void *, void *, int32_t, void *);
void F_FontGetSdfSpread(void *, void *, void *, int32_t, void *);
void F_FontGetTexture(void *, void *, void *, int32_t, void *);
void F_FontSdfSpread(void *, void *, void *, int32_t, void *);
void F_IsKeyboardUsedDebugOverlay(void *, void *, void *, int32_t, void *);
void F_IsMouseOverDebugOverlay(void *, void *, void *, int32_t, void *);
void F_MakeColorHSV(void *, void *, void *, int32_t, void *);
void F_MakeColorRGB(void *, void *, void *, int32_t, void *);
void F_MergeColor(void *, void *, void *, int32_t, void *);
void F_ScreenSave(void *, void *, void *, int32_t, void *);
void F_ScreenSavePart(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationGetEventFrames(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationGetFrame(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationGetPosition(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationIsFinished(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationIsLooping(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationList(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationMix(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationSetFrame(void *, void *, void *, int32_t, void *);
void F_SkeletonAnimationSetPosition(void *, void *, void *, int32_t, void *);
void F_SkeletonAttachmentExists(void *, void *, void *, int32_t, void *);
void F_SkeletonBoneList(void *, void *, void *, int32_t, void *);
void F_SkeletonClearAnimation(void *, void *, void *, int32_t, void *);
void F_SkeletonCreateAttachment(void *, void *, void *, int32_t, void *);
void F_SkeletonCreateAttachmentCol(void *, void *, void *, int32_t, void *);
void F_SkeletonCreateSkinFromSkins(void *, void *, void *, int32_t, void *);
void F_SkeletonDestroyAttachment(void *, void *, void *, int32_t, void *);
void F_SkeletonDraw(void *, void *, void *, int32_t, void *);
void F_SkeletonDrawCollision(void *, void *, void *, int32_t, void *);
void F_SkeletonDrawInstance(void *, void *, void *, int32_t, void *);
void F_SkeletonDrawTime(void *, void *, void *, int32_t, void *);
void F_SkeletonFindSlot(void *, void *, void *, int32_t, void *);
void F_SkeletonGetAnimation(void *, void *, void *, int32_t, void *);
void F_SkeletonGetAttachment(void *, void *, void *, int32_t, void *);
void F_SkeletonGetBoneData(void *, void *, void *, int32_t, void *);
void F_SkeletonGetBoneState(void *, void *, void *, int32_t, void *);
void F_SkeletonGetBounds(void *, void *, void *, int32_t, void *);
void F_SkeletonGetDuration(void *, void *, void *, int32_t, void *);
void F_SkeletonGetFrames(void *, void *, void *, int32_t, void *);
void F_SkeletonGetMinmax(void *, void *, void *, int32_t, void *);
void F_SkeletonGetNumBounds(void *, void *, void *, int32_t, void *);
void F_SkeletonGetSkin(void *, void *, void *, int32_t, void *);
void F_SkeletonReplaceAttachment(void *, void *, void *, int32_t, void *);
void F_SkeletonReplaceAttachmentCol(void *, void *, void *, int32_t, void *);
void F_SkeletonSetAnimation(void *, void *, void *, int32_t, void *);
void F_SkeletonSetAnimationExt(void *, void *, void *, int32_t, void *);
void F_SkeletonSetAttachment(void *, void *, void *, int32_t, void *);
void F_SkeletonSetBoneData(void *, void *, void *, int32_t, void *);
void F_SkeletonSetBoneState(void *, void *, void *, int32_t, void *);
void F_SkeletonSetDrawCollision(void *, void *, void *, int32_t, void *);
void F_SkeletonSetSkin(void *, void *, void *, int32_t, void *);
void F_SkeletonSkinList(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotAlphaGet(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotColourGet(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotColourSet(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotData(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotDataInstance(void *, void *, void *, int32_t, void *);
void F_SkeletonSlotList(void *, void *, void *, int32_t, void *);
void F_SpriteGetBaseUV(void *, void *, void *, int32_t, void *);
void F_SpriteGetConvexHull(void *, void *, void *, int32_t, void *);
void F_SpriteGetInfo(void *, void *, void *, int32_t, void *);
void F_SpriteGetTexture(void *, void *, void *, int32_t, void *);
void F_StringHeight(void *, void *, void *, int32_t, void *);
void F_StringHeightExt(void *, void *, void *, int32_t, void *);
void F_StringWidth(void *, void *, void *, int32_t, void *);
void F_StringWidthExt(void *, void *, void *, int32_t, void *);
void F_SurfaceCopy(void *, void *, void *, int32_t, void *);
void F_SurfaceCopyPart(void *, void *, void *, int32_t, void *);
void F_SurfaceCreate(void *, void *, void *, int32_t, void *);
void F_SurfaceCreateEmpty(void *, void *, void *, int32_t, void *);
void F_SurfaceDepthDisable(void *, void *, void *, int32_t, void *);
void F_SurfaceExists(void *, void *, void *, int32_t, void *);
void F_SurfaceFormatIsSupported(void *, void *, void *, int32_t, void *);
void F_SurfaceFree(void *, void *, void *, int32_t, void *);
void F_SurfaceGetDepthDisable(void *, void *, void *, int32_t, void *);
void F_SurfaceGetFormat(void *, void *, void *, int32_t, void *);
void F_SurfaceGetHeight(void *, void *, void *, int32_t, void *);
void F_SurfaceGetPixel(void *, void *, void *, int32_t, void *);
void F_SurfaceGetPixelExt(void *, void *, void *, int32_t, void *);
void F_SurfaceGetTarget(void *, void *, void *, int32_t, void *);
void F_SurfaceGetTargetDepth(void *, void *, void *, int32_t, void *);
void F_SurfaceGetTargetExt(void *, void *, void *, int32_t, void *);
void F_SurfaceGetTexture(void *, void *, void *, int32_t, void *);
void F_SurfaceGetTextureDepth(void *, void *, void *, int32_t, void *);
void F_SurfaceGetWidth(void *, void *, void *, int32_t, void *);
void F_SurfaceHasDepth(void *, void *, void *, int32_t, void *);
void F_SurfaceResetTarget(void *, void *, void *, int32_t, void *);
void F_SurfaceResize(void *, void *, void *, int32_t, void *);
void F_SurfaceSave(void *, void *, void *, int32_t, void *);
void F_SurfaceSavePart(void *, void *, void *, int32_t, void *);
void F_SurfaceSetTarget(void *, void *, void *, int32_t, void *);
void F_SurfaceSetTargetExt(void *, void *, void *, int32_t, void *);
void F_TextureGetHeight(void *, void *, void *, int32_t, void *);
void F_TextureGetUVs(void *, void *, void *, int32_t, void *);
void F_TextureGetWidth(void *, void *, void *, int32_t, void *);
void F_TextureGlobalScale(void *, void *, void *, int32_t, void *);
void F_TextureGroup_Add(void *, void *, void *, int32_t, void *);
void F_TextureGroup_Delete(void *, void *, void *, int32_t, void *);
void F_TexturePreload(void *, void *, void *, int32_t, void *);
void F_TextureSetPriority(void *, void *, void *, int32_t, void *);
void F_TilesetGetBaseUV(void *, void *, void *, int32_t, void *);
void F_TilesetGetTexture(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheGetMaxUsed(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheGetOldestEntryAge(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheGetPruneAge(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheGetPruneFraction(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheGetUsed(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCacheLimit(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCachePruneAge(void *, void *, void *, int32_t, void *);
void F_VectorSpriteCachePruneFraction(void *, void *, void *, int32_t, void *);
void F_VectorSpriteGetCacheLimit(void *, void *, void *, int32_t, void *);
void F_WindowCenter(void *, void *, void *, int32_t, void *);
void F_WindowDefault(void *, void *, void *, int32_t, void *);
void F_WindowEnableBorderlessFullscreen(void *, void *, void *, int32_t, void *);
void F_WindowGetBorderlessFullscreen(void *, void *, void *, int32_t, void *);
void F_WindowGetCaption(void *, void *, void *, int32_t, void *);
void F_WindowGetColor(void *, void *, void *, int32_t, void *);
void F_WindowGetCursor(void *, void *, void *, int32_t, void *);
void F_WindowGetFullscreen(void *, void *, void *, int32_t, void *);
void F_WindowGetHeight(void *, void *, void *, int32_t, void *);
void F_WindowGetShowborder(void *, void *, void *, int32_t, void *);
void F_WindowGetShowicons(void *, void *, void *, int32_t, void *);
void F_WindowGetSizeable(void *, void *, void *, int32_t, void *);
void F_WindowGetStayontop(void *, void *, void *, int32_t, void *);
void F_WindowGetVisible(void *, void *, void *, int32_t, void *);
void F_WindowGetWidth(void *, void *, void *, int32_t, void *);
void F_WindowGetX(void *, void *, void *, int32_t, void *);
void F_WindowGetY(void *, void *, void *, int32_t, void *);
void F_WindowMinimise(void *, void *, void *, int32_t, void *);
void F_WindowMouseGetDeltaX(void *, void *, void *, int32_t, void *);
void F_WindowMouseGetDeltaY(void *, void *, void *, int32_t, void *);
void F_WindowMouseGetLocked(void *, void *, void *, int32_t, void *);
void F_WindowMouseGetX(void *, void *, void *, int32_t, void *);
void F_WindowMouseGetY(void *, void *, void *, int32_t, void *);
void F_WindowMouseSet(void *, void *, void *, int32_t, void *);
void F_WindowMouseSetLocked(void *, void *, void *, int32_t, void *);
void F_WindowRestore(void *, void *, void *, int32_t, void *);
void F_WindowSetCaption(void *, void *, void *, int32_t, void *);
void F_WindowSetColor(void *, void *, void *, int32_t, void *);
void F_WindowSetCursor(void *, void *, void *, int32_t, void *);
void F_WindowSetFullscreen(void *, void *, void *, int32_t, void *);
void F_WindowSetMaxHeight(void *, void *, void *, int32_t, void *);
void F_WindowSetMaxWidth(void *, void *, void *, int32_t, void *);
void F_WindowSetMinHeight(void *, void *, void *, int32_t, void *);
void F_WindowSetMinWidth(void *, void *, void *, int32_t, void *);
void F_WindowSetPosition(void *, void *, void *, int32_t, void *);
void F_WindowSetRectangle(void *, void *, void *, int32_t, void *);
void F_WindowSetShowborder(void *, void *, void *, int32_t, void *);
void F_WindowSetShowicons(void *, void *, void *, int32_t, void *);
void F_WindowSetSize(void *, void *, void *, int32_t, void *);
void F_WindowSetSizeable(void *, void *, void *, int32_t, void *);
void F_WindowSetStayontop(void *, void *, void *, int32_t, void *);
void F_WindowSetVisible(void *, void *, void *, int32_t, void *);
void F_WindowViewMouseGetX(void *, void *, void *, int32_t, void *);
void F_WindowViewMouseGetY(void *, void *, void *, int32_t, void *);
void F_WindowViewMouseSet(void *, void *, void *, int32_t, void *);
void F_WindowViewsMouseGetX(void *, void *, void *, int32_t, void *);
void F_WindowViewsMouseGetY(void *, void *, void *, int32_t, void *);
void F_WindowViewsMouseSet(void *, void *, void *, int32_t, void *);
/* struct 0xf676 */ GenConvHull(int32_t, int32_t, int32_t);
bool GetSpriteIndices(void *, void *, void *, void *);
void InitGraphicFunctions(void);
void SetMaskData(void *, void *, void *, int32_t);
void TEXGROUPADD_InitHashes(void);
void TEXGROUPADD_Init_FrameInfoFromStruct(void *, void *, void *, int32_t, int32_t, void *);
bool TEXGROUPADD_Init_From_Struct(void *, void *);
void TEXGROUPADD_Init_MessagesFromStruct(void *, void *, void *, int32_t, int32_t, void *);
void TEXGROUPADD_Init_NineSliceFromStruct(void *, void *, void *, int32_t, int32_t, void *);
int32_t TEXGROUPADD_Init_SpriteFromStruct(void *, void *, void *);
void TEXGROUPADD_Init_TPEFromStruct(void *, void *, void *, int32_t, int32_t, void *);
void std::vector<char const *,std::allocator<char const *> >::_Change_array(void *, void, void);
void std::vector<char const *,std::allocator<char const *> >::_Tidy(void);
void std::vector<RValue *,std::allocator<RValue *> >::_Xlength(void);
void std::vector<RefDynamicArrayOfRValue *,std::allocator<RefDynamicArrayOfRValue *> >::_Xlength(void);
void std::vector<char const *,std::allocator<char const *> >::_Xlength(void);
void std::vector<HullPt,std::allocator<HullPt> >::_Xlength(void);
void std::vector<SFrameInfo,std::allocator<SFrameInfo> >::_Xlength(void);
void std::vector<SMessage,std::allocator<SMessage> >::_Xlength(void);
void std::vector<YYTPageEntry,std::allocator<YYTPageEntry> >::_Xlength(void);
void std::vector<RefDynamicArrayOfRValue *,std::allocator<RefDynamicArrayOfRValue *> >::_Xrange(void);
void * std::allocator<char const *>::allocate(void);
