// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Data_Structures.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Data_Structures.obj
// 210 function symbol(s) attributed to this object.

void DS_AutoMutex::DS_AutoMutex(void);
void DS_AutoMutex::~DS_AutoMutex(void);
bool CheckEncryptedUDID(char*);
char* EncryptUDID(void);
void F_DsExists(void *, void *, void *, int32_t, void *);
void F_DsGridAdd(void *, void *, void *, int32_t, void *);
void F_DsGridAddDisk(void *, void *, void *, int32_t, void *);
void F_DsGridAddGridRegion(void *, void *, void *, int32_t, void *);
void F_DsGridAddRegion(void *, void *, void *, int32_t, void *);
void F_DsGridClear(void *, void *, void *, int32_t, void *);
void F_DsGridCopy(void *, void *, void *, int32_t, void *);
void F_DsGridCreate(void *, void *, void *, int32_t, void *);
void F_DsGridDestroy(void *, void *, void *, int32_t, void *);
void F_DsGridGetDiskMax(void *, void *, void *, int32_t, void *);
void F_DsGridGetDiskMean(void *, void *, void *, int32_t, void *);
void F_DsGridGetDiskMin(void *, void *, void *, int32_t, void *);
void F_DsGridGetDiskSum(void *, void *, void *, int32_t, void *);
void F_DsGridGetMax(void *, void *, void *, int32_t, void *);
void F_DsGridGetMean(void *, void *, void *, int32_t, void *);
void F_DsGridGetMin(void *, void *, void *, int32_t, void *);
void F_DsGridGetSum(void *, void *, void *, int32_t, void *);
void F_DsGridGet_debug(void *, void *, void *, int32_t, void *);
void F_DsGridGet_release(void *, void *, void *, int32_t, void *);
void F_DsGridHeight(void *, void *, void *, int32_t, void *);
void F_DsGridMultiply(void *, void *, void *, int32_t, void *);
void F_DsGridMultiplyDisk(void *, void *, void *, int32_t, void *);
void F_DsGridMultiplyGridRegion(void *, void *, void *, int32_t, void *);
void F_DsGridMultiplyRegion(void *, void *, void *, int32_t, void *);
void F_DsGridRead(void *, void *, void *, int32_t, void *);
void F_DsGridResize(void *, void *, void *, int32_t, void *);
void F_DsGridSetDisk(void *, void *, void *, int32_t, void *);
void F_DsGridSetGridRegion(void *, void *, void *, int32_t, void *);
void F_DsGridSetPost(void *, void *, void *, int32_t, void *);
void F_DsGridSetPre(void *, void *, void *, int32_t, void *);
void F_DsGridSetRegion(void *, void *, void *, int32_t, void *);
void F_DsGridSet_debug(void *, void *, void *, int32_t, void *);
void F_DsGridSet_release(void *, void *, void *, int32_t, void *);
void F_DsGridShuffle(void *, void *, void *, int32_t, void *);
void F_DsGridSort(void *, void *, void *, int32_t, void *);
void F_DsGridToMpGrid(void *, void *, void *, int32_t, void *);
void F_DsGridValueDiskExists(void *, void *, void *, int32_t, void *);
void F_DsGridValueDiskX(void *, void *, void *, int32_t, void *);
void F_DsGridValueDiskY(void *, void *, void *, int32_t, void *);
void F_DsGridValueExists(void *, void *, void *, int32_t, void *);
void F_DsGridValueX(void *, void *, void *, int32_t, void *);
void F_DsGridValueY(void *, void *, void *, int32_t, void *);
void F_DsGridWidth(void *, void *, void *, int32_t, void *);
void F_DsGridWrite(void *, void *, void *, int32_t, void *);
void F_DsListAdd(void *, void *, void *, int32_t, void *);
void F_DsListClear(void *, void *, void *, int32_t, void *);
void F_DsListCopy(void *, void *, void *, int32_t, void *);
void F_DsListCreate(void *, void *, void *, int32_t, void *);
void F_DsListDelete(void *, void *, void *, int32_t, void *);
void F_DsListDestroy(void *, void *, void *, int32_t, void *);
void F_DsListEmpty(void *, void *, void *, int32_t, void *);
void F_DsListFindIndex(void *, void *, void *, int32_t, void *);
void F_DsListFindValue(void *, void *, void *, int32_t, void *);
void F_DsListInsert(void *, void *, void *, int32_t, void *);
void F_DsListIsList(void *, void *, void *, int32_t, void *);
void F_DsListIsMap(void *, void *, void *, int32_t, void *);
void F_DsListMarkAsList(void *, void *, void *, int32_t, void *);
void F_DsListMarkAsMap(void *, void *, void *, int32_t, void *);
void F_DsListRead(void *, void *, void *, int32_t, void *);
void F_DsListReplace(void *, void *, void *, int32_t, void *);
void F_DsListSet(void *, void *, void *, int32_t, void *);
void F_DsListSetPost(void *, void *, void *, int32_t, void *);
void F_DsListSetPre(void *, void *, void *, int32_t, void *);
void F_DsListShuffle(void *, void *, void *, int32_t, void *);
void F_DsListSize(void *, void *, void *, int32_t, void *);
void F_DsListSort(void *, void *, void *, int32_t, void *);
void F_DsListWrite(void *, void *, void *, int32_t, void *);
void F_DsMapAdd(void *, void *, void *, int32_t, void *);
void F_DsMapAddList(void *, void *, void *, int32_t, void *);
void F_DsMapAddMap(void *, void *, void *, int32_t, void *);
bool F_DsMapAdd_Internal(int32_t, void *, void *);
bool F_DsMapAdd_Internal(int32_t, void *, double);
void F_DsMapClear(void *, void *, void *, int32_t, void *);
void F_DsMapCopy(void *, void *, void *, int32_t, void *);
void F_DsMapCreate(void *, void *, void *, int32_t, void *);
void F_DsMapDelete(void *, void *, void *, int32_t, void *);
void F_DsMapDestroy(void *, void *, void *, int32_t, void *);
void F_DsMapEmpty(void *, void *, void *, int32_t, void *);
void F_DsMapExists(void *, void *, void *, int32_t, void *);
void F_DsMapFindFirst(void *, void *, void *, int32_t, void *);
void F_DsMapFindLast(void *, void *, void *, int32_t, void *);
void F_DsMapFindNext(void *, void *, void *, int32_t, void *);
void F_DsMapFindPrevious(void *, void *, void *, int32_t, void *);
void F_DsMapFindValue(void *, void *, void *, int32_t, void *);
void F_DsMapIsList(void *, void *, void *, int32_t, void *);
void F_DsMapIsMap(void *, void *, void *, int32_t, void *);
void F_DsMapKeysToArray(void *, void *, void *, int32_t, void *);
void F_DsMapRead(void *, void *, void *, int32_t, void *);
void F_DsMapReplace(void *, void *, void *, int32_t, void *);
void F_DsMapReplaceList(void *, void *, void *, int32_t, void *);
void F_DsMapReplaceMap(void *, void *, void *, int32_t, void *);
void F_DsMapSecureLoad(void *, void *, void *, int32_t, void *);
void F_DsMapSecureLoadBuffer(void *, void *, void *, int32_t, void *);
void F_DsMapSecureSave(void *, void *, void *, int32_t, void *);
void F_DsMapSecureSaveBuffer(void *, void *, void *, int32_t, void *);
void F_DsMapSet(void *, void *, void *, int32_t, void *);
void F_DsMapSetPost(void *, void *, void *, int32_t, void *);
void F_DsMapSetPre(void *, void *, void *, int32_t, void *);
void F_DsMapSize(void *, void *, void *, int32_t, void *);
void F_DsMapValuesToArray(void *, void *, void *, int32_t, void *);
void F_DsMapWrite(void *, void *, void *, int32_t, void *);
void F_DsPriorityAdd(void *, void *, void *, int32_t, void *);
void F_DsPriorityChangePriority(void *, void *, void *, int32_t, void *);
void F_DsPriorityClear(void *, void *, void *, int32_t, void *);
void F_DsPriorityCopy(void *, void *, void *, int32_t, void *);
void F_DsPriorityCreate(void *, void *, void *, int32_t, void *);
void F_DsPriorityDeleteMax(void *, void *, void *, int32_t, void *);
void F_DsPriorityDeleteMin(void *, void *, void *, int32_t, void *);
void F_DsPriorityDeleteValue(void *, void *, void *, int32_t, void *);
void F_DsPriorityDestroy(void *, void *, void *, int32_t, void *);
void F_DsPriorityEmpty(void *, void *, void *, int32_t, void *);
void F_DsPriorityFindMax(void *, void *, void *, int32_t, void *);
void F_DsPriorityFindMin(void *, void *, void *, int32_t, void *);
void F_DsPriorityFindPriority(void *, void *, void *, int32_t, void *);
void F_DsPriorityRead(void *, void *, void *, int32_t, void *);
void F_DsPrioritySize(void *, void *, void *, int32_t, void *);
void F_DsPriorityWrite(void *, void *, void *, int32_t, void *);
void F_DsQueueClear(void *, void *, void *, int32_t, void *);
void F_DsQueueCopy(void *, void *, void *, int32_t, void *);
void F_DsQueueCreate(void *, void *, void *, int32_t, void *);
void F_DsQueueDequeue(void *, void *, void *, int32_t, void *);
void F_DsQueueDestroy(void *, void *, void *, int32_t, void *);
void F_DsQueueEmpty(void *, void *, void *, int32_t, void *);
void F_DsQueueEnqueue(void *, void *, void *, int32_t, void *);
void F_DsQueueHead(void *, void *, void *, int32_t, void *);
void F_DsQueueRead(void *, void *, void *, int32_t, void *);
void F_DsQueueSize(void *, void *, void *, int32_t, void *);
void F_DsQueueTail(void *, void *, void *, int32_t, void *);
void F_DsQueueWrite(void *, void *, void *, int32_t, void *);
void F_DsSetPrecision(void *, void *, void *, int32_t, void *);
void F_DsStackClear(void *, void *, void *, int32_t, void *);
void F_DsStackCopy(void *, void *, void *, int32_t, void *);
void F_DsStackCreate(void *, void *, void *, int32_t, void *);
void F_DsStackDestroy(void *, void *, void *, int32_t, void *);
void F_DsStackEmpty(void *, void *, void *, int32_t, void *);
void F_DsStackPop(void *, void *, void *, int32_t, void *);
void F_DsStackPush(void *, void *, void *, int32_t, void *);
void F_DsStackRead(void *, void *, void *, int32_t, void *);
void F_DsStackSize(void *, void *, void *, int32_t, void *);
void F_DsStackTop(void *, void *, void *, int32_t, void *);
void F_DsStackWrite(void *, void *, void *, int32_t, void *);
int32_t FindFreeDsListIndex(void);
int32_t FindFreeDsMapIndex(void);
void InitDataStructuresFunctions(void);
void * YYGML_ds_grid_create(void *, int32_t, int32_t);
void dsListAddInt64(int32_t, /* type 0x13 */);
void dsListAddMap(int32_t, int32_t);
void dsListClear(int32_t);
int32_t dsListCreate(void);
void dsMapAddList(int32_t, void *, int32_t);
void dsMapClear(int32_t);
