// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Misc.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Misc.obj
// 156 function symbol(s) attributed to this object.

/* struct 0x1a633 */ std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::_Find_last<RValue *>(void *, void);
/* struct 0x10528 */ std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::_Try_emplace<RValue * const &>(void *);
void std::fill<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > > > *,std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > > > >(void *, void *, void *);
/* struct 0x10295 */ std::make_unique<RValue,0>(void);
void std::_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,void *> > >::~_Alloc_construct_ptr<std::allocator<std::_List_node<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,void *> > >(void);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > > > > >::~_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > > > > >(void);
void std::_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,void *> > >::~_List_node_emplace_op2<std::allocator<std::_List_node<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,void *> > >(void);
void std::list<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > >::~list<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > >,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > >(void);
void std::unique_ptr<RValue,std::default_delete<RValue> >::~unique_ptr<RValue,std::default_delete<RValue> >(void);
void std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::_Clear_guard::~_Clear_guard(void);
void AddEntryToStruct(/* type 0x603 */, void *, /* type 0x13 */);
int32_t AllocGif(void);
void StructVarsMap::DeleteCheckKey(int32_t);
bool DoVariableInstanceExists(void *, void *);
bool DoVariableInstanceExistsFromHash(void *, int32_t);
void F_AlarmGet(void *, void *, void *, int32_t, void *);
void F_AlarmSet(void *, void *, void *, int32_t, void *);
void F_DateCompareDate(void *, void *, void *, int32_t, void *);
void F_DateCompareDateTime(void *, void *, void *, int32_t, void *);
void F_DateCompareTime(void *, void *, void *, int32_t, void *);
void F_DateCreateDateTime(void *, void *, void *, int32_t, void *);
void F_DateCurrentDateTime(void *, void *, void *, int32_t, void *);
void F_DateDateOf(void *, void *, void *, int32_t, void *);
void F_DateDateString(void *, void *, void *, int32_t, void *);
void F_DateDateTimeString(void *, void *, void *, int32_t, void *);
void F_DateDaySpan(void *, void *, void *, int32_t, void *);
void F_DateDaysInMonth(void *, void *, void *, int32_t, void *);
void F_DateDaysInYear(void *, void *, void *, int32_t, void *);
void F_DateGetDay(void *, void *, void *, int32_t, void *);
void F_DateGetDayOfYear(void *, void *, void *, int32_t, void *);
void F_DateGetHour(void *, void *, void *, int32_t, void *);
void F_DateGetHourOfYear(void *, void *, void *, int32_t, void *);
void F_DateGetMinute(void *, void *, void *, int32_t, void *);
void F_DateGetMinuteOfYear(void *, void *, void *, int32_t, void *);
void F_DateGetMonth(void *, void *, void *, int32_t, void *);
void F_DateGetSecond(void *, void *, void *, int32_t, void *);
void F_DateGetSecondOfYear(void *, void *, void *, int32_t, void *);
void F_DateGetTimezone(void *, void *, void *, int32_t, void *);
void F_DateGetWeek(void *, void *, void *, int32_t, void *);
void F_DateGetWeekday(void *, void *, void *, int32_t, void *);
void F_DateGetYear(void *, void *, void *, int32_t, void *);
void F_DateHourSpan(void *, void *, void *, int32_t, void *);
void F_DateIncDay(void *, void *, void *, int32_t, void *);
void F_DateIncHour(void *, void *, void *, int32_t, void *);
void F_DateIncMinute(void *, void *, void *, int32_t, void *);
void F_DateIncMonth(void *, void *, void *, int32_t, void *);
void F_DateIncSecond(void *, void *, void *, int32_t, void *);
void F_DateIncWeek(void *, void *, void *, int32_t, void *);
void F_DateIncYear(void *, void *, void *, int32_t, void *);
void F_DateIsToday(void *, void *, void *, int32_t, void *);
void F_DateLeapYear(void *, void *, void *, int32_t, void *);
void F_DateMinuteSpan(void *, void *, void *, int32_t, void *);
void F_DateMonthSpan(void *, void *, void *, int32_t, void *);
void F_DateSecondSpan(void *, void *, void *, int32_t, void *);
void F_DateSetTimezone(void *, void *, void *, int32_t, void *);
void F_DateTimeOf(void *, void *, void *, int32_t, void *);
void F_DateTimeString(void *, void *, void *, int32_t, void *);
void F_DateValidDateTime(void *, void *, void *, int32_t, void *);
void F_DateWeekSpan(void *, void *, void *, int32_t, void *);
void F_DateYearSpan(void *, void *, void *, int32_t, void *);
void F_DebugEvent(void *, void *, void *, int32_t, void *);
void F_EventInherited(void *, void *, void *, int32_t, void *);
void F_EventObject(void *, void *, void *, int32_t, void *);
void F_EventPerform(void *, void *, void *, int32_t, void *);
void F_EventPerformAsync(void *, void *, void *, int32_t, void *);
void F_EventUser(void *, void *, void *, int32_t, void *);
void F_ExtensionExists(void *, void *, void *, int32_t, void *);
void F_ExtensionGetOptionCount(void *, void *, void *, int32_t, void *);
void F_ExtensionGetOptionNames(void *, void *, void *, int32_t, void *);
void F_ExtensionGetOptionValue(void *, void *, void *, int32_t, void *);
void F_ExtensionGetOptions(void *, void *, void *, int32_t, void *);
void F_ExtensionGetVersion(void *, void *, void *, int32_t, void *);
void F_ExternalCall(void *, void *, void *, int32_t, void *);
void F_ExternalDefine(void *, void *, void *, int32_t, void *);
void F_ExternalFree(void *, void *, void *, int32_t, void *);
void F_GCCollect(void *, void *, void *, int32_t, void *);
void F_GCEnable(void *, void *, void *, int32_t, void *);
void F_GCGetStats(void *, void *, void *, int32_t, void *);
void F_GCGetTargetFrameTime(void *, void *, void *, int32_t, void *);
void F_GCIsEnabled(void *, void *, void *, int32_t, void *);
void F_GCTargetFrameTime(void *, void *, void *, int32_t, void *);
void F_GameGetSpeed(void *, void *, void *, int32_t, void *);
void F_GameSetSpeed(void *, void *, void *, int32_t, void *);
void F_GifAddSurface(void *, void *, void *, int32_t, void *);
void F_GifOpen(void *, void *, void *, int32_t, void *);
void F_GifSave(void *, void *, void *, int32_t, void *);
void F_GifSaveBuffer(void *, void *, void *, int32_t, void *);
void F_IsDebugOverlayOpen(void *, void *, void *, int32_t, void *);
void F_ShowDebugLog(void *, void *, void *, int32_t, void *);
void F_ShowDebugMessage(void *, void *, void *, int32_t, void *);
void F_ShowDebugMessageExt(void *, void *, void *, int32_t, void *);
void F_ShowDebugOverlay(void *, void *, void *, int32_t, void *);
void F_StaticGet(void *, void *, void *, int32_t, void *);
void F_StaticSet(void *, void *, void *, int32_t, void *);
void F_VariableClone(void *, void *, void *, int32_t, void *);
void F_VariableGetHash(void *, void *, void *, int32_t, void *);
void F_VariableGlobalExists(void *, void *, void *, int32_t, void *);
void F_VariableGlobalGet(void *, void *, void *, int32_t, void *);
void F_VariableGlobalSet(void *, void *, void *, int32_t, void *);
void F_VariableInstanceExists(void *, void *, void *, int32_t, void *);
void F_VariableInstanceExistsFromHash(void *, void *, void *, int32_t, void *);
void F_VariableInstanceForeach(void *, void *, void *, int32_t, void *);
void F_VariableInstanceGet(void *, void *, void *, int32_t, void *);
void F_VariableInstanceGetFromHash(void *, void *, void *, int32_t, void *);
void F_VariableInstanceGetNames(void *, void *, void *, int32_t, void *);
void F_VariableInstanceNamesCount(void *, void *, void *, int32_t, void *);
void F_VariableInstanceRemove(void *, void *, void *, int32_t, void *);
void F_VariableInstanceRemoveFromHash(void *, void *, void *, int32_t, void *);
void F_VariableInstanceSet(void *, void *, void *, int32_t, void *);
void F_VariableInstanceSetFromHash(void *, void *, void *, int32_t, void *);
void F_VariableInstanceSetPost(void *, void *, void *, int32_t, void *);
void F_VariableInstanceSetPre(void *, void *, void *, int32_t, void *);
void F_WindowPostMessage(void *, void *, void *, int32_t, void *);
void Fixup_Scriptrefs(void *, int32_t, void *, void *);
int32_t GetSecondOfYear(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
void InitMiscFunctions(void);
void InstanceCopyAllVariables(void *, void *, int32_t, void *);
void Variable_Clone(void *, void *, void *, void *, int32_t, void *);
int32_t WriteGif(void *, void *, int32_t);
void YYGML_show_debug_message(void *);
void std::_Hash_vec<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > > > > > >::_Assign_grow(void, void);
void std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::_Forced_rehash(/* type 0x23 */);
void std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::clear(void);
int32_t NeuQuant::contest(double, double, double);
void extOptGetRValue(void *, void *, void *);
void NeuQuant::inxbuild(void);
int32_t NeuQuant::inxsearch(int32_t, int32_t, int32_t);
bool is_leap_year(int32_t);
void NeuQuant::learn(void);
void std::_Hash<std::_Umap_traits<RValue *,std::unique_ptr<RValue,std::default_delete<RValue> >,std::_Uhash_compare<RValue *,hashRValue,equalsRValue>,std::allocator<std::pair<RValue * const,std::unique_ptr<RValue,std::default_delete<RValue> > > >,0> >::reserve(/* type 0x23 */);
