// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\Function_Particles.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Function_Particles.obj
// 79 function symbol(s) attributed to this object.

void F_EffectClear(void *, void *, void *, int32_t, void *);
void F_EffectCreateAbove(void *, void *, void *, int32_t, void *);
void F_EffectCreateBelow(void *, void *, void *, int32_t, void *);
void F_EffectCreateDepth(void *, void *, void *, int32_t, void *);
void F_EffectCreateLayer(void *, void *, void *, int32_t, void *);
void F_PartEmitterBurst(void *, void *, void *, int32_t, void *);
void F_PartEmitterClear(void *, void *, void *, int32_t, void *);
void F_PartEmitterCreate(void *, void *, void *, int32_t, void *);
void F_PartEmitterDelay(void *, void *, void *, int32_t, void *);
void F_PartEmitterDestroy(void *, void *, void *, int32_t, void *);
void F_PartEmitterDestroyAll(void *, void *, void *, int32_t, void *);
void F_PartEmitterEnable(void *, void *, void *, int32_t, void *);
void F_PartEmitterExists(void *, void *, void *, int32_t, void *);
void F_PartEmitterInterval(void *, void *, void *, int32_t, void *);
void F_PartEmitterRegion(void *, void *, void *, int32_t, void *);
void F_PartEmitterRelative(void *, void *, void *, int32_t, void *);
void F_PartEmitterStream(void *, void *, void *, int32_t, void *);
void F_PartParticlesBurst(void *, void *, void *, int32_t, void *);
void F_PartParticlesClear(void *, void *, void *, int32_t, void *);
void F_PartParticlesCount(void *, void *, void *, int32_t, void *);
void F_PartParticlesCreate(void *, void *, void *, int32_t, void *);
void F_PartParticlesCreateColor(void *, void *, void *, int32_t, void *);
void F_PartSystemAngle(void *, void *, void *, int32_t, void *);
void F_PartSystemAutomaticDraw(void *, void *, void *, int32_t, void *);
void F_PartSystemAutomaticUpdate(void *, void *, void *, int32_t, void *);
void F_PartSystemClear(void *, void *, void *, int32_t, void *);
void F_PartSystemColor(void *, void *, void *, int32_t, void *);
void F_PartSystemCreate(void *, void *, void *, int32_t, void *);
void F_PartSystemCreateLayer(void *, void *, void *, int32_t, void *);
void F_PartSystemDepth(void *, void *, void *, int32_t, void *);
void F_PartSystemDestroy(void *, void *, void *, int32_t, void *);
void F_PartSystemDrawIt(void *, void *, void *, int32_t, void *);
void F_PartSystemDrawOrder(void *, void *, void *, int32_t, void *);
void F_PartSystemExists(void *, void *, void *, int32_t, void *);
void F_PartSystemGetInfo(void *, void *, void *, int32_t, void *);
void F_PartSystemGetLayer(void *, void *, void *, int32_t, void *);
void F_PartSystemGlobalSpace(void *, void *, void *, int32_t, void *);
void F_PartSystemLayer(void *, void *, void *, int32_t, void *);
void F_PartSystemPosition(void *, void *, void *, int32_t, void *);
void F_PartSystemUpdate(void *, void *, void *, int32_t, void *);
void F_PartTypeAlpha1(void *, void *, void *, int32_t, void *);
void F_PartTypeAlpha2(void *, void *, void *, int32_t, void *);
void F_PartTypeAlpha3(void *, void *, void *, int32_t, void *);
void F_PartTypeBlend(void *, void *, void *, int32_t, void *);
void F_PartTypeClear(void *, void *, void *, int32_t, void *);
void F_PartTypeColor1(void *, void *, void *, int32_t, void *);
void F_PartTypeColor2(void *, void *, void *, int32_t, void *);
void F_PartTypeColor3(void *, void *, void *, int32_t, void *);
void F_PartTypeColorHSV(void *, void *, void *, int32_t, void *);
void F_PartTypeColorMix(void *, void *, void *, int32_t, void *);
void F_PartTypeColorRGB(void *, void *, void *, int32_t, void *);
void F_PartTypeCreate(void *, void *, void *, int32_t, void *);
void F_PartTypeDeath(void *, void *, void *, int32_t, void *);
void F_PartTypeDestroy(void *, void *, void *, int32_t, void *);
void F_PartTypeDirection(void *, void *, void *, int32_t, void *);
void F_PartTypeExists(void *, void *, void *, int32_t, void *);
void F_PartTypeGravity(void *, void *, void *, int32_t, void *);
void F_PartTypeLife(void *, void *, void *, int32_t, void *);
void F_PartTypeOrientation(void *, void *, void *, int32_t, void *);
void F_PartTypeScale(void *, void *, void *, int32_t, void *);
void F_PartTypeShape(void *, void *, void *, int32_t, void *);
void F_PartTypeSize(void *, void *, void *, int32_t, void *);
void F_PartTypeSizeX(void *, void *, void *, int32_t, void *);
void F_PartTypeSizeY(void *, void *, void *, int32_t, void *);
void F_PartTypeSpeed(void *, void *, void *, int32_t, void *);
void F_PartTypeSprite(void *, void *, void *, int32_t, void *);
void F_PartTypeStep(void *, void *, void *, int32_t, void *);
void F_PartTypeSubimage(void *, void *, void *, int32_t, void *);
void F_ParticleAdd(void *, void *, void *, int32_t, void *);
void F_ParticleDelete(void *, void *, void *, int32_t, void *);
void F_ParticleExists(void *, void *, void *, int32_t, void *);
void F_ParticleGetInfo(void *, void *, void *, int32_t, void *);
void * GetLayer(void *, int32_t);
int32_t GetPartSystemResourceIndex(void *, int32_t, bool, bool);
void InitParticlesFunctions(void);
void ParticleSystemGetInfoImpl(void *, void *, void *, int32_t, void *, bool);
void std::vector<SEmitter *,std::allocator<SEmitter *> >::_Reallocate_exactly(void);
