// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Function\YoYo_Functions.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\YoYo_Functions.obj
// 89 function symbol(s) attributed to this object.

void ConvertYYWCharToUint16(void *, int32_t, /* type 0x621 */);
int32_t CountNum16BitChars(void *);
void F_AppSurfaceEnable(void *, void *, void *, int32_t, void *);
void F_AppSurfaceIsEnabled(void *, void *, void *, int32_t, void *);
void F_ApplicationGetPos(void *, void *, void *, int32_t, void *);
void F_CodeIsCompiled(void *, void *, void *, int32_t, void *);
void F_GMLApplicationSurfaceDrawEnable(void *, void *, void *, int32_t, void *);
void F_GMLApplicationSurfaceIsDrawEnabled(void *, void *, void *, int32_t, void *);
void F_GMLReleaseMode(void *, void *, void *, int32_t, void *);
void F_IO_AddVirtualKey(void *, void *, void *, int32_t, void *);
void F_IO_DeleteVirtualKey(void *, void *, void *, int32_t, void *);
void F_IO_HideVirtualKey(void *, void *, void *, int32_t, void *);
void F_IO_ShowVirtualKey(void *, void *, void *, int32_t, void *);
void F_MouseXToGUI(void *, void *, void *, int32_t, void *);
void F_MouseYToGUI(void *, void *, void *, int32_t, void *);
void F_Platform_Function_Not_Supported(void *, void *, void *, int32_t, void *);
void F_StubFuncReal(void *, void *, void *, int32_t, void *);
void F_StubFuncString(void *, void *, void *, int32_t, void *);
void F_YoYo_Base64Decode(void *, void *, void *, int32_t, void *);
void F_YoYo_Base64Encode(void *, void *, void *, int32_t, void *);
void F_YoYo_CheckPermission(void *, void *, void *, int32_t, void *);
void F_YoYo_CloudFileSave(void *, void *, void *, int32_t, void *);
void F_YoYo_CloudStringSave(void *, void *, void *, int32_t, void *);
void F_YoYo_CloudSynchronise(void *, void *, void *, int32_t, void *);
void F_YoYo_GetConfig(void *, void *, void *, int32_t, void *);
void F_YoYo_GetDPIX(void *, void *, void *, int32_t, void *);
void F_YoYo_GetDPIY(void *, void *, void *, int32_t, void *);
void F_YoYo_GetDomain(void *, void *, void *, int32_t, void *);
void F_YoYo_GetGUIHeight(void *, void *, void *, int32_t, void *);
void F_YoYo_GetGUIWidth(void *, void *, void *, int32_t, void *);
void F_YoYo_GetLanguage(void *, void *, void *, int32_t, void *);
void F_YoYo_GetRegion(void *, void *, void *, int32_t, void *);
void F_YoYo_GetTiltX(void *, void *, void *, int32_t, void *);
void F_YoYo_GetTiltY(void *, void *, void *, int32_t, void *);
void F_YoYo_GetTiltZ(void *, void *, void *, int32_t, void *);
void F_YoYo_GetTimer(void *, void *, void *, int32_t, void *);
void F_YoYo_IsKeypadOpen(void *, void *, void *, int32_t, void *);
void F_YoYo_IsNetworkConnected(void *, void *, void *, int32_t, void *);
void F_YoYo_LeaveRating(void *, void *, void *, int32_t, void *);
void F_YoYo_LockOrientation(void *, void *, void *, int32_t, void *);
void F_YoYo_MD5File(void *, void *, void *, int32_t, void *);
void F_YoYo_MD5Unicode(void *, void *, void *, int32_t, void *);
void F_YoYo_MD5Utf8(void *, void *, void *, int32_t, void *);
void F_YoYo_MouseXRaw(void *, void *, void *, int32_t, void *);
void F_YoYo_MouseYRaw(void *, void *, void *, int32_t, void *);
void F_YoYo_OSHasFocus(void *, void *, void *, int32_t, void *);
void F_YoYo_OSPauseEvent(void *, void *, void *, int32_t, void *);
void F_YoYo_OpenURL(void *, void *, void *, int32_t, void *);
void F_YoYo_OpenURL_ext(void *, void *, void *, int32_t, void *);
void F_YoYo_OpenURL_full(void *, void *, void *, int32_t, void *);
void F_YoYo_OsGetInfo(void *, void *, void *, int32_t, void *);
void F_YoYo_PowersaveEnable(void *, void *, void *, int32_t, void *);
void F_YoYo_RequestPermission(void *, void *, void *, int32_t, void *);
void F_YoYo_SHA1File(void *, void *, void *, int32_t, void *);
void F_YoYo_SHA1Unicode(void *, void *, void *, int32_t, void *);
void F_YoYo_SHA1Utf8(void *, void *, void *, int32_t, void *);
void F_YoYo_SetGUIMaximise(void *, void *, void *, int32_t, void *);
void F_YoYo_SetGUISize(void *, void *, void *, int32_t, void *);
void F_YoYo_SetLockOrientation(void *, void *, void *, int32_t, void *);
void F_debug_input_playback(void *, void *, void *, int32_t, void *);
void F_debug_input_record(void *, void *, void *, int32_t, void *);
void F_debug_input_save(void *, void *, void *, int32_t, void *);
void F_video_close(void *, void *, void *, int32_t, void *);
void F_video_draw(void *, void *, void *, int32_t, void *);
void F_video_enable_loop(void *, void *, void *, int32_t, void *);
void F_video_get_duration(void *, void *, void *, int32_t, void *);
void F_video_get_format(void *, void *, void *, int32_t, void *);
void F_video_get_position(void *, void *, void *, int32_t, void *);
void F_video_get_status(void *, void *, void *, int32_t, void *);
void F_video_get_volume(void *, void *, void *, int32_t, void *);
void F_video_is_looping(void *, void *, void *, int32_t, void *);
void F_video_open(void *, void *, void *, int32_t, void *);
void F_video_pause(void *, void *, void *, int32_t, void *);
void F_video_resume(void *, void *, void *, int32_t, void *);
void F_video_seek_to(void *, void *, void *, int32_t, void *);
void F_video_setVolume(void *, void *, void *, int32_t, void *);
bool GET_YoYo_GetBrowserHeight(void *, int32_t, void *);
bool GET_YoYo_GetBrowserWidth(void *, int32_t, void *);
bool GET_YoYo_GetDevice(void *, int32_t, void *);
bool GET_YoYo_GetOSBrowser(void *, int32_t, void *);
bool GET_YoYo_GetOSVersion(void *, int32_t, void *);
bool GET_YoYo_GetPlatform(void *, int32_t, void *);
void InitYoYoBuiltInVariables(void);
void InitYoYoFunctions(void);
