// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\Files\Javascript\g_dfmt.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\Javascript.obj
// 95 function symbol(s) attributed to this object.

void YYStrBuilder::~YYStrBuilder(void);
void __ContextStackHelper::~__ContextStackHelper(void);
/* type 0x8a83 (LF_ENUM) */ CALL_RValue(void *, void *, void *, void *, int32_t, void *);
void Call_Accessor_Get(void *, void *, void *);
void Call_Accessor_Set(void *, void *, void *);
/* type 0x8a83 (LF_ENUM) */ Call_RValue(void *, void *, void *, int32_t, void *);
/* type 0x8a83 (LF_ENUM) */ Call_ScriptRef_Direct(void *, void *, void *, void *, int32_t, void *);
void CreateArgumentsObject(void *, void *, int32_t, void *, bool);
void * Create_StandardBuiltInObjectPrototype(void);
void * EncodeObject(void *);
void F_CopyStatic(void *, void *, void *, int32_t, void *);
void F_ExceptionUnhandledHandler(void *, void *, void *, int32_t, void *);
void F_GML_Object_prototype_toString(void *, void *, void *, int32_t, void *);
void F_JSDelete(void *, void *, void *, int32_t, void *);
void F_JSError(void *, void *, void *, int32_t, void *);
void F_JSFinishCatch(void *, void *, void *, int32_t, void *);
void F_JSFinishFinally(void *, void *, void *, int32_t, void *);
void F_JSGetInstance(void *, void *, void *, int32_t, void *);
void F_JSGlobal(void *, void *, void *, int32_t, void *);
void F_JSGlobalScope(void *, void *, void *, int32_t, void *);
void F_JSInstanceOf(void *, void *, void *, int32_t, void *);
void F_JSNew(void *, void *, void *, int32_t, void *);
void F_JSNewGMLObject(void *, void *, void *, int32_t, void *);
void F_JSNewObject(void *, void *, void *, int32_t, void *);
void F_JSNewProperty(void *, void *, void *, int32_t, void *);
void F_JSNull(void *, void *, void *, int32_t, void *);
void F_JSNullObject(void *, void *, void *, int32_t, void *);
void F_JSOther(void *, void *, void *, int32_t, void *);
void F_JSPrint(void *, void *, void *, int32_t, void *);
void F_JSThis(void *, void *, void *, int32_t, void *);
void F_JSThrow(void *, void *, void *, int32_t, void *);
void F_JSTryHook(void *, void *, void *, int32_t, void *);
void F_JSTryUnHook(void *, void *, void *, int32_t, void *);
void F_JSTypeof(void *, void *, void *, int32_t, void *);
/* type 0x8a83 (LF_ENUM) */ F_JS_Object_DefaultValue(void *, void *, int32_t);
void F_JS_Object_Get(void *, void *, void *);
/* type 0x8a83 (LF_ENUM) */ F_JS_ToNumber(void *, void *, bool);
/* type 0x8a83 (LF_ENUM) */ F_JS_ToPrimitive(void *, void *, int32_t);
/* type 0x8a83 (LF_ENUM) */ F_JS_ToString(void *, void *);
void F_NewGMLArray(void *, void *, void *, int32_t, void *);
void F_SetStatic(void *, void *, void *, int32_t, void *);
void * StructVarsMap::FindPositionV(int32_t);
/* type 0x8a6d (LF_ENUM) */ HasInstance(void *, void *);
void InitJavaScriptFunctions(void);
void JSThrowReferenceError(void *);
void JS_Argument_Get(void *, void *, void *);
void JS_Argument_Put(void *, void *, void *);
void JS_Array_Put(void *, void *, void *);
bool JS_CanPut(void *, void *);
void JS_DefaultGetOwnProperty(void *, void *, void *);
/* type 0x6fe8 (LF_ENUM) */ JS_DefineOwnProperty_Internal(void *, void *, void *, bool);
void JS_DeleteProperty(void *, void *, void *, bool);
void JS_GetProperty(void *, void *, void *);
bool JS_HasProperty(void *, void *);
bool JS_IsCallable(void *);
void JS_Object_Put(void *, void *, void *, bool);
bool JS_SameValue(void *, void *);
void * JS_SetupFunction(void *, int32_t, bool);
void JS_StandardBuiltInObjectConstructor(void *, void *, void *, int32_t, void *);
int32_t KIND_RValue(void *);
void NativeErrorCall(void *, void *, void *, void *, void *, int32_t, void *);
void UnwindExceptionStack(void);
void YYThrow(void *);
void * RValue::asObject(void);
char* YYStrBuilder::ensureSpace(int32_t);
void freedtoa(char*);
char* gdtoa(void *, int32_t, /* type 0x675 */, /* type 0x674 */, int32_t, int32_t, /* type 0x674 */, void *);
void * _RefThing<char const *>::get(void);
bool isWhitespace(int32_t);
void * utf8proc_get_property(int32_t);
void * Balloc_D2A(int32_t);
int32_t cmp_D2A(void *, void *);
void * diff_D2A(void *, void *);
char* g__fmt_D2A(char*, char*, char*, int32_t, uint32_t, /* type 0x23 */);
int32_t hi0bits_D2A(uint32_t);
void * i2b_D2A(int32_t);
void * lshift_D2A(void *, int32_t);
void * mult_D2A(void *, void *);
void * multadd_D2A(void *, int32_t, int32_t);
void * pow5mult_D2A(void *, int32_t);
int32_t quorem_D2A(void *, void *);
char* rv_alloc_D2A(int32_t);
