// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\imgui\imgui_widgets.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\imgui_widgets.obj
// 134 function symbol(s) attributed to this object.

bool ImGui::DragBehaviorT<int,int,float>(int32_t, /* type 0x674 */, float, void, void, void *, int32_t);
bool ImGui::DragBehaviorT<unsigned int,int,float>(int32_t, /* type 0x675 */, float, void, void, void *, int32_t);
bool ImGui::DragBehaviorT<float,float,float>(int32_t, /* type 0x640 */, float, void, void, void *, int32_t);
bool ImGui::DragBehaviorT<double,double,double>(int32_t, /* type 0x641 */, float, void, void, void *, int32_t);
bool ImGui::DragBehaviorT<__int64,__int64,double>(int32_t, /* type 0x613 */, float, void, void, void *, int32_t);
bool ImGui::DragBehaviorT<unsigned __int64,__int64,double>(int32_t, /* type 0x623 */, float, void, void, void *, int32_t);
int32_t ImGui::RoundScalarWithFormatT<int>(void *, int32_t, int32_t);
uint32_t ImGui::RoundScalarWithFormatT<unsigned int>(void *, int32_t, uint32_t);
float ImGui::RoundScalarWithFormatT<float>(void *, int32_t, float);
double ImGui::RoundScalarWithFormatT<double>(void *, int32_t, double);
/* type 0x13 */ ImGui::RoundScalarWithFormatT<__int64>(void *, int32_t, /* type 0x13 */);
/* type 0x23 */ ImGui::RoundScalarWithFormatT<unsigned __int64>(void *, int32_t, /* type 0x23 */);
float ImGui::ScaleRatioFromValueT<int,int,float>(int32_t, int32_t, int32_t, int32_t, bool, float, float);
float ImGui::ScaleRatioFromValueT<unsigned int,int,float>(int32_t, uint32_t, uint32_t, uint32_t, bool, float, float);
float ImGui::ScaleRatioFromValueT<float,float,float>(int32_t, float, float, float, bool, float, float);
float ImGui::ScaleRatioFromValueT<double,double,double>(int32_t, double, double, double, bool, float, float);
float ImGui::ScaleRatioFromValueT<__int64,__int64,double>(int32_t, /* type 0x13 */, /* type 0x13 */, /* type 0x13 */, bool, float, float);
float ImGui::ScaleRatioFromValueT<unsigned __int64,__int64,double>(int32_t, /* type 0x23 */, /* type 0x23 */, /* type 0x23 */, bool, float, float);
int32_t ImGui::ScaleValueFromRatioT<int,int,float>(int32_t, float, int32_t, int32_t, bool, float, float);
uint32_t ImGui::ScaleValueFromRatioT<unsigned int,int,float>(int32_t, float, uint32_t, uint32_t, bool, float, float);
float ImGui::ScaleValueFromRatioT<float,float,float>(int32_t, float, float, float, bool, float, float);
double ImGui::ScaleValueFromRatioT<double,double,double>(int32_t, float, double, double, bool, float, float);
/* type 0x13 */ ImGui::ScaleValueFromRatioT<__int64,__int64,double>(int32_t, float, /* type 0x13 */, /* type 0x13 */, bool, float, float);
/* type 0x23 */ ImGui::ScaleValueFromRatioT<unsigned __int64,__int64,double>(int32_t, float, /* type 0x23 */, /* type 0x23 */, bool, float, float);
bool ImGui::SliderBehaviorT<int,int,float>(void *, uint32_t, int32_t, /* type 0x674 */, void, void, void *, int32_t, void *);
bool ImGui::SliderBehaviorT<unsigned int,int,float>(void *, uint32_t, int32_t, /* type 0x675 */, void, void, void *, int32_t, void *);
bool ImGui::SliderBehaviorT<float,float,float>(void *, uint32_t, int32_t, /* type 0x640 */, void, void, void *, int32_t, void *);
bool ImGui::SliderBehaviorT<double,double,double>(void *, uint32_t, int32_t, /* type 0x641 */, void, void, void *, int32_t, void *);
bool ImGui::SliderBehaviorT<__int64,__int64,double>(void *, uint32_t, int32_t, /* type 0x613 */, void, void, void *, int32_t, void *);
bool ImGui::SliderBehaviorT<unsigned __int64,__int64,double>(void *, uint32_t, int32_t, /* type 0x623 */, void, void, void *, int32_t, void *);
void ImGui::AlignTextToFramePadding(void);
bool ImGui::ArrowButtonEx(void *, int32_t, /* struct 0xcf46 */, int32_t);
bool ImGui::BeginCombo(void *, void *, int32_t);
bool ImGui::BeginComboPopup(uint32_t, void *, int32_t);
bool ImGui::BeginMainMenuBar(void);
bool ImGui::BeginMenuBar(void);
bool ImGui::BeginMenuEx(void *, void *, bool);
bool ImGui::BeginTabBarEx(void *, void *, int32_t);
bool ImGui::ButtonBehavior(void *, uint32_t, /* type 0x630 */, /* type 0x630 */, int32_t);
bool ImGui::ButtonEx(void *, void *, int32_t);
float CalcMaxPopupHeightFromItemCount(int32_t);
bool ImGui::Checkbox(void *, /* type 0x630 */);
bool ImGui::CloseButton(uint32_t, void *);
bool ImGui::CollapseButton(uint32_t, void *, void *);
bool ImGui::CollapsingHeader(void *, /* type 0x630 */, int32_t);
bool ImGui::ColorButton(void *, void *, int32_t, void *);
bool ImGui::ColorEdit4(void *, /* type 0x640 */, int32_t);
void ImGui::ColorEditOptionsPopup(void *, int32_t);
void ColorEditRestoreHS(void *, /* type 0x640 */, /* type 0x640 */, /* type 0x640 */);
bool ImGui::ColorPicker4(void *, /* type 0x640 */, int32_t, void *);
void ImGui::ColorPickerOptionsPopup(void *, int32_t);
void ImGui::ColorTooltip(void *, void *, int32_t);
bool ImGui::Combo(void *, /* type 0x674 */, void *, /* type 0x603 */, int32_t, int32_t);
bool ImGui::DataTypeApplyFromText(void *, int32_t, /* type 0x603 */, void *);
int32_t ImGui::DataTypeCompare(int32_t, void *, void *);
int32_t ImGui::DataTypeFormatString(char*, int32_t, int32_t, void *, void *);
float ImGuiMenuColumns::DeclColumns(float, float, float, float);
void ImGuiInputTextCallbackData::DeleteChars(int32_t, int32_t);
bool ImGui::DragBehavior(uint32_t, int32_t, /* type 0x603 */, float, void *, void *, void *, int32_t);
bool ImGui::DragScalar(void *, int32_t, /* type 0x603 */, float, void *, void *, void *, int32_t);
void ImGui::Dummy(void *);
void ImGui::EndMenu(void);
void ImGui::EndMenuBar(void);
void ImGui::EndTabBar(void);
uint32_t ImGui::GetWindowScrollbarID(void *, /* type 0x108f8 (LF_ENUM) */);
void * ImParseFormatFindEnd(void *);
int32_t ImParseFormatPrecision(void *, int32_t);
void ImGui::Image(/* type 0x603 */, void *, void *, void *, void *, void *);
bool ImGui::ImageButtonEx(uint32_t, /* type 0x603 */, void *, void *, void *, void *, void *, int32_t);
void ImGui::InputTextDeactivateHook(uint32_t);
bool ImGui::InputTextEx(void *, void *, char*, int32_t, void *, int32_t, void *, /* type 0x603 */);
bool InputTextFilterCharacter(void *, /* type 0x675 */, int32_t, void *, /* type 0x603 */, bool);
void InputTextReconcileUndoStateAfterUserCallback(void *, void *, int32_t);
void ImGuiInputTextCallbackData::InsertChars(int32_t, void *, void *);
bool ImGui::InvisibleButton(void *, void *, int32_t);
bool IsRootOfOpenMenuSet(void);
bool ImGui::MenuItemEx(void *, void *, void *, bool, bool);
bool ImGui::RadioButton(void *, bool);
void RenderArrowsForVerticalBar(void *, /* struct 0xcf46 */, /* struct 0xcf46 */, float, float);
void ImStb::STB_TEXTEDIT_DELETECHARS(void *, int32_t, int32_t);
float ImStb::STB_TEXTEDIT_GETWIDTH(void *, int32_t, int32_t);
bool ImStb::STB_TEXTEDIT_INSERTCHARS(void *, int32_t, void *, int32_t);
void ImStb::STB_TEXTEDIT_LAYOUTROW(void *, void *, int32_t);
int32_t ImStb::STB_TEXTEDIT_MOVEWORDLEFT_IMPL(void *, int32_t);
int32_t ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_IMPL(void *, int32_t);
int32_t ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_MAC(void *, int32_t);
void ImGui::Scrollbar(/* type 0x108f8 (LF_ENUM) */);
bool ImGui::ScrollbarEx(void *, uint32_t, /* type 0x108f8 (LF_ENUM) */, /* type 0x613 */, /* type 0x13 */, /* type 0x13 */, int32_t);
bool ImGui::Selectable(void *, bool, int32_t, void *);
void ImGui::Separator(void);
void ImGui::SeparatorEx(int32_t, float);
void ImGui::SeparatorText(void *);
void ImGui::SeparatorTextEx(uint32_t, void *, void *, float);
int32_t ShrinkWidthItemComparer(void *, void *);
void ImGui::ShrinkWidths(void *, int32_t, float);
bool ImGui::SliderBehavior(void *, uint32_t, int32_t, /* type 0x603 */, void *, void *, void *, int32_t, void *);
bool ImGui::SliderScalar(void *, int32_t, /* type 0x603 */, void *, void *, void *, int32_t);
bool ImGui::SplitterBehavior(void *, uint32_t, /* type 0x108f8 (LF_ENUM) */, /* type 0x640 */, /* type 0x640 */, float, float, float, float, uint32_t);
void ImGui::TabBarAddTab(void *, int32_t, void *);
void * ImGui::TabBarGetTabName(void *, void *);
void ImGui::TabBarLayout(void *);
void ImGui::TabBarQueueReorderFromMousePos(void *, void *, /* struct 0xcf46 */);
void ImGui::TabBarRemoveTab(void *, uint32_t);
void * ImGui::TabBarScrollingButtons(void *);
void * ImGui::TabBarTabListPopupButton(void *);
void ImGui::TabItemBackground(void *, void *, int32_t, uint32_t);
/* struct 0xcf46 */ ImGui::TabItemCalcSize(void *, bool);
int32_t TabItemComparerByBeginOrder(void *, void *);
int32_t TabItemComparerBySection(void *, void *);
bool ImGui::TabItemEx(void *, void *, /* type 0x630 */, int32_t, void *);
void ImGui::TabItemLabelAndCloseButton(void *, void *, int32_t, /* struct 0xcf46 */, void *, uint32_t, uint32_t, bool, /* type 0x630 */, /* type 0x630 */);
bool ImGui::TempInputScalar(void *, uint32_t, void *, int32_t, /* type 0x603 */, void *, void *, void *);
void ImGui::Text(void *, char *);
void ImGui::TextColored(void *, void *, char *);
void ImGui::TextEx(void *, void *, int32_t);
void ImGui::TextV(void *, char*);
bool ImGui::TreeNodeBehavior(uint32_t, int32_t, void *, void *);
void ImGui::TreePushOverrideID(uint32_t);
void ImGuiMenuColumns::Update(float, bool);
int32_t ImStb::is_word_boundary_from_right(void *, int32_t);
void ImVector<ImGuiTabItem>::reserve(int32_t);
/* type 0x621 */ ImStb::stb_text_createundo(void *, int32_t, int32_t, int32_t);
int32_t ImStb::stb_text_locate_coord(void *, float, float);
void ImStb::stb_text_makeundo_replace(void *, void *, int32_t, int32_t, int32_t);
void ImStb::stb_text_undo(void *, void *);
void ImStb::stb_textedit_clamp(void *, void *);
void ImStb::stb_textedit_click(void *, void *, float, float);
void ImStb::stb_textedit_delete(void *, void *, int32_t, int32_t);
void ImStb::stb_textedit_delete_selection(void *, void *);
void ImStb::stb_textedit_discard_undo(void *);
void ImStb::stb_textedit_find_charpos(void *, void *, int32_t, int32_t);
void ImStb::stb_textedit_key(void *, void *, int32_t);
void ImStb::stb_textedit_move_to_last(void *, void *);
void ImStb::stb_textedit_replace(void *, void *, void *, int32_t);
