// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\imgui\imgui.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\imgui.obj
// 368 function symbol(s) attributed to this object.

void IM_DELETE<ImDrawList>(void *);
void IM_DELETE<ImGuiDockNode>(void *);
void IM_DELETE<ImGuiTabBar>(void *);
void IM_DELETE<ImGuiViewportP>(void *);
void ImVector<ImGuiDockNode *>::ImVector<ImGuiDockNode *>(void);
void ImDrawData::ImDrawData(void);
void ImGuiContext::ImGuiContext(void *);
void ImGuiDockNode::ImGuiDockNode(uint32_t);
void ImGuiIO::ImGuiIO(void);
void ImGuiStyle::ImGuiStyle(void);
void ImGuiViewportP::ImGuiViewportP(void);
void ImGuiWindow::ImGuiWindow(void *, void *);
void ImVector<unsigned short>::~ImVector<unsigned short>(void);
void ImVector<unsigned int>::~ImVector<unsigned int>(void);
void ImVector<ImDrawList *>::~ImVector<ImDrawList *>(void);
void ImVector<ImGuiDockNode *>::~ImVector<ImGuiDockNode *>(void);
void ImVector<ImGuiViewport *>::~ImVector<ImGuiViewport *>(void);
void ImVector<ImGuiWindow *>::~ImVector<ImGuiWindow *>(void);
void ImVector<void *>::~ImVector<void *>(void);
void ImVector<ImDrawChannel>::~ImVector<ImDrawChannel>(void);
void ImVector<ImDrawCmd>::~ImVector<ImDrawCmd>(void);
void ImVector<ImDrawVert>::~ImVector<ImDrawVert>(void);
void ImVector<ImGuiPlatformMonitor>::~ImVector<ImGuiPlatformMonitor>(void);
void ImVector<ImGuiTabItem>::~ImVector<ImGuiTabItem>(void);
void ImVector<ImVec4>::~ImVector<ImVec4>(void);
void ImDrawList::~ImDrawList(void);
void ImGuiDockPreviewData::~ImGuiDockPreviewData(void);
void ImGuiIO::~ImGuiIO(void);
void ImGuiPlatformIO::~ImGuiPlatformIO(void);
void * ImGui::AcceptDragDropPayload(void *, int32_t);
void ImGuiIO::AddInputCharacter(uint32_t);
void ImGuiIO::AddKeyAnalogEvent(/* type 0xced0 (LF_ENUM) */, bool, float);
void ImGuiIO::AddMouseButtonEvent(int32_t, bool);
void ImGuiIO::AddMousePosEvent(float, float);
void * ImGui::AddUpdateViewport(void *, uint32_t, void *, void *, int32_t);
void AddWindowToDrawData(void *, int32_t);
void AddWindowToSortBuffer(void *, void *);
void ApplyWindowSettings(void *, void *);
bool ImGui::Begin(void *, /* type 0x630 */, int32_t);
bool ImGui::BeginChildEx(void *, uint32_t, void *, int32_t, int32_t);
void ImGui::BeginDisabled(bool);
void ImGui::BeginDockableDragDropTarget(void *);
void ImGui::BeginDocked(void *, /* type 0x630 */);
bool ImGui::BeginDragDropSource(int32_t);
void ImGui::BeginGroup(void);
bool ImGui::BeginPopupEx(uint32_t, int32_t);
bool ImGui::BeginTooltipEx(int32_t, int32_t);
void ImGui::BringWindowToDisplayFront(void *);
float ImGuiWindow::CalcFontSize(void);
/* struct 0xcf46 */ ImGui::CalcItemSize(/* struct 0xcf46 */, float, float);
float ImGui::CalcItemWidth(void);
/* struct 0xcf46 */ CalcNextScrollFromScrollTargetAndClamp(void *);
void CalcResizePosSizeFromAnyCorner(void *, void *, void *, void *, void *);
int32_t ImGui::CalcTypematicRepeatAmount(float, float, float, float);
/* struct 0xcf46 */ CalcWindowAutoFitSize(void *, void *);
void CalcWindowContentSizes(void *, void *, void *);
/* struct 0xcf46 */ CalcWindowMinSize(void *);
/* struct 0xcf46 */ CalcWindowSizeAfterConstraint(void *, void *);
int32_t ChildWindowComparer(void *, void *);
void ClampWindowPos(void *, void *);
void ImGuiKeyRoutingTable::Clear(void);
void ImGuiStorage::Clear(void);
void ImGui::ClearDragDrop(void);
void ImGuiIO::ClearInputKeys(void);
void ImRect::ClipWithFull(void *);
void ImGui::ClosePopupToLevel(int32_t, bool);
void ImGui::ClosePopupsOverWindow(void *, bool);
uint32_t ImGui::ColorConvertFloat4ToU32(void *);
void ImGui::ColorConvertHSVtoRGB(float, float, float, void *, void *, void *);
void ImGui::ColorConvertRGBtoHSV(float, float, float, void *, void *, void *);
bool ImRect::Contains(void *);
/* type 0xced0 (LF_ENUM) */ ImGui::ConvertSingleModFlagToKey(void *, /* type 0xced0 (LF_ENUM) */);
void * CreateNewWindow(void *, int32_t);
void * ImGui::CreateNewWindowSettings(void *);
void ImGui::DebugHookIdInfo(uint32_t, int32_t, void *, void *);
void ImGui::DebugLocateItemResolveWithLastItem(void);
void ImGui::DebugLog(void *, /* type 0x0 */);
void ImGui::DebugLogV(void *, char*);
void DebugPrintInputEvent(void *, void *);
void ImGui::DestroyPlatformWindow(void *);
void ImGui::DockBuilderRemoveNodeChildNodes(uint32_t);
void ImGui::DockBuilderRemoveNodeDockedWindows(uint32_t, bool);
void * ImGui::DockContextAddNode(void *, uint32_t);
void ImGui::DockContextBuildAddWindowsToNodes(void *, uint32_t);
void ImGui::DockContextBuildNodesFromSettings(void *, void *, int32_t);
void ImGui::DockContextEndFrame(void *);
uint32_t ImGui::DockContextGenNodeID(void *);
void ImGui::DockContextNewFrameUpdateDocking(void *);
void ImGui::DockContextNewFrameUpdateUndocking(void *);
void ImGui::DockContextProcessDock(void *, void *);
void ImGui::DockContextProcessUndockNode(void *, void *);
void ImGui::DockContextProcessUndockWindow(void *, void *, bool);
void ImGui::DockContextPruneUnusedSettingsNodes(void *);
void ImGui::DockContextRemoveNode(void *, void *, bool);
void ImGui::DockNodeAddTabBar(void *);
void ImGui::DockNodeAddWindow(void *, void *, bool);
bool ImGui::DockNodeCalcDropRectsAndTestMousePos(void *, int32_t, void *, bool, void *);
int32_t DockNodeComparerDepthMostFirst(void *, void *);
void DockNodeFindInfo(void *, void *);
void ImGui::DockNodeHideHostWindow(void *);
bool ImGui::DockNodeIsDropAllowed(void *, void *);
bool DockNodeIsDropAllowedOne(void *, void *);
void ImGui::DockNodeMoveWindows(void *, void *);
void ImGui::DockNodePreviewDockRender(void *, void *, void *, void *);
void ImGui::DockNodePreviewDockSetup(void *, void *, void *, void *, void *, bool, bool);
void ImGui::DockNodeRemoveWindow(void *, void *, uint32_t);
void ImGui::DockNodeStartMouseMovingWindow(void *, void *);
void * ImGui::DockNodeTreeFindFallbackLeafNode(void *);
void * ImGui::DockNodeTreeFindVisibleNodeByPos(void *, /* struct 0xcf46 */);
void ImGui::DockNodeTreeMerge(void *, void *, void *);
void ImGui::DockNodeTreeSplit(void *, void *, /* type 0x108f8 (LF_ENUM) */, int32_t, float, void *);
void ImGui::DockNodeTreeUpdatePosSize(void *, /* struct 0xcf46 */, /* struct 0xcf46 */, void *);
void ImGui::DockNodeTreeUpdateSplitter(void *);
void DockNodeTreeUpdateSplitterFindTouchingNode(void *, /* type 0x108f8 (LF_ENUM) */, int32_t, void *);
void ImGui::DockNodeUpdate(void *);
void ImGui::DockNodeUpdateFlagsAndCollapse(void *);
void ImGui::DockNodeUpdateHasCentralNodeChild(void *);
void ImGui::DockNodeUpdateTabBar(void *, void *);
void ImGui::DockNodeWindowMenuHandler_Default(void *, void *, void *);
void ImGui::DockNodeWindowMenuUpdate(void *, void *);
void ImGui::DockSettingsHandler_ApplyAll(void *, void *);
void ImGui::DockSettingsHandler_ClearAll(void *, void *);
void DockSettingsHandler_DockNodeToSettings(void *, void *, int32_t);
void ImGui::DockSettingsHandler_ReadLine(void *, void *, /* type 0x603 */, void *);
/* type 0x603 */ ImGui::DockSettingsHandler_ReadOpen(void *, void *, void *);
void ImGui::DockSettingsHandler_WriteAll(void *, void *, void *);
void ImGui::DockSettingsRenameNodeReferences(uint32_t, uint32_t);
void ImGui::End(void);
void ImGui::EndChild(void);
void ImGui::EndDisabled(void);
void ImGui::EndDragDropSource(void);
void ImGui::EndFrame(void);
void ImGui::EndGroup(void);
void ImGui::EndPopup(void);
void * FindBestWheelingWindow(void *);
/* struct 0xcf46 */ ImGui::FindBestWindowPosForPopup(void *);
/* struct 0xcf46 */ ImGui::FindBestWindowPosForPopupEx(void *, void *, /* type 0x674 */, void *, void *, /* type 0x10906 (LF_ENUM) */);
void * FindFrontMostVisibleChildWindow(void *);
void FindHoveredWindow(void);
void * ImGui::FindSettingsHandler(void *);
void * ImGui::FindViewportByID(uint32_t);
void * ImGui::FindWindowByName(void *);
void * FindWindowNavFocusable(int32_t, int32_t, int32_t);
void * ImGui::FindWindowSettingsByWindow(void *);
int32_t ImGui::FixupKeyChord(void *, int32_t);
void FlattenDrawDataIntoSingleLayer(void *);
void ImGui::FocusWindow(void *, int32_t);
void FreeWrapper(/* type 0x603 */, /* type 0x603 */);
void * GetClipboardTextFn_DefaultImpl(/* type 0x603 */);
uint32_t ImGui::GetColorU32(uint32_t, float);
uint32_t ImGui::GetID(void *);
uint32_t ImGuiWindow::GetID(int32_t);
uint32_t ImGuiWindow::GetID(void *, void *);
uint32_t ImGuiWindow::GetIDFromRectangle(void *);
int32_t ImGuiStorage::GetInt(uint32_t, int32_t);
/* type 0x674 */ ImGuiStorage::GetIntRef(uint32_t, int32_t);
void * ImGui::GetKeyChordName(int32_t);
void * ImGui::GetKeyData(void *, /* type 0xced0 (LF_ENUM) */);
void * ImGui::GetKeyName(/* type 0xced0 (LF_ENUM) */);
void * ImGui::GetKeyOwnerData(void *, /* type 0xced0 (LF_ENUM) */);
int32_t ImGui::GetKeyPressedAmount(/* type 0xced0 (LF_ENUM) */, float, float);
float ImGui::GetNavTweakPressedAmount(/* type 0x108f8 (LF_ENUM) */);
/* struct 0x109fe */ ImGui::GetPopupAllowedExtentRect(void *);
/* struct 0x109fe */ GetResizeBorderRect(void *, int32_t, float, float);
void * ImGui::GetShortcutRoutingData(int32_t);
void * ImGui::GetTopMostPopupModal(void);
void * GetViewportBgFgDrawList(void *, /* type 0x23 */, void *);
void * ImGui::GetViewportPlatformMonitor(void *);
/* type 0x603 */ ImGuiStorage::GetVoidPtr(uint32_t);
bool ImGui::GetWindowAlwaysWantOwnViewport(void *);
uint32_t ImAlphaBlendColors(uint32_t, uint32_t);
void * ImFileOpen(void *, void *);
int32_t ImFormatString(char*, /* type 0x23 */, void *, /* type 0x0 */);
void ImFormatStringToTempBuffer(void *, void *, void *, /* type 0x0 */);
void ImFormatStringToTempBufferV(void *, void *, void *, char*);
uint32_t ImHashStr(void *, /* type 0x23 */, uint32_t);
int32_t ImTextCharFromUtf8(/* type 0x675 */, void *, void *);
int32_t ImTextCountCharsFromUtf8(void *, void *);
int32_t ImTextStrFromUtf8(/* type 0x621 */, int32_t, void *, void *, void *);
int32_t ImTextStrToUtf8(char*, int32_t, void *, void *);
/* struct 0xcf46 */ ImTriangleClosestPoint(void *, void *, void *, void *);
void InitOrLoadWindowSettings(void *, void *);
void ImGui::Initialize(void);
bool ImGui::IsItemHovered(int32_t);
bool ImGui::IsKeyChordPressed(int32_t, uint32_t, int32_t);
bool ImGui::IsKeyDown(/* type 0xced0 (LF_ENUM) */);
bool ImGui::IsKeyPressed(/* type 0xced0 (LF_ENUM) */, uint32_t, int32_t);
bool ImGui::IsKeyReleased(/* type 0xced0 (LF_ENUM) */);
bool ImGui::IsMouseClicked(int32_t, uint32_t, int32_t);
bool ImGui::IsMouseDown(int32_t);
bool ImGui::IsMouseDragging(int32_t, float);
bool ImGui::IsMouseHoveringRect(void *, void *, bool);
bool ImGui::IsMouseReleased(int32_t);
bool ImGui::IsPopupOpen(uint32_t, int32_t);
bool ImGui::IsWindowAbove(void *, void *);
bool ImGui::IsWindowContentHoverable(void *, int32_t);
bool ImGui::IsWindowFocused(int32_t);
bool ImGui::ItemAdd(void *, uint32_t, void *, int32_t);
bool ImGui::ItemHoverable(void *, uint32_t, int32_t);
void ImGui::ItemSize(void *, float);
void ImGui::LoadIniSettingsFromDisk(void *);
void ImGui::LoadIniSettingsFromMemory(void *, /* type 0x23 */);
void ImGui::LogFinish(void);
void ImGui::LogRenderedText(void *, void *, void *);
void ImGui::LogText(void *, /* type 0x0 */);
void LogTextV(void *, void *, char*);
void ImGui::LogToClipboard(int32_t);
/* type 0x603 */ MallocWrapper(/* type 0x23 */, /* type 0x603 */);
void ImGui::MarkItemEdited(uint32_t);
/* type 0x603 */ ImGui::MemAlloc(/* type 0x23 */);
void ImGui::MemFree(/* type 0x603 */);
float ImGuiWindow::MenuBarHeight(void);
/* struct 0x109fe */ ImGuiWindow::MenuBarRect(void);
void ImGui::NavApplyItemToResult(void *);
/* struct 0xcf46 */ ImGui::NavCalcPreferredRefPos(void);
void ImGui::NavInitWindow(void *, bool);
void ImGui::NavMoveRequestApplyResult(void);
void ImGui::NavMoveRequestResolveWithLastItem(void *);
void ImGui::NavMoveRequestSubmit(int32_t, int32_t, int32_t, int32_t);
void ImGui::NavProcessItem(void);
void * ImGui::NavRestoreLastChildNavWindow(void *);
void ImGui::NavRestoreLayer(/* type 0x1091c (LF_ENUM) */);
bool ImGui::NavScoreItem(void *);
void ImGui::NavUpdate(void);
void ImGui::NavUpdateAnyRequestFlag(void);
void ImGui::NavUpdateCancelRequest(void);
void ImGui::NavUpdateCreateMoveRequest(void);
void ImGui::NavUpdateCreateWrappingRequest(void);
float ImGui::NavUpdatePageUpPageDown(void);
void ImGui::NavUpdateWindowing(void);
void NavUpdateWindowingHighlightWindow(int32_t);
void ImGui::NavUpdateWindowingOverlay(void);
void ImGui::NewFrame(void);
void ImGui::OpenPopup(void *, int32_t);
void ImGui::OpenPopupEx(uint32_t, int32_t);
void ImGui::OpenPopupOnItemClick(void *, int32_t);
void ImDrawList::PathLineTo(void *);
void ImGui::PopClipRect(void);
void ImGui::PopFont(void);
void ImGui::PopStyleColor(int32_t);
void ImGui::PopStyleVar(int32_t);
void ImGui::PushClipRect(void *, void *, bool);
void ImGui::PushID(int32_t);
void ImGui::PushID(void *);
void ImGui::PushItemFlag(int32_t, bool);
void ImGui::PushItemWidth(float);
void ImGui::PushOverrideID(uint32_t);
void ImGui::PushStyleColor(int32_t, void *);
void ImGui::PushStyleColor(int32_t, uint32_t);
void ImGui::PushStyleVar(int32_t, void *);
void ImGui::PushStyleVar(int32_t, float);
void ImGui::Render(void);
void ImGui::RenderDimmedBackgroundBehindWindow(void *, uint32_t);
void ImGui::RenderDimmedBackgrounds(void);
void ImGui::RenderDragDropTargetRect(void *, void *);
void ImGui::RenderFrame(/* struct 0xcf46 */, /* struct 0xcf46 */, uint32_t, bool, float);
void ImGui::RenderFrameBorder(/* struct 0xcf46 */, /* struct 0xcf46 */, float);
void ImGui::RenderMouseCursor(/* struct 0xcf46 */, float, int32_t, uint32_t, uint32_t, uint32_t);
void ImGui::RenderNavHighlight(void *, uint32_t, int32_t);
void ImGui::RenderText(/* struct 0xcf46 */, void *, void *, bool);
void ImGui::RenderTextClipped(void *, void *, void *, void *, void *, void *, void *);
void ImGui::RenderTextClippedEx(void *, void *, void *, void *, void *, void *, void *, void *);
void ImGui::RenderTextEllipsis(void *, void *, void *, float, float, void *, void *, void *);
void ImGui::RenderWindowDecorations(void *, void *, bool, bool, int32_t, void *, float);
void ImGui::RenderWindowOuterBorders(void *);
void RenderWindowOuterSingleBorder(void *, int32_t, uint32_t, float);
void ImGui::RenderWindowTitleBarContents(void *, void *, void *, /* type 0x630 */);
void ImGui::SameLine(float, float);
void * ImGui::SaveIniSettingsToMemory(/* type 0x623 */);
void ScaleWindow(void *, float);
void ImGui::ScaleWindowsInViewport(void *, float);
/* struct 0xcf46 */ ImGui::ScrollToRectEx(void *, void *, int32_t);
void ImGui::SetActiveID(uint32_t, void *);
void SetClipboardTextFn_DefaultImpl(/* type 0x603 */, void *);
void ImGui::SetCurrentFont(void *);
void ImGui::SetFocusID(uint32_t, void *);
void ImGuiStorage::SetInt(uint32_t, int32_t);
void ImGui::SetItemDefaultFocus(void);
void ImGui::SetItemTooltip(void *, /* type 0x0 */);
void ImGui::SetKeyboardFocusHere(int32_t);
void ImGui::SetLastItemDataForWindow(void *, void *);
void ImGui::SetNavFocusScope(uint32_t);
void ImGui::SetNavID(uint32_t, /* type 0x1091c (LF_ENUM) */, uint32_t, void *);
void ImGui::SetNavWindow(void *);
void SetPlatformImeDataFn_DefaultImpl(void *, void *);
void ImGui::SetScrollHereY(float);
bool ImGui::SetShortcutRouting(int32_t, uint32_t, int32_t);
void ImGui::SetTooltip(void *, /* type 0x0 */);
void ImGuiStorage::SetVoidPtr(uint32_t, /* type 0x603 */);
void ImGui::SetWindowDock(void *, uint32_t, int32_t);
void ImGui::SetWindowPos(void *, void *, int32_t);
void ImGui::SetWindowSize(void *, void *, int32_t);
void SetupDrawListSharedData(void);
bool ImGui::Shortcut(int32_t, uint32_t, int32_t);
void ImGui::StartMouseMovingWindow(void *);
void ImGui::StartMouseMovingWindowOrNode(void *, void *, bool);
int32_t TabItemComparerByDockOrder(void *, void *);
bool ImGui::TestKeyOwner(/* type 0xced0 (LF_ENUM) */, uint32_t);
float ImGuiWindow::TitleBarHeight(void);
/* struct 0x109fe */ ImGuiWindow::TitleBarRect(void);
void ImGui::TranslateWindowsInViewport(void *, void *, void *);
void ImGui::UpdateHoveredWindowAndCaptureFlags(void);
void ImGui::UpdateInputEvents(bool);
void ImGui::UpdateKeyRoutingTable(void *);
void ImGui::UpdateKeyboardInputs(void);
void ImGui::UpdateMouseInputs(void);
void ImGui::UpdateMouseMovingWindowNewFrame(void);
void ImGui::UpdateMouseWheel(void);
bool ImGui::UpdateTryMergeWindowIntoHostViewport(void *, void *);
void ImGui::UpdateViewportPlatformMonitor(void *);
void ImGui::UpdateViewportsEndFrame(void);
void ImGui::UpdateViewportsNewFrame(void);
void UpdateWindowInFocusOrderList(void *, bool, int32_t);
int32_t ImGui::UpdateWindowManualResize(void *, void *, /* type 0x674 */, /* type 0x674 */, int32_t, /* type 0x675 */, void *);
void ImGui::UpdateWindowParentAndRootLinks(void *, int32_t, void *);
void ImGui::WindowSelectViewport(void *);
void WindowSettingsHandler_ApplyAll(void *, void *);
void WindowSettingsHandler_ClearAll(void *, void *);
void WindowSettingsHandler_ReadLine(void *, void *, /* type 0x603 */, void *);
/* type 0x603 */ WindowSettingsHandler_ReadOpen(void *, void *, void *);
void WindowSettingsHandler_WriteAll(void *, void *, void *);
void ImGui::WindowSyncOwnedViewport(void *, void *);
void ImGuiTextBuffer::append(void *, void *);
void ImGuiTextBuffer::appendf(void *, /* type 0x0 */);
void ImGuiTextBuffer::appendfv(void *, char*);
void ImVector<unsigned short>::clear(void);
void ImVector<int>::clear(void);
void ImVector<unsigned int>::clear(void);
void ImVector<float>::clear(void);
void ImVector<ImGuiWindow *>::clear(void);
void ImVector<ImDrawChannel>::clear(void);
void ImVector<ImGuiKeyRoutingData>::clear(void);
void ImVector<ImVec2>::clear(void);
void * ImVector<ImGuiStorage::ImGuiStoragePair>::insert(void *, void *);
void ImVector<unsigned int>::push_back(void *);
void ImVector<ImFont *>::push_back(void *);
void ImVector<ImGuiDockNode *>::push_back(void *);
void ImVector<ImGuiColorMod>::push_back(void *);
void ImVector<ImGuiPopupData>::push_back(void *);
void ImVector<ImGuiSettingsHandler>::push_back(void *);
void ImVector<ImGuiStyleMod>::push_back(void *);
void ImVector<unsigned short>::reserve(int32_t);
void ImVector<unsigned int>::reserve(int32_t);
void ImVector<float>::reserve(int32_t);
void ImVector<ImDrawList *>::reserve(int32_t);
void ImVector<ImGuiViewport *>::reserve(int32_t);
void ImVector<ImGuiViewportP *>::reserve(int32_t);
void ImVector<ImGuiWindow *>::reserve(int32_t);
void ImVector<ImDrawCmd>::reserve(int32_t);
void ImVector<ImDrawVert>::reserve(int32_t);
void ImVector<ImGuiDockNodeSettings>::reserve(int32_t);
void ImVector<ImGuiDockRequest>::reserve(int32_t);
void ImVector<ImGuiFocusScopeData>::reserve(int32_t);
void ImVector<ImGuiInputEvent>::reserve(int32_t);
void ImVector<ImGuiKeyRoutingData>::reserve(int32_t);
void ImVector<ImGuiPopupData>::reserve(int32_t);
void ImVector<ImGuiStackLevelInfo>::reserve(int32_t);
void ImVector<ImGuiStorage::ImGuiStoragePair>::reserve(int32_t);
void ImVector<ImGuiWindowStackData>::reserve(int32_t);
void ImVector<unsigned char>::resize(int32_t);
void ImVector<unsigned short>::resize(int32_t);
void ImVector<ImGuiGroupData>::resize(int32_t);
