// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\imgui\imgui_draw.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\imgui_draw.obj
// 111 function symbol(s) attributed to this object.

void ImDrawListSharedData::ImDrawListSharedData(void);
void ImFontAtlas::ImFontAtlas(void);
void ImDrawList::AddCallback(void *, /* type 0x603 */);
void ImDrawList::AddCircle(void *, float, uint32_t, int32_t, float);
void ImDrawList::AddCircleFilled(void *, float, uint32_t, int32_t);
void ImDrawList::AddConvexPolyFilled(void *, int32_t, uint32_t);
void ImDrawList::AddDrawCmd(void);
void ImGui::AddDrawListToDrawDataEx(void *, void *, void *);
void * ImFontAtlas::AddFont(void *);
void * ImFontAtlas::AddFontFromMemoryCompressedBase85TTF(void *, float, void *, void *);
void * ImFontAtlas::AddFontFromMemoryCompressedTTF(void *, int32_t, float, void *, void *);
void ImFont::AddGlyph(void *, /* type 0x21 */, float, float, float, float, float, float, float, float, float);
void ImDrawList::AddLine(void *, void *, uint32_t, float);
void ImDrawList::AddPolyline(void *, int32_t, uint32_t, int32_t, float);
void ImDrawList::AddRect(void *, void *, uint32_t, float, int32_t, float);
void ImDrawList::AddRectFilled(void *, void *, uint32_t, float, int32_t);
void ImDrawList::AddRectFilledMultiColor(void *, void *, uint32_t, uint32_t, uint32_t, uint32_t);
bool ImFontAtlas::Build(void);
void ImFont::BuildLookupTable(void);
/* struct 0xcf46 */ ImFont::CalcTextSizeA(float, float, float, void *, void *, void *);
void * ImFont::CalcWordWrapPositionA(float, void *, void *, float);
void ImDrawListSplitter::ClearFreeMemory(void);
void ImFont::ClearOutputData(void);
void ImFontAtlas::ClearTexData(void);
void ImFont::GrowIndex(int32_t);
void ImFontAtlasBuildPackCustomRects(void *, /* type 0x603 */);
void ImFontAtlasBuildRender32bppRectFromString(void *, int32_t, int32_t, int32_t, int32_t, void *, char, uint32_t);
void ImFontAtlasBuildRender8bppRectFromString(void *, int32_t, int32_t, int32_t, int32_t, void *, char, unsigned char);
void ImFontAtlasBuildRenderDefaultTexData(void *);
void ImFontAtlasBuildRenderLinesTexData(void *);
bool ImFontAtlasBuildWithStbTruetype(void *);
void ImDrawListSplitter::Merge(void *);
void ImDrawList::PathArcTo(void *, float, float, float, int32_t);
void ImDrawList::PathRect(void *, void *, float, int32_t);
void ImDrawList::PopClipRect(void);
void ImDrawList::PrimRectUV(void *, void *, void *, void *, uint32_t);
void ImDrawList::PrimReserve(int32_t, int32_t);
void ImDrawList::PushClipRect(void *, void *, bool);
void ImDrawList::PushTextureID(/* type 0x603 */);
void ImGui::RenderArrow(void *, /* struct 0xcf46 */, uint32_t, int32_t, float);
void ImGui::RenderArrowDockMenu(void *, /* struct 0xcf46 */, float, uint32_t);
void ImGui::RenderBullet(void *, /* struct 0xcf46 */, uint32_t);
void ImFont::RenderChar(void *, float, void *, uint32_t, /* type 0x21 */);
void ImGui::RenderCheckMark(void *, /* struct 0xcf46 */, uint32_t, float);
void ImGui::RenderColorRectWithAlphaCheckerboard(void *, /* struct 0xcf46 */, /* struct 0xcf46 */, uint32_t, float, /* struct 0xcf46 */, float, int32_t);
void ImGui::RenderRectFilledWithHole(void *, void *, void *, uint32_t, float);
void ImFont::RenderText(void *, float, void *, uint32_t, void *, void *, void *, float, bool);
void ImDrawListSplitter::SetCurrentChannel(void *, int32_t);
void ImGui::ShadeVertsLinearColorGradientKeepAlpha(void *, int32_t, int32_t, /* struct 0xcf46 */, /* struct 0xcf46 */, uint32_t, uint32_t);
void ImDrawListSplitter::Split(void *, int32_t);
void ImGui::StyleColorsDark(void *);
void UnpackBitVectorToFlatIndexList(void *, void *);
int32_t ImDrawList::_CalcCircleAutoSegmentCount(float);
void ImDrawList::_ClearFreeMemory(void);
void ImDrawList::_OnChangedClipRect(void);
void ImDrawList::_OnChangedTextureID(void);
void ImDrawList::_PathArcToFastEx(void *, float, int32_t, int32_t, int32_t);
void ImDrawList::_PathArcToN(void *, float, float, float, int32_t);
void ImDrawList::_ResetForNewFrame(void);
void ImVector<ImDrawCmd>::clear(void);
void ImVector<ImDrawVert>::clear(void);
void ImVector<ImFontAtlasCustomRect>::push_back(void *);
int32_t rect_height_compare(void *, void *);
int32_t rect_original_order(void *, void *);
void ImVector<void *>::reserve(int32_t);
void ImVector<ImDrawChannel>::reserve(int32_t);
void ImVector<ImVec4>::reserve(int32_t);
void ImVector<ImVec2>::reserve_discard(int32_t);
void ImVector<ImFontGlyph>::resize(int32_t);
void stb__lit(void *, uint32_t);
void stb__match(void *, uint32_t);
void * stb_decompress_token(void *);
/* struct 0x1aa33 */ stbrp__skyline_find_best_pos(void *, int32_t, int32_t);
int32_t stbrp__skyline_find_min_y(void *, void *, int32_t, int32_t, /* type 0x674 */);
void * stbtt_FlattenCurves(void *, int32_t, float, void *, /* type 0x674 */, /* type 0x603 */);
int32_t stbtt_GetFontOffsetForIndex_internal(/* type 0x620 */, int32_t);
int32_t stbtt_InitFont_internal(void *, /* type 0x620 */, int32_t);
int32_t stbtt__GetGlyfOffset(void *, int32_t);
int32_t stbtt__GetGlyphShapeT2(void *, int32_t, void *);
int32_t stbtt__GetGlyphShapeTT(void *, int32_t, void *);
unsigned char stbtt__buf_peek8(void *);
/* struct 0x114ec */ stbtt__cff_get_index(void *);
/* struct 0x114ec */ stbtt__cff_index_get(/* struct 0x114ec */, int32_t);
uint32_t stbtt__cff_int(void *);
/* struct 0x114ec */ stbtt__cid_get_glyph_subrs(void *, int32_t);
int32_t stbtt__close_shape(void *, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
void stbtt__csctx_close_shape(void *);
void stbtt__csctx_rccurve_to(void *, float, float, float, float, float, float);
void stbtt__csctx_rline_to(void *, float, float);
void stbtt__csctx_rmove_to(void *, float, float);
void stbtt__csctx_v(void *, unsigned char, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
/* struct 0x114ec */ stbtt__dict_get(void *, int32_t);
void stbtt__fill_active_edges_new(/* type 0x640 */, /* type 0x640 */, int32_t, void *, float);
uint32_t stbtt__find_table(/* type 0x620 */, uint32_t, void *);
/* struct 0x114ec */ stbtt__get_subrs(/* struct 0x114ec */, /* struct 0x114ec */);
void stbtt__h_prefilter(/* type 0x620 */, int32_t, int32_t, int32_t, uint32_t);
void stbtt__handle_clipped_edge(/* type 0x640 */, int32_t, void *, float, float, float, float);
void stbtt__rasterize(void *, void *, /* type 0x674 */, int32_t, float, float, float, float, int32_t, int32_t, int32_t, /* type 0x603 */);
void stbtt__rasterize_sorted_edges(void *, void *, int32_t, int32_t, int32_t, int32_t, /* type 0x603 */);
int32_t stbtt__run_charstring(void *, int32_t, void *);
void stbtt__sort_edges_quicksort(void *, int32_t);
void stbtt__tesselate_cubic(void *, /* type 0x674 */, float, float, float, float, float, float, float, float, float, int32_t);
int32_t stbtt__tesselate_curve(void *, /* type 0x674 */, float, float, float, float, float, float, float, int32_t);
void stbtt__v_prefilter(/* type 0x620 */, int32_t, int32_t, int32_t, uint32_t);
void stbrp_init_target(void *, int32_t, int32_t, void *, int32_t);
int32_t stbrp_pack_rects(void *, void *, int32_t);
int32_t stbtt_FindGlyphIndex(void *, int32_t);
int32_t stbtt_GetGlyphShape(void *, int32_t, void *);
void stbtt_MakeGlyphBitmapSubpixel(void *, /* type 0x620 */, int32_t, int32_t, int32_t, float, float, float, float, int32_t);
int32_t stbtt_PackFontRangesRenderIntoRects(void *, void *, void *, int32_t, void *);
void stbtt_Rasterize(void *, float, void *, int32_t, float, float, float, float, int32_t, int32_t, int32_t, /* type 0x603 */);
