// Reconstructed from PDB debug info.
// Original path : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\imgui\implot.cpp
// Compiled into : D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\x64\Release-Zeus\implot.obj
// 70 function symbol(s) attributed to this object.

void ImPlotAxis::ImPlotAxis(void);
void ImPlotContext::ImPlotContext(void);
void ImPlotPlot::ImPlotPlot(void);
void ImPlotStyle::ImPlotStyle(void);
void ImVector<ImPlotTick>::~ImVector<ImPlotTick>(void);
void ImPlotAxis::~ImPlotAxis(void);
void ImPlot::AddTextCentered(void *, /* struct 0xcf46 */, uint32_t, void *, void *);
void ImPlot::AddTextVertical(void *, /* struct 0xcf46 */, uint32_t, void *, void *);
void * ImPlotTicker::AddTick(double, bool, int32_t, bool, void *, /* type 0x603 */);
void * ImPlotTicker::AddTick(/* struct 0x11717 */);
/* struct 0x11662 */ ImPlot::AddTime(void *, int32_t, int32_t);
bool ImPlot::AllAxesInputLocked(void *, int32_t);
int32_t ImPlotColormapData::Append(void *, void *, int32_t, bool);
void ImPlotAxis::ApplyFit(float);
void ImPlot::BeginDisabledControls(bool);
bool ImPlot::BeginPlot(void *, void *, int32_t);
/* struct 0xcf46 */ ImPlot::CalcLegendSize(void *, void *, void *, bool);
/* struct 0x11662 */ ImPlot::CombineDateTime(void *, void *);
void ImPlotAxis::Constrain(void);
void ImPlot::EndDisabledControls(bool);
void ImPlot::EndPlot(void);
/* struct 0x11662 */ ImPlot::FloorTime(void *, int32_t);
int32_t ImPlot::FormatDate(void *, /* type 0x670 */, int32_t, int32_t, bool);
int32_t ImPlot::FormatTime(void *, /* type 0x670 */, int32_t, int32_t, bool);
int32_t ImPlot::Formatter_Default(double, /* type 0x670 */, int32_t, /* type 0x603 */);
int32_t ImPlot::Formatter_Time(double, /* type 0x670 */, int32_t, /* type 0x603 */);
/* struct 0xd06e */ ImPlot::GetAutoColor(int32_t);
float ImPlot::GetDateTimeWidth(/* struct 0x115a7 */);
int32_t ImPlotColormapData::GetIndex(void *);
void * ImPool<ImPlotPlot>::GetOrAddByKey(uint32_t);
uint32_t ImPlot::GetStyleColorU32(int32_t);
/* struct 0xd06e */ ImPlot::GetStyleColorVec4(int32_t);
int32_t ImPlot::GetTimeStep(int32_t, int32_t);
int32_t ImPlot::GetYear(void *);
void ImPlot::Initialize(void *);
bool ImPlot::IsLeapYear(int32_t);
bool ImPlotAxis::IsLocked(void);
void ImPlot::LabelAxisValue(void *, double, /* type 0x670 */, int32_t, bool);
int32_t ImPlot::LegendSortingComp(void *, void *);
void ImPlot::Locator_Default(void *, void *, float, bool, void *, /* type 0x603 */);
void ImPlot::Locator_Time(void *, void *, float, bool, void *, /* type 0x603 */);
/* struct 0x11662 */ ImPlot::MkTime(void *);
void ImPlot::PadAndDatumAxesX(void *, void *, void *, void *);
void ImPlot::PadAndDatumAxesY(void *, void *, void *, void *);
void ImPlot::PushColormap(int32_t);
void ImPlot::PushPlotClipRect(float);
void ImPlot::RenderGridLinesX(void *, void *, void *, uint32_t, uint32_t, float, float);
void ImPlot::RenderGridLinesY(void *, void *, void *, uint32_t, uint32_t, float, float);
void ImPlot::ResetCtxForNextPlot(void *);
void ImPlotAxis::SetAspect(double);
bool ImPlotAxis::SetMax(double, bool);
bool ImPlotAxis::SetMin(double, bool);
void ImPlotAxis::SetRange(double, double);
void ImPlot::SetupAxisLimits(int32_t, double, double, int32_t);
void ImPlot::SetupFinish(void);
void ImPlot::SetupLegend(int32_t, int32_t);
void ImPlot::ShowAxisContextMenu(void *, void *, bool);
bool ImPlot::ShowDatePicker(void *, /* type 0x674 */, void *, void *, void *);
bool ImPlot::ShowLegendContextMenu(void *, bool);
bool ImPlot::ShowLegendEntries(void *, void *, bool, void *, void *, bool, void *);
void ImPlot::ShowPlotContextMenu(void *);
void ImPlot::ShowSubplotsContextMenu(void *);
bool ImPlot::ShowTimePicker(void *, void *);
void ImPlot::StyleColorsAuto(void *);
void ImPlot::SubplotSetCell(int32_t, int32_t);
void ImPlot::UpdateAxisColors(void *);
bool ImPlot::UpdateInput(void *);
void ImPlotAxis::UpdateTransformCache(void);
void ImPlotColormapData::_AppendTable(int32_t);
